@rem 15.09.2003
@rem copies source files generated by Telelogic Tau
@set P_SRC=C:\Kolevatov\Projects\SDL\STACK80211\Make
@set P_DEST=C:\Kolevatov\Projects\STACK802_11\GENER
if exist %P_DEST%\*.c del %P_DEST%\*.c
if exist %P_DEST%\*.h del %P_DEST%\*.h
copy %P_SRC%\*.c %P_DEST%\*.c
copy %P_SRC%\*.h %P_DEST%\*.h