
/* Program generated by Cadvanced 4.3.0  */
#define XSCT_CADVANCED

#define SCT_VERSION_4_3
#include "scttypes.h"
#include "ctypes.h"
#include "sysincl_exp_gen.h"
#ifdef XINCLUDE_HS_FILE
#include "SysSTA.hs"
#endif
#ifdef XCTRACE
static char  xFileName[] = "C:\\Kolevatov\\Projects\\SDL\\STACK80211\\Make\\sysincl_exp_gen.c";
#endif


/*************************************************************************
**                  #CODE directives, #BODY sections                    **
*************************************************************************/

/*************************************************************************
**                  SECTION Variables and Functions                     **
*************************************************************************/

/*****
* PACKAGE sysincl_exp
* #SDTREF(TEXT,C:\Kolevatov\Projects\SDL\STACK80211\sysincl_exp.h,4,9)
******/
XCONST struct xPackageIdStruct yPacR_z_sysincl_exp__sysincl_exp = {xPackageEC
  xSymbTLink((xIdNode)0, (xIdNode)0), (xIdNode)&xSymbolTableIdRec
  xIdNames("sysincl_exp") XCOMMON_EXTRAS xIdNames(0) XPAC_EXTRAS};

/*****
* NEWTYPE CA_sysincl_exp_6_X_Octet  (BODY section)
* <<PACKAGE sysincl_exp>>
* #SDTREF(TEXT,C:\\Kolevatov\\Projects\\SDL\\STACK80211\\procpkt_exp.h,61)
******/

/* *** CA_sysincl_exp_6_X_Octet *** */
tSDLArrayInfo ySDL_z_sysincl_exp_1Q_CA_sysincl_exp_6_X_Octet =
  {type_SDL_Carray, 6,
  (xptrint)sizeof(z_sysincl_exp_1Q_CA_sysincl_exp_6_X_Octet) T_SDL_OPFUNCS(0)
  T_SDL_EXTRA_VALUE T_SDL_Names("CA_sysincl_exp_6_X_Octet")
  xRaWF((xIdNode)&yPacR_z_sysincl_exp__sysincl_exp)
  xRaWF(&ySrtR_z_sysincl_exp_1Q_CA_sysincl_exp_6_X_Octet),
  (tSDLTypeInfo *)&ySDL_SDL_Octet, SDL_INTEGER_LIT(6)
  xRaWF((tSDLTypeInfo *)&ySDL_SDL_Integer) xRaWF(0)};
#ifndef XOPTSORT
XCONST struct xSortIdStruct ySrtR_z_sysincl_exp_1Q_CA_sysincl_exp_6_X_Octet =
  {xSortEC xSymbTLink((xIdNode)0, (xIdNode)0),
  (xIdNode)&yPacR_z_sysincl_exp__sysincl_exp
  xIdNames("CA_sysincl_exp_6_X_Octet") XCOMMON_EXTRAS xFreF(0)
  xAssF(yAss_z_sysincl_exp_1Q_CA_sysincl_exp_6_X_Octet)
  xEqF(yEq_z_sysincl_exp_1Q_CA_sysincl_exp_6_X_Octet) xTestF(0),
  (xptrint)sizeof(z_sysincl_exp_1Q_CA_sysincl_exp_6_X_Octet), xCArray,
  &xSrtR_SDL_Octet, xSrtN_SDL_Integer, 0, SDL_INTEGER_LIT(6)-1, 0, 0
  xRaWF((tSDLTypeInfo *)&ySDL_z_sysincl_exp_1Q_CA_sysincl_exp_6_X_Octet)
  XSRT_EXTRAS};
#endif

/*-------------------TSTI-------------------*/
#ifdef XEINDEX
SDL_Integer yTstI_z_sysincl_exp_1Q_CA_sysincl_exp_6_X_Octet(SDL_Integer yExpr)
{
  if (yExpr < 0 || yExpr >= SDL_INTEGER_LIT(6)) {
    xErrorIndex((tSDLTypeInfo *)&ySDL_SDL_Integer, &yExpr);
    return 0;
  }
  return yExpr;
}
#endif

/*****
* NEWTYPE tagMACADDR  (BODY section)
* <<PACKAGE sysincl_exp>>
* #SDTREF(TEXT,C:\\Kolevatov\\Projects\\SDL\\STACK80211\\procpkt_exp.h,61)
******/

/* *** tagMACADDR *** */
static tSDLFieldInfo fSDL_z_sysincl_exp_1R_tagMACADDR[] = {
  {(tSDLTypeInfo *)&ySDL_z_sysincl_exp_1Q_CA_sysincl_exp_6_X_Octet
    T_SDL_Names("ab"), xOffsetOf(z_sysincl_exp_1R_tagMACADDR, ab), 0}
};
tSDLStructInfo ySDL_z_sysincl_exp_1R_tagMACADDR = {type_SDL_Struct, 6,
  (xptrint)sizeof(z_sysincl_exp_1R_tagMACADDR) T_SDL_OPFUNCS(0)
  T_SDL_EXTRA_VALUE T_SDL_Names("tagMACADDR")
  xRaWF((xIdNode)&yPacR_z_sysincl_exp__sysincl_exp)
  xRaWF(&ySrtR_z_sysincl_exp_1R_tagMACADDR), fSDL_z_sysincl_exp_1R_tagMACADDR,
  1};
#ifndef XOPTSORT
XCONST struct xSortIdStruct ySrtR_z_sysincl_exp_1R_tagMACADDR = {xSortEC
  xSymbTLink((xIdNode)0, (xIdNode)0),
  (xIdNode)&yPacR_z_sysincl_exp__sysincl_exp xIdNames("tagMACADDR")
  XCOMMON_EXTRAS xFreF(0) xAssF(yAss_z_sysincl_exp_1R_tagMACADDR)
  xEqF(yEq_z_sysincl_exp_1R_tagMACADDR) xTestF(0),
  (xptrint)sizeof(z_sysincl_exp_1R_tagMACADDR), xStruct, (xSortIdNode)0,
  (xSortIdNode)0, 0, 0, 0, 0
  xRaWF((tSDLTypeInfo *)&ySDL_z_sysincl_exp_1R_tagMACADDR) XSRT_EXTRAS};
#endif
#ifndef XOPTSTRUCT
/*---------------COMPONENTS----------------*/
static XCONST struct xVarIdStruct yVarR_z_sysincl_exp_1R7_ab = {xVariableEC
  xSymbTLink((xIdNode)0, (xIdNode)0),
  (xIdNode)&ySrtR_z_sysincl_exp_1R_tagMACADDR xIdNames("ab") XCOMMON_EXTRAS,
  &ySrtR_z_sysincl_exp_1Q_CA_sysincl_exp_6_X_Octet,
  (tSDLTypeInfo *)&ySDL_z_sysincl_exp_1Q_CA_sysincl_exp_6_X_Octet,
  xOffsetOf(z_sysincl_exp_1R_tagMACADDR, ab), (xptrint)0, 0 XVAR_EXTRAS};
#endif

/*****
* NEWTYPE tagPKT  (BODY section)
* <<PACKAGE sysincl_exp>>
* #SDTREF(TEXT,C:\\Kolevatov\\Projects\\SDL\\STACK80211\\procpkt_exp.h,68)
******/

/* *** tagPKT *** */
static tSDLFieldInfo fSDL_z_sysincl_exp_1S_tagPKT[] = {
  {(tSDLTypeInfo *)&ySDL_z_sysincl_exp_1R_tagMACADDR  T_SDL_Names("da"),
    xOffsetOf(z_sysincl_exp_1S_tagPKT, da), 0},
  {(tSDLTypeInfo *)&ySDL_z_sysincl_exp_1R_tagMACADDR  T_SDL_Names("sa"),
    xOffsetOf(z_sysincl_exp_1S_tagPKT, sa), 0},
  {(tSDLTypeInfo *)&ySDL_z_sysincl_exp_1R_tagMACADDR  T_SDL_Names("bssid"),
    xOffsetOf(z_sysincl_exp_1S_tagPKT, bssid), 0},
  {(tSDLTypeInfo *)&ySDL_z_sysincl_exp_1R_tagMACADDR  T_SDL_Names("ra"),
    xOffsetOf(z_sysincl_exp_1S_tagPKT, ra), 0},
  {(tSDLTypeInfo *)&ySDL_z_sysincl_exp_1R_tagMACADDR  T_SDL_Names("ta"),
    xOffsetOf(z_sysincl_exp_1S_tagPKT, ta), 0},
  {(tSDLTypeInfo *)&ySDL_SDL_Integer  T_SDL_Names("nType"),
    xOffsetOf(z_sysincl_exp_1S_tagPKT, nType), 0},
  {(tSDLTypeInfo *)&ySDL_SDL_Integer  T_SDL_Names("nSubtype"),
    xOffsetOf(z_sysincl_exp_1S_tagPKT, nSubtype), 0},
  {(tSDLTypeInfo *)&ySDL_SDL_Integer  T_SDL_Names("nSize"),
    xOffsetOf(z_sysincl_exp_1S_tagPKT, nSize), 0},
  {(tSDLTypeInfo *)&ySDL_SDL_Integer  T_SDL_Names("nSeqNo"),
    xOffsetOf(z_sysincl_exp_1S_tagPKT, nSeqNo), 0},
  {(tSDLTypeInfo *)&ySDL_SDL_Integer  T_SDL_Names("nFragNo"),
    xOffsetOf(z_sysincl_exp_1S_tagPKT, nFragNo), 0},
  {(tSDLTypeInfo *)&ySDL_SDL_Real  T_SDL_Names("dDurat"),
    xOffsetOf(z_sysincl_exp_1S_tagPKT, dDurat), 0},
  {(tSDLTypeInfo *)&ySDL_SDL_Integer  T_SDL_Names("nCRC32"),
    xOffsetOf(z_sysincl_exp_1S_tagPKT, nCRC32), 0},
  {(tSDLTypeInfo *)&ySDL_SDL_Integer  T_SDL_Names("bRetry"),
    xOffsetOf(z_sysincl_exp_1S_tagPKT, bRetry), 0},
  {(tSDLTypeInfo *)&ySDL_SDL_Integer  T_SDL_Names("bMF"),
    xOffsetOf(z_sysincl_exp_1S_tagPKT, bMF), 0},
  {(tSDLTypeInfo *)&ySDL_SDL_Integer  T_SDL_Names("bValid"),
    xOffsetOf(z_sysincl_exp_1S_tagPKT, bValid), 0},
  {(tSDLTypeInfo *)&ySDL_SDL_Integer  T_SDL_Names("m_bHaveData"),
    xOffsetOf(z_sysincl_exp_1S_tagPKT, m_bHaveData), 0},
  {(tSDLTypeInfo *)&ySDL_z_ctypes_3_Charstar  T_SDL_Names("m_pData"),
    xOffsetOf(z_sysincl_exp_1S_tagPKT, m_pData), 0}
};
tSDLStructInfo ySDL_z_sysincl_exp_1S_tagPKT = {type_SDL_Struct, 6,
  (xptrint)sizeof(z_sysincl_exp_1S_tagPKT) T_SDL_OPFUNCS(0) T_SDL_EXTRA_VALUE
  T_SDL_Names("tagPKT") xRaWF((xIdNode)&yPacR_z_sysincl_exp__sysincl_exp)
  xRaWF(&ySrtR_z_sysincl_exp_1S_tagPKT), fSDL_z_sysincl_exp_1S_tagPKT, 17};
#ifndef XOPTSORT
XCONST struct xSortIdStruct ySrtR_z_sysincl_exp_1S_tagPKT = {xSortEC
  xSymbTLink((xIdNode)0, (xIdNode)0),
  (xIdNode)&yPacR_z_sysincl_exp__sysincl_exp xIdNames("tagPKT") XCOMMON_EXTRAS
  xFreF(0) xAssF(yAss_z_sysincl_exp_1S_tagPKT)
  xEqF(yEq_z_sysincl_exp_1S_tagPKT) xTestF(0),
  (xptrint)sizeof(z_sysincl_exp_1S_tagPKT), xStruct, (xSortIdNode)0,
  (xSortIdNode)0, 0, 0, 0, 0
  xRaWF((tSDLTypeInfo *)&ySDL_z_sysincl_exp_1S_tagPKT) XSRT_EXTRAS};
#endif
#ifndef XOPTSTRUCT
/*---------------COMPONENTS----------------*/
static XCONST struct xVarIdStruct yVarR_z_sysincl_exp_1S13_da = {xVariableEC
  xSymbTLink((xIdNode)0, (xIdNode)0), (xIdNode)&ySrtR_z_sysincl_exp_1S_tagPKT
  xIdNames("da") XCOMMON_EXTRAS, &ySrtR_z_sysincl_exp_1R_tagMACADDR,
  (tSDLTypeInfo *)&ySDL_z_sysincl_exp_1R_tagMACADDR,
  xOffsetOf(z_sysincl_exp_1S_tagPKT, da), (xptrint)0, 0 XVAR_EXTRAS};
static XCONST struct xVarIdStruct yVarR_z_sysincl_exp_1S14_sa = {xVariableEC
  xSymbTLink((xIdNode)0, (xIdNode)0), (xIdNode)&ySrtR_z_sysincl_exp_1S_tagPKT
  xIdNames("sa") XCOMMON_EXTRAS, &ySrtR_z_sysincl_exp_1R_tagMACADDR,
  (tSDLTypeInfo *)&ySDL_z_sysincl_exp_1R_tagMACADDR,
  xOffsetOf(z_sysincl_exp_1S_tagPKT, sa), (xptrint)0, 0 XVAR_EXTRAS};
static XCONST struct xVarIdStruct yVarR_z_sysincl_exp_1S15_bssid = {xVariableEC
  xSymbTLink((xIdNode)0, (xIdNode)0), (xIdNode)&ySrtR_z_sysincl_exp_1S_tagPKT
  xIdNames("bssid") XCOMMON_EXTRAS, &ySrtR_z_sysincl_exp_1R_tagMACADDR,
  (tSDLTypeInfo *)&ySDL_z_sysincl_exp_1R_tagMACADDR,
  xOffsetOf(z_sysincl_exp_1S_tagPKT, bssid), (xptrint)0, 0 XVAR_EXTRAS};
static XCONST struct xVarIdStruct yVarR_z_sysincl_exp_1S16_ra = {xVariableEC
  xSymbTLink((xIdNode)0, (xIdNode)0), (xIdNode)&ySrtR_z_sysincl_exp_1S_tagPKT
  xIdNames("ra") XCOMMON_EXTRAS, &ySrtR_z_sysincl_exp_1R_tagMACADDR,
  (tSDLTypeInfo *)&ySDL_z_sysincl_exp_1R_tagMACADDR,
  xOffsetOf(z_sysincl_exp_1S_tagPKT, ra), (xptrint)0, 0 XVAR_EXTRAS};
static XCONST struct xVarIdStruct yVarR_z_sysincl_exp_1S17_ta = {xVariableEC
  xSymbTLink((xIdNode)0, (xIdNode)0), (xIdNode)&ySrtR_z_sysincl_exp_1S_tagPKT
  xIdNames("ta") XCOMMON_EXTRAS, &ySrtR_z_sysincl_exp_1R_tagMACADDR,
  (tSDLTypeInfo *)&ySDL_z_sysincl_exp_1R_tagMACADDR,
  xOffsetOf(z_sysincl_exp_1S_tagPKT, ta), (xptrint)0, 0 XVAR_EXTRAS};
static XCONST struct xVarIdStruct yVarR_z_sysincl_exp_1S18_nType = {xVariableEC
  xSymbTLink((xIdNode)0, (xIdNode)0), (xIdNode)&ySrtR_z_sysincl_exp_1S_tagPKT
  xIdNames("nType") XCOMMON_EXTRAS, &xSrtR_SDL_Integer,
  (tSDLTypeInfo *)&ySDL_SDL_Integer, xOffsetOf(z_sysincl_exp_1S_tagPKT, nType),
  (xptrint)0, 0 XVAR_EXTRAS};
static XCONST struct xVarIdStruct yVarR_z_sysincl_exp_1S19_nSubtype =
  {xVariableEC xSymbTLink((xIdNode)0, (xIdNode)0),
  (xIdNode)&ySrtR_z_sysincl_exp_1S_tagPKT xIdNames("nSubtype") XCOMMON_EXTRAS,
  &xSrtR_SDL_Integer, (tSDLTypeInfo *)&ySDL_SDL_Integer,
  xOffsetOf(z_sysincl_exp_1S_tagPKT, nSubtype), (xptrint)0, 0 XVAR_EXTRAS};
static XCONST struct xVarIdStruct yVarR_z_sysincl_exp_1S1A_nSize = {xVariableEC
  xSymbTLink((xIdNode)0, (xIdNode)0), (xIdNode)&ySrtR_z_sysincl_exp_1S_tagPKT
  xIdNames("nSize") XCOMMON_EXTRAS, &xSrtR_SDL_Integer,
  (tSDLTypeInfo *)&ySDL_SDL_Integer, xOffsetOf(z_sysincl_exp_1S_tagPKT, nSize),
  (xptrint)0, 0 XVAR_EXTRAS};
static XCONST struct xVarIdStruct yVarR_z_sysincl_exp_1S1B_nSeqNo =
  {xVariableEC xSymbTLink((xIdNode)0, (xIdNode)0),
  (xIdNode)&ySrtR_z_sysincl_exp_1S_tagPKT xIdNames("nSeqNo") XCOMMON_EXTRAS,
  &xSrtR_SDL_Integer, (tSDLTypeInfo *)&ySDL_SDL_Integer,
  xOffsetOf(z_sysincl_exp_1S_tagPKT, nSeqNo), (xptrint)0, 0 XVAR_EXTRAS};
static XCONST struct xVarIdStruct yVarR_z_sysincl_exp_1S1C_nFragNo =
  {xVariableEC xSymbTLink((xIdNode)0, (xIdNode)0),
  (xIdNode)&ySrtR_z_sysincl_exp_1S_tagPKT xIdNames("nFragNo") XCOMMON_EXTRAS,
  &xSrtR_SDL_Integer, (tSDLTypeInfo *)&ySDL_SDL_Integer,
  xOffsetOf(z_sysincl_exp_1S_tagPKT, nFragNo), (xptrint)0, 0 XVAR_EXTRAS};
static XCONST struct xVarIdStruct yVarR_z_sysincl_exp_1S1D_dDurat =
  {xVariableEC xSymbTLink((xIdNode)0, (xIdNode)0),
  (xIdNode)&ySrtR_z_sysincl_exp_1S_tagPKT xIdNames("dDurat") XCOMMON_EXTRAS,
  &xSrtR_SDL_Real, (tSDLTypeInfo *)&ySDL_SDL_Real,
  xOffsetOf(z_sysincl_exp_1S_tagPKT, dDurat), (xptrint)0, 0 XVAR_EXTRAS};
static XCONST struct xVarIdStruct yVarR_z_sysincl_exp_1S1E_nCRC32 =
  {xVariableEC xSymbTLink((xIdNode)0, (xIdNode)0),
  (xIdNode)&ySrtR_z_sysincl_exp_1S_tagPKT xIdNames("nCRC32") XCOMMON_EXTRAS,
  &xSrtR_SDL_Integer, (tSDLTypeInfo *)&ySDL_SDL_Integer,
  xOffsetOf(z_sysincl_exp_1S_tagPKT, nCRC32), (xptrint)0, 0 XVAR_EXTRAS};
static XCONST struct xVarIdStruct yVarR_z_sysincl_exp_1S1F_bRetry =
  {xVariableEC xSymbTLink((xIdNode)0, (xIdNode)0),
  (xIdNode)&ySrtR_z_sysincl_exp_1S_tagPKT xIdNames("bRetry") XCOMMON_EXTRAS,
  &xSrtR_SDL_Integer, (tSDLTypeInfo *)&ySDL_SDL_Integer,
  xOffsetOf(z_sysincl_exp_1S_tagPKT, bRetry), (xptrint)0, 0 XVAR_EXTRAS};
static XCONST struct xVarIdStruct yVarR_z_sysincl_exp_1S1G_bMF = {xVariableEC
  xSymbTLink((xIdNode)0, (xIdNode)0), (xIdNode)&ySrtR_z_sysincl_exp_1S_tagPKT
  xIdNames("bMF") XCOMMON_EXTRAS, &xSrtR_SDL_Integer,
  (tSDLTypeInfo *)&ySDL_SDL_Integer, xOffsetOf(z_sysincl_exp_1S_tagPKT, bMF),
  (xptrint)0, 0 XVAR_EXTRAS};
static XCONST struct xVarIdStruct yVarR_z_sysincl_exp_1S1H_bValid =
  {xVariableEC xSymbTLink((xIdNode)0, (xIdNode)0),
  (xIdNode)&ySrtR_z_sysincl_exp_1S_tagPKT xIdNames("bValid") XCOMMON_EXTRAS,
  &xSrtR_SDL_Integer, (tSDLTypeInfo *)&ySDL_SDL_Integer,
  xOffsetOf(z_sysincl_exp_1S_tagPKT, bValid), (xptrint)0, 0 XVAR_EXTRAS};
static XCONST struct xVarIdStruct yVarR_z_sysincl_exp_1S1I_m_bHaveData =
  {xVariableEC xSymbTLink((xIdNode)0, (xIdNode)0),
  (xIdNode)&ySrtR_z_sysincl_exp_1S_tagPKT xIdNames("m_bHaveData")
  XCOMMON_EXTRAS, &xSrtR_SDL_Integer, (tSDLTypeInfo *)&ySDL_SDL_Integer,
  xOffsetOf(z_sysincl_exp_1S_tagPKT, m_bHaveData), (xptrint)0, 0 XVAR_EXTRAS};
static XCONST struct xVarIdStruct yVarR_z_sysincl_exp_1S1J_m_pData =
  {xVariableEC xSymbTLink((xIdNode)0, (xIdNode)0),
  (xIdNode)&ySrtR_z_sysincl_exp_1S_tagPKT xIdNames("m_pData") XCOMMON_EXTRAS,
  &ySrtR_z_ctypes_3_Charstar, (tSDLTypeInfo *)&ySDL_z_ctypes_3_Charstar,
  xOffsetOf(z_sysincl_exp_1S_tagPKT, m_pData), (xptrint)0, 0 XVAR_EXTRAS};
#endif

/*****
* NEWTYPE Ref_sysincl_exp_Octet  (BODY section)
* <<PACKAGE sysincl_exp>>
* #SDTREF(TEXT,C:\\Kolevatov\\Projects\\SDL\\STACK80211\\proc_mac_exp.h,33)
******/

/* *** Ref_sysincl_exp_Octet *** */
tSDLGenInfo ySDL_z_sysincl_exp_1T_Ref_sysincl_exp_Octet = {type_SDL_Ref, 0,
  (xptrint)sizeof(z_sysincl_exp_1T_Ref_sysincl_exp_Octet) T_SDL_OPFUNCS(0)
  T_SDL_EXTRA_VALUE T_SDL_Names("Ref_sysincl_exp_Octet")
  xRaWF((xIdNode)&yPacR_z_sysincl_exp__sysincl_exp)
  xRaWF(&ySrtR_z_sysincl_exp_1T_Ref_sysincl_exp_Octet),
  (tSDLTypeInfo *)&ySDL_SDL_Octet};
#ifndef XOPTSORT
XCONST struct xSortIdStruct ySrtR_z_sysincl_exp_1T_Ref_sysincl_exp_Octet =
  {xSortEC xSymbTLink((xIdNode)0, (xIdNode)0),
  (xIdNode)&yPacR_z_sysincl_exp__sysincl_exp xIdNames("Ref_sysincl_exp_Octet")
  XCOMMON_EXTRAS xFreF(0) xAssF(0) xEqF(0) xTestF(0),
  (xptrint)sizeof(z_sysincl_exp_1T_Ref_sysincl_exp_Octet), xRef,
  &xSrtR_SDL_Octet, (xSortIdNode)0, 0, 0, 0, 0
  xRaWF((tSDLTypeInfo *)&ySDL_z_sysincl_exp_1T_Ref_sysincl_exp_Octet)
  XSRT_EXTRAS};
#endif

void * yMkAddr_z_sysincl_exp_1T_Ref_sysincl_exp_Octet (z_sysincl_exp_1T_Ref_sysincl_exp_Octet yMkValue, z_sysincl_exp_1T_Ref_sysincl_exp_Octet * yMkResult)
{
  *yMkResult = yMkValue;
  return (void *)yMkResult;
}

/*****
* NEWTYPE tagFLATARRAY  (BODY section)
* <<PACKAGE sysincl_exp>>
* #SDTREF(TEXT,C:\\Kolevatov\\Projects\\SDL\\STACK80211\\proc_mac_exp.h,33)
******/

/* *** tagFLATARRAY *** */
static tSDLFieldInfo fSDL_z_sysincl_exp_1U_tagFLATARRAY[] = {
  {(tSDLTypeInfo *)&ySDL_SDL_Integer  T_SDL_Names("nSize"),
    xOffsetOf(z_sysincl_exp_1U_tagFLATARRAY, nSize), 0},
  {(tSDLTypeInfo *)&ySDL_z_sysincl_exp_1T_Ref_sysincl_exp_Octet
    T_SDL_Names("pData"), xOffsetOf(z_sysincl_exp_1U_tagFLATARRAY, pData), 0}
};
tSDLStructInfo ySDL_z_sysincl_exp_1U_tagFLATARRAY = {type_SDL_Struct, 2,
  (xptrint)sizeof(z_sysincl_exp_1U_tagFLATARRAY) T_SDL_OPFUNCS(0)
  T_SDL_EXTRA_VALUE T_SDL_Names("tagFLATARRAY")
  xRaWF((xIdNode)&yPacR_z_sysincl_exp__sysincl_exp)
  xRaWF(&ySrtR_z_sysincl_exp_1U_tagFLATARRAY),
  fSDL_z_sysincl_exp_1U_tagFLATARRAY, 2};
#ifndef XOPTSORT
XCONST struct xSortIdStruct ySrtR_z_sysincl_exp_1U_tagFLATARRAY = {xSortEC
  xSymbTLink((xIdNode)0, (xIdNode)0),
  (xIdNode)&yPacR_z_sysincl_exp__sysincl_exp xIdNames("tagFLATARRAY")
  XCOMMON_EXTRAS xFreF(0) xAssF(0) xEqF(yEq_z_sysincl_exp_1U_tagFLATARRAY)
  xTestF(0), (xptrint)sizeof(z_sysincl_exp_1U_tagFLATARRAY), xStruct,
  (xSortIdNode)0, (xSortIdNode)0, 0, 0, 0, 0
  xRaWF((tSDLTypeInfo *)&ySDL_z_sysincl_exp_1U_tagFLATARRAY) XSRT_EXTRAS};
#endif
#ifndef XOPTSTRUCT
/*---------------COMPONENTS----------------*/
static XCONST struct xVarIdStruct yVarR_z_sysincl_exp_1U9_nSize = {xVariableEC
  xSymbTLink((xIdNode)0, (xIdNode)0),
  (xIdNode)&ySrtR_z_sysincl_exp_1U_tagFLATARRAY xIdNames("nSize")
  XCOMMON_EXTRAS, &xSrtR_SDL_Integer, (tSDLTypeInfo *)&ySDL_SDL_Integer,
  xOffsetOf(z_sysincl_exp_1U_tagFLATARRAY, nSize), (xptrint)0, 0 XVAR_EXTRAS};
static XCONST struct xVarIdStruct yVarR_z_sysincl_exp_1UA_pData = {xVariableEC
  xSymbTLink((xIdNode)0, (xIdNode)0),
  (xIdNode)&ySrtR_z_sysincl_exp_1U_tagFLATARRAY xIdNames("pData")
  XCOMMON_EXTRAS, &ySrtR_z_sysincl_exp_1T_Ref_sysincl_exp_Octet,
  (tSDLTypeInfo *)&ySDL_z_sysincl_exp_1T_Ref_sysincl_exp_Octet,
  xOffsetOf(z_sysincl_exp_1U_tagFLATARRAY, pData), (xptrint)0, 0 XVAR_EXTRAS};
#endif

/*****
* NEWTYPE tagMACDUPLC  (BODY section)
* <<PACKAGE sysincl_exp>>
* #SDTREF(TEXT,C:\\Kolevatov\\Projects\\SDL\\STACK80211\\proc_mac_exp.h,41)
******/

/* *** tagMACDUPLC *** */
static tSDLFieldInfo fSDL_z_sysincl_exp_1V_tagMACDUPLC[] = {
  {(tSDLTypeInfo *)&ySDL_SDL_Integer  T_SDL_Names("nAccessNo"),
    xOffsetOf(z_sysincl_exp_1V_tagMACDUPLC, nAccessNo), 0},
  {(tSDLTypeInfo *)&ySDL_z_sysincl_exp_1R_tagMACADDR  T_SDL_Names("tAddr2"),
    xOffsetOf(z_sysincl_exp_1V_tagMACDUPLC, tAddr2), 0},
  {(tSDLTypeInfo *)&ySDL_SDL_Integer  T_SDL_Names("nSeqNo"),
    xOffsetOf(z_sysincl_exp_1V_tagMACDUPLC, nSeqNo), 0},
  {(tSDLTypeInfo *)&ySDL_SDL_Integer  T_SDL_Names("nFragNo"),
    xOffsetOf(z_sysincl_exp_1V_tagMACDUPLC, nFragNo), 0}
};
tSDLStructInfo ySDL_z_sysincl_exp_1V_tagMACDUPLC = {type_SDL_Struct, 6,
  (xptrint)sizeof(z_sysincl_exp_1V_tagMACDUPLC) T_SDL_OPFUNCS(0)
  T_SDL_EXTRA_VALUE T_SDL_Names("tagMACDUPLC")
  xRaWF((xIdNode)&yPacR_z_sysincl_exp__sysincl_exp)
  xRaWF(&ySrtR_z_sysincl_exp_1V_tagMACDUPLC),
  fSDL_z_sysincl_exp_1V_tagMACDUPLC, 4};
#ifndef XOPTSORT
XCONST struct xSortIdStruct ySrtR_z_sysincl_exp_1V_tagMACDUPLC = {xSortEC
  xSymbTLink((xIdNode)0, (xIdNode)0),
  (xIdNode)&yPacR_z_sysincl_exp__sysincl_exp xIdNames("tagMACDUPLC")
  XCOMMON_EXTRAS xFreF(0) xAssF(yAss_z_sysincl_exp_1V_tagMACDUPLC)
  xEqF(yEq_z_sysincl_exp_1V_tagMACDUPLC) xTestF(0),
  (xptrint)sizeof(z_sysincl_exp_1V_tagMACDUPLC), xStruct, (xSortIdNode)0,
  (xSortIdNode)0, 0, 0, 0, 0
  xRaWF((tSDLTypeInfo *)&ySDL_z_sysincl_exp_1V_tagMACDUPLC) XSRT_EXTRAS};
#endif
#ifndef XOPTSTRUCT
/*---------------COMPONENTS----------------*/
static XCONST struct xVarIdStruct yVarR_z_sysincl_exp_1VD_nAccessNo =
  {xVariableEC xSymbTLink((xIdNode)0, (xIdNode)0),
  (xIdNode)&ySrtR_z_sysincl_exp_1V_tagMACDUPLC xIdNames("nAccessNo")
  XCOMMON_EXTRAS, &xSrtR_SDL_Integer, (tSDLTypeInfo *)&ySDL_SDL_Integer,
  xOffsetOf(z_sysincl_exp_1V_tagMACDUPLC, nAccessNo), (xptrint)0, 0
  XVAR_EXTRAS};
static XCONST struct xVarIdStruct yVarR_z_sysincl_exp_1VE_tAddr2 = {xVariableEC
  xSymbTLink((xIdNode)0, (xIdNode)0),
  (xIdNode)&ySrtR_z_sysincl_exp_1V_tagMACDUPLC xIdNames("tAddr2")
  XCOMMON_EXTRAS, &ySrtR_z_sysincl_exp_1R_tagMACADDR,
  (tSDLTypeInfo *)&ySDL_z_sysincl_exp_1R_tagMACADDR,
  xOffsetOf(z_sysincl_exp_1V_tagMACDUPLC, tAddr2), (xptrint)0, 0 XVAR_EXTRAS};
static XCONST struct xVarIdStruct yVarR_z_sysincl_exp_1VF_nSeqNo = {xVariableEC
  xSymbTLink((xIdNode)0, (xIdNode)0),
  (xIdNode)&ySrtR_z_sysincl_exp_1V_tagMACDUPLC xIdNames("nSeqNo")
  XCOMMON_EXTRAS, &xSrtR_SDL_Integer, (tSDLTypeInfo *)&ySDL_SDL_Integer,
  xOffsetOf(z_sysincl_exp_1V_tagMACDUPLC, nSeqNo), (xptrint)0, 0 XVAR_EXTRAS};
static XCONST struct xVarIdStruct yVarR_z_sysincl_exp_1VG_nFragNo =
  {xVariableEC xSymbTLink((xIdNode)0, (xIdNode)0),
  (xIdNode)&ySrtR_z_sysincl_exp_1V_tagMACDUPLC xIdNames("nFragNo")
  XCOMMON_EXTRAS, &xSrtR_SDL_Integer, (tSDLTypeInfo *)&ySDL_SDL_Integer,
  xOffsetOf(z_sysincl_exp_1V_tagMACDUPLC, nFragNo), (xptrint)0, 0 XVAR_EXTRAS};
#endif

/*****
* NEWTYPE tagMAC_MIBCNTRS  (BODY section)
* <<PACKAGE sysincl_exp>>
* #SDTREF(TEXT,C:\\Kolevatov\\Projects\\SDL\\STACK80211\\proc_mac_exp.h,50)
******/

/* *** tagMAC_MIBCNTRS *** */
static tSDLFieldInfo fSDL_z_sysincl_exp_1W_tagMAC_MIBCNTRS[] = {
  {(tSDLTypeInfo *)&ySDL_SDL_Integer  T_SDL_Names("TransmittedFragmentCount"),
    xOffsetOf(z_sysincl_exp_1W_tagMAC_MIBCNTRS, TransmittedFragmentCount), 0},
  {(tSDLTypeInfo *)&ySDL_SDL_Integer
    T_SDL_Names("MulticastTransmittedFrameCount"),
    xOffsetOf(z_sysincl_exp_1W_tagMAC_MIBCNTRS, MulticastTransmittedFrameCount),
    0},
  {(tSDLTypeInfo *)&ySDL_SDL_Integer  T_SDL_Names("FailedCount"),
    xOffsetOf(z_sysincl_exp_1W_tagMAC_MIBCNTRS, FailedCount), 0},
  {(tSDLTypeInfo *)&ySDL_SDL_Integer  T_SDL_Names("RetryCount"),
    xOffsetOf(z_sysincl_exp_1W_tagMAC_MIBCNTRS, RetryCount), 0},
  {(tSDLTypeInfo *)&ySDL_SDL_Integer  T_SDL_Names("MultipleRetryCount"),
    xOffsetOf(z_sysincl_exp_1W_tagMAC_MIBCNTRS, MultipleRetryCount), 0},
  {(tSDLTypeInfo *)&ySDL_SDL_Integer  T_SDL_Names("RTSSuccessCount"),
    xOffsetOf(z_sysincl_exp_1W_tagMAC_MIBCNTRS, RTSSuccessCount), 0},
  {(tSDLTypeInfo *)&ySDL_SDL_Integer  T_SDL_Names("RTSFailureCount"),
    xOffsetOf(z_sysincl_exp_1W_tagMAC_MIBCNTRS, RTSFailureCount), 0},
  {(tSDLTypeInfo *)&ySDL_SDL_Integer  T_SDL_Names("ACKFailureCount"),
    xOffsetOf(z_sysincl_exp_1W_tagMAC_MIBCNTRS, ACKFailureCount), 0},
  {(tSDLTypeInfo *)&ySDL_SDL_Integer  T_SDL_Names("ReceivedFragmentCount"),
    xOffsetOf(z_sysincl_exp_1W_tagMAC_MIBCNTRS, ReceivedFragmentCount), 0},
  {(tSDLTypeInfo *)&ySDL_SDL_Integer
    T_SDL_Names("MulticastReceivedFrameCount"),
    xOffsetOf(z_sysincl_exp_1W_tagMAC_MIBCNTRS, MulticastReceivedFrameCount),
    0},
  {(tSDLTypeInfo *)&ySDL_SDL_Integer  T_SDL_Names("FCSErrorCount"),
    xOffsetOf(z_sysincl_exp_1W_tagMAC_MIBCNTRS, FCSErrorCount), 0},
  {(tSDLTypeInfo *)&ySDL_SDL_Integer  T_SDL_Names("FrameDuplicateCount"),
    xOffsetOf(z_sysincl_exp_1W_tagMAC_MIBCNTRS, FrameDuplicateCount), 0}
};
tSDLStructInfo ySDL_z_sysincl_exp_1W_tagMAC_MIBCNTRS = {type_SDL_Struct, 2,
  (xptrint)sizeof(z_sysincl_exp_1W_tagMAC_MIBCNTRS) T_SDL_OPFUNCS(0)
  T_SDL_EXTRA_VALUE T_SDL_Names("tagMAC_MIBCNTRS")
  xRaWF((xIdNode)&yPacR_z_sysincl_exp__sysincl_exp)
  xRaWF(&ySrtR_z_sysincl_exp_1W_tagMAC_MIBCNTRS),
  fSDL_z_sysincl_exp_1W_tagMAC_MIBCNTRS, 12};
#ifndef XOPTSORT
XCONST struct xSortIdStruct ySrtR_z_sysincl_exp_1W_tagMAC_MIBCNTRS = {xSortEC
  xSymbTLink((xIdNode)0, (xIdNode)0),
  (xIdNode)&yPacR_z_sysincl_exp__sysincl_exp xIdNames("tagMAC_MIBCNTRS")
  XCOMMON_EXTRAS xFreF(0) xAssF(0) xEqF(yEq_z_sysincl_exp_1W_tagMAC_MIBCNTRS)
  xTestF(0), (xptrint)sizeof(z_sysincl_exp_1W_tagMAC_MIBCNTRS), xStruct,
  (xSortIdNode)0, (xSortIdNode)0, 0, 0, 0, 0
  xRaWF((tSDLTypeInfo *)&ySDL_z_sysincl_exp_1W_tagMAC_MIBCNTRS) XSRT_EXTRAS};
#endif
#ifndef XOPTSTRUCT
/*---------------COMPONENTS----------------*/
static XCONST struct xVarIdStruct yVarR_z_sysincl_exp_1W0T_TransmittedFragmentCount =
  {xVariableEC xSymbTLink((xIdNode)0, (xIdNode)0),
  (xIdNode)&ySrtR_z_sysincl_exp_1W_tagMAC_MIBCNTRS
  xIdNames("TransmittedFragmentCount") XCOMMON_EXTRAS, &xSrtR_SDL_Integer,
  (tSDLTypeInfo *)&ySDL_SDL_Integer,
  xOffsetOf(z_sysincl_exp_1W_tagMAC_MIBCNTRS, TransmittedFragmentCount),
  (xptrint)0, 0 XVAR_EXTRAS};
static XCONST struct xVarIdStruct yVarR_z_sysincl_exp_1W0U_MulticastTransmittedFrameCount =
  {xVariableEC xSymbTLink((xIdNode)0, (xIdNode)0),
  (xIdNode)&ySrtR_z_sysincl_exp_1W_tagMAC_MIBCNTRS
  xIdNames("MulticastTransmittedFrameCount") XCOMMON_EXTRAS,
  &xSrtR_SDL_Integer, (tSDLTypeInfo *)&ySDL_SDL_Integer,
  xOffsetOf(z_sysincl_exp_1W_tagMAC_MIBCNTRS, MulticastTransmittedFrameCount),
  (xptrint)0, 0 XVAR_EXTRAS};
static XCONST struct xVarIdStruct yVarR_z_sysincl_exp_1W0V_FailedCount =
  {xVariableEC xSymbTLink((xIdNode)0, (xIdNode)0),
  (xIdNode)&ySrtR_z_sysincl_exp_1W_tagMAC_MIBCNTRS xIdNames("FailedCount")
  XCOMMON_EXTRAS, &xSrtR_SDL_Integer, (tSDLTypeInfo *)&ySDL_SDL_Integer,
  xOffsetOf(z_sysincl_exp_1W_tagMAC_MIBCNTRS, FailedCount), (xptrint)0, 0
  XVAR_EXTRAS};
static XCONST struct xVarIdStruct yVarR_z_sysincl_exp_1W0W_RetryCount =
  {xVariableEC xSymbTLink((xIdNode)0, (xIdNode)0),
  (xIdNode)&ySrtR_z_sysincl_exp_1W_tagMAC_MIBCNTRS xIdNames("RetryCount")
  XCOMMON_EXTRAS, &xSrtR_SDL_Integer, (tSDLTypeInfo *)&ySDL_SDL_Integer,
  xOffsetOf(z_sysincl_exp_1W_tagMAC_MIBCNTRS, RetryCount), (xptrint)0, 0
  XVAR_EXTRAS};
static XCONST struct xVarIdStruct yVarR_z_sysincl_exp_1W0X_MultipleRetryCount =
  {xVariableEC xSymbTLink((xIdNode)0, (xIdNode)0),
  (xIdNode)&ySrtR_z_sysincl_exp_1W_tagMAC_MIBCNTRS
  xIdNames("MultipleRetryCount") XCOMMON_EXTRAS, &xSrtR_SDL_Integer,
  (tSDLTypeInfo *)&ySDL_SDL_Integer,
  xOffsetOf(z_sysincl_exp_1W_tagMAC_MIBCNTRS, MultipleRetryCount), (xptrint)0,
  0 XVAR_EXTRAS};
static XCONST struct xVarIdStruct yVarR_z_sysincl_exp_1W0Y_RTSSuccessCount =
  {xVariableEC xSymbTLink((xIdNode)0, (xIdNode)0),
  (xIdNode)&ySrtR_z_sysincl_exp_1W_tagMAC_MIBCNTRS xIdNames("RTSSuccessCount")
  XCOMMON_EXTRAS, &xSrtR_SDL_Integer, (tSDLTypeInfo *)&ySDL_SDL_Integer,
  xOffsetOf(z_sysincl_exp_1W_tagMAC_MIBCNTRS, RTSSuccessCount), (xptrint)0, 0
  XVAR_EXTRAS};
static XCONST struct xVarIdStruct yVarR_z_sysincl_exp_1W0Z_RTSFailureCount =
  {xVariableEC xSymbTLink((xIdNode)0, (xIdNode)0),
  (xIdNode)&ySrtR_z_sysincl_exp_1W_tagMAC_MIBCNTRS xIdNames("RTSFailureCount")
  XCOMMON_EXTRAS, &xSrtR_SDL_Integer, (tSDLTypeInfo *)&ySDL_SDL_Integer,
  xOffsetOf(z_sysincl_exp_1W_tagMAC_MIBCNTRS, RTSFailureCount), (xptrint)0, 0
  XVAR_EXTRAS};
static XCONST struct xVarIdStruct yVarR_z_sysincl_exp_1W10_ACKFailureCount =
  {xVariableEC xSymbTLink((xIdNode)0, (xIdNode)0),
  (xIdNode)&ySrtR_z_sysincl_exp_1W_tagMAC_MIBCNTRS xIdNames("ACKFailureCount")
  XCOMMON_EXTRAS, &xSrtR_SDL_Integer, (tSDLTypeInfo *)&ySDL_SDL_Integer,
  xOffsetOf(z_sysincl_exp_1W_tagMAC_MIBCNTRS, ACKFailureCount), (xptrint)0, 0
  XVAR_EXTRAS};
static XCONST struct xVarIdStruct yVarR_z_sysincl_exp_1W11_ReceivedFragmentCount =
  {xVariableEC xSymbTLink((xIdNode)0, (xIdNode)0),
  (xIdNode)&ySrtR_z_sysincl_exp_1W_tagMAC_MIBCNTRS
  xIdNames("ReceivedFragmentCount") XCOMMON_EXTRAS, &xSrtR_SDL_Integer,
  (tSDLTypeInfo *)&ySDL_SDL_Integer,
  xOffsetOf(z_sysincl_exp_1W_tagMAC_MIBCNTRS, ReceivedFragmentCount),
  (xptrint)0, 0 XVAR_EXTRAS};
static XCONST struct xVarIdStruct yVarR_z_sysincl_exp_1W12_MulticastReceivedFrameCount =
  {xVariableEC xSymbTLink((xIdNode)0, (xIdNode)0),
  (xIdNode)&ySrtR_z_sysincl_exp_1W_tagMAC_MIBCNTRS
  xIdNames("MulticastReceivedFrameCount") XCOMMON_EXTRAS, &xSrtR_SDL_Integer,
  (tSDLTypeInfo *)&ySDL_SDL_Integer,
  xOffsetOf(z_sysincl_exp_1W_tagMAC_MIBCNTRS, MulticastReceivedFrameCount),
  (xptrint)0, 0 XVAR_EXTRAS};
static XCONST struct xVarIdStruct yVarR_z_sysincl_exp_1W13_FCSErrorCount =
  {xVariableEC xSymbTLink((xIdNode)0, (xIdNode)0),
  (xIdNode)&ySrtR_z_sysincl_exp_1W_tagMAC_MIBCNTRS xIdNames("FCSErrorCount")
  XCOMMON_EXTRAS, &xSrtR_SDL_Integer, (tSDLTypeInfo *)&ySDL_SDL_Integer,
  xOffsetOf(z_sysincl_exp_1W_tagMAC_MIBCNTRS, FCSErrorCount), (xptrint)0, 0
  XVAR_EXTRAS};
static XCONST struct xVarIdStruct yVarR_z_sysincl_exp_1W14_FrameDuplicateCount =
  {xVariableEC xSymbTLink((xIdNode)0, (xIdNode)0),
  (xIdNode)&ySrtR_z_sysincl_exp_1W_tagMAC_MIBCNTRS
  xIdNames("FrameDuplicateCount") XCOMMON_EXTRAS, &xSrtR_SDL_Integer,
  (tSDLTypeInfo *)&ySDL_SDL_Integer,
  xOffsetOf(z_sysincl_exp_1W_tagMAC_MIBCNTRS, FrameDuplicateCount), (xptrint)0,
  0 XVAR_EXTRAS};
#endif

/*****
* NEWTYPE CA_sysincl_exp_16_X_tagMACDUPLC  (BODY section)
* <<PACKAGE sysincl_exp>>
* #SDTREF(TEXT,C:\\Kolevatov\\Projects\\SDL\\STACK80211\\proc_mac_exp.h,68)
******/

/* *** CA_sysincl_exp_16_X_tagMACDUPLC *** */
tSDLArrayInfo ySDL_z_sysincl_exp_1X_CA_sysincl_exp_16_X_tagMACDUPLC =
  {type_SDL_Carray, 6,
  (xptrint)sizeof(z_sysincl_exp_1X_CA_sysincl_exp_16_X_tagMACDUPLC)
  T_SDL_OPFUNCS(0) T_SDL_EXTRA_VALUE
  T_SDL_Names("CA_sysincl_exp_16_X_tagMACDUPLC")
  xRaWF((xIdNode)&yPacR_z_sysincl_exp__sysincl_exp)
  xRaWF(&ySrtR_z_sysincl_exp_1X_CA_sysincl_exp_16_X_tagMACDUPLC),
  (tSDLTypeInfo *)&ySDL_z_sysincl_exp_1V_tagMACDUPLC, SDL_INTEGER_LIT(16)
  xRaWF((tSDLTypeInfo *)&ySDL_SDL_Integer) xRaWF(0)};
#ifndef XOPTSORT
XCONST struct xSortIdStruct ySrtR_z_sysincl_exp_1X_CA_sysincl_exp_16_X_tagMACDUPLC =
  {xSortEC xSymbTLink((xIdNode)0, (xIdNode)0),
  (xIdNode)&yPacR_z_sysincl_exp__sysincl_exp
  xIdNames("CA_sysincl_exp_16_X_tagMACDUPLC") XCOMMON_EXTRAS xFreF(0)
  xAssF(yAss_z_sysincl_exp_1X_CA_sysincl_exp_16_X_tagMACDUPLC)
  xEqF(yEq_z_sysincl_exp_1X_CA_sysincl_exp_16_X_tagMACDUPLC) xTestF(0),
  (xptrint)sizeof(z_sysincl_exp_1X_CA_sysincl_exp_16_X_tagMACDUPLC), xCArray,
  &ySrtR_z_sysincl_exp_1V_tagMACDUPLC, xSrtN_SDL_Integer, 0,
  SDL_INTEGER_LIT(16)-1, 0, 0
  xRaWF((tSDLTypeInfo *)&ySDL_z_sysincl_exp_1X_CA_sysincl_exp_16_X_tagMACDUPLC)
  XSRT_EXTRAS};
#endif

/*-------------------TSTI-------------------*/
#ifdef XEINDEX
SDL_Integer yTstI_z_sysincl_exp_1X_CA_sysincl_exp_16_X_tagMACDUPLC
  (SDL_Integer yExpr)
{
  if (yExpr < 0 || yExpr >= SDL_INTEGER_LIT(16)) {
    xErrorIndex((tSDLTypeInfo *)&ySDL_SDL_Integer, &yExpr);
    return 0;
  }
  return yExpr;
}
#endif

/*****
* NEWTYPE tagMAC_ST  (BODY section)
* <<PACKAGE sysincl_exp>>
* #SDTREF(TEXT,C:\\Kolevatov\\Projects\\SDL\\STACK80211\\proc_mac_exp.h,68)
******/

/* *** tagMAC_ST *** */
static tSDLFieldInfo fSDL_z_sysincl_exp_1Y_tagMAC_ST[] = {
  {(tSDLTypeInfo *)&ySDL_SDL_Integer  T_SDL_Names("bVCFree"),
    xOffsetOf(z_sysincl_exp_1Y_tagMAC_ST, bVCFree), 0},
  {(tSDLTypeInfo *)&ySDL_SDL_Integer  T_SDL_Names("nCW"),
    xOffsetOf(z_sysincl_exp_1Y_tagMAC_ST, nCW), 0},
  {(tSDLTypeInfo *)&ySDL_SDL_Integer  T_SDL_Names("nCurSeqNo"),
    xOffsetOf(z_sysincl_exp_1Y_tagMAC_ST, nCurSeqNo), 0},
  {(tSDLTypeInfo *)&ySDL_SDL_Integer  T_SDL_Names("nSSRC"),
    xOffsetOf(z_sysincl_exp_1Y_tagMAC_ST, nSSRC), 0},
  {(tSDLTypeInfo *)&ySDL_SDL_Integer  T_SDL_Names("nSLRC"),
    xOffsetOf(z_sysincl_exp_1Y_tagMAC_ST, nSLRC), 0},
  {(tSDLTypeInfo *)&ySDL_SDL_Integer  T_SDL_Names("nFrags"),
    xOffsetOf(z_sysincl_exp_1Y_tagMAC_ST, nFrags), 0},
  {(tSDLTypeInfo *)&ySDL_SDL_Integer  T_SDL_Names("nCurFrag"),
    xOffsetOf(z_sysincl_exp_1Y_tagMAC_ST, nCurFrag), 0},
  {(tSDLTypeInfo *)&ySDL_z_sysincl_exp_1W_tagMAC_MIBCNTRS  T_SDL_Names("MIBC"),
    xOffsetOf(z_sysincl_exp_1Y_tagMAC_ST, MIBC), 0},
  {(tSDLTypeInfo *)&ySDL_z_sysincl_exp_1S_tagPKT  T_SDL_Names("pktCTRL"),
    xOffsetOf(z_sysincl_exp_1Y_tagMAC_ST, pktCTRL), 0},
  {(tSDLTypeInfo *)&ySDL_z_sysincl_exp_1S_tagPKT  T_SDL_Names("pktRTS"),
    xOffsetOf(z_sysincl_exp_1Y_tagMAC_ST, pktRTS), 0},
  {(tSDLTypeInfo *)&ySDL_z_sysincl_exp_1S_tagPKT  T_SDL_Names("pktTx"),
    xOffsetOf(z_sysincl_exp_1Y_tagMAC_ST, pktTx), 0},
  {(tSDLTypeInfo *)&ySDL_z_sysincl_exp_1S_tagPKT  T_SDL_Names("pktRx"),
    xOffsetOf(z_sysincl_exp_1Y_tagMAC_ST, pktRx), 0},
  {(tSDLTypeInfo *)&ySDL_z_sysincl_exp_1S_tagPKT  T_SDL_Names("pktTxFr"),
    xOffsetOf(z_sysincl_exp_1Y_tagMAC_ST, pktTxFr), 0},
  {(tSDLTypeInfo *)&ySDL_SDL_Integer  T_SDL_Names("m_nCacheAccessNo"),
    xOffsetOf(z_sysincl_exp_1Y_tagMAC_ST, m_nCacheAccessNo), 0},
  {(tSDLTypeInfo *)&ySDL_SDL_Integer  T_SDL_Names("m_nCacheSize"),
    xOffsetOf(z_sysincl_exp_1Y_tagMAC_ST, m_nCacheSize), 0},
  {(tSDLTypeInfo *)&ySDL_z_sysincl_exp_1X_CA_sysincl_exp_16_X_tagMACDUPLC
    T_SDL_Names("m_pDC"), xOffsetOf(z_sysincl_exp_1Y_tagMAC_ST, m_pDC), 0}
};
tSDLStructInfo ySDL_z_sysincl_exp_1Y_tagMAC_ST = {type_SDL_Struct, 6,
  (xptrint)sizeof(z_sysincl_exp_1Y_tagMAC_ST) T_SDL_OPFUNCS(0)
  T_SDL_EXTRA_VALUE T_SDL_Names("tagMAC_ST")
  xRaWF((xIdNode)&yPacR_z_sysincl_exp__sysincl_exp)
  xRaWF(&ySrtR_z_sysincl_exp_1Y_tagMAC_ST), fSDL_z_sysincl_exp_1Y_tagMAC_ST,
  16};
#ifndef XOPTSORT
XCONST struct xSortIdStruct ySrtR_z_sysincl_exp_1Y_tagMAC_ST = {xSortEC
  xSymbTLink((xIdNode)0, (xIdNode)0),
  (xIdNode)&yPacR_z_sysincl_exp__sysincl_exp xIdNames("tagMAC_ST")
  XCOMMON_EXTRAS xFreF(0) xAssF(yAss_z_sysincl_exp_1Y_tagMAC_ST)
  xEqF(yEq_z_sysincl_exp_1Y_tagMAC_ST) xTestF(0),
  (xptrint)sizeof(z_sysincl_exp_1Y_tagMAC_ST), xStruct, (xSortIdNode)0,
  (xSortIdNode)0, 0, 0, 0, 0
  xRaWF((tSDLTypeInfo *)&ySDL_z_sysincl_exp_1Y_tagMAC_ST) XSRT_EXTRAS};
#endif
#ifndef XOPTSTRUCT
/*---------------COMPONENTS----------------*/
static XCONST struct xVarIdStruct yVarR_z_sysincl_exp_1Y11_bVCFree =
  {xVariableEC xSymbTLink((xIdNode)0, (xIdNode)0),
  (xIdNode)&ySrtR_z_sysincl_exp_1Y_tagMAC_ST xIdNames("bVCFree")
  XCOMMON_EXTRAS, &xSrtR_SDL_Integer, (tSDLTypeInfo *)&ySDL_SDL_Integer,
  xOffsetOf(z_sysincl_exp_1Y_tagMAC_ST, bVCFree), (xptrint)0, 0 XVAR_EXTRAS};
static XCONST struct xVarIdStruct yVarR_z_sysincl_exp_1Y12_nCW = {xVariableEC
  xSymbTLink((xIdNode)0, (xIdNode)0),
  (xIdNode)&ySrtR_z_sysincl_exp_1Y_tagMAC_ST xIdNames("nCW") XCOMMON_EXTRAS,
  &xSrtR_SDL_Integer, (tSDLTypeInfo *)&ySDL_SDL_Integer,
  xOffsetOf(z_sysincl_exp_1Y_tagMAC_ST, nCW), (xptrint)0, 0 XVAR_EXTRAS};
static XCONST struct xVarIdStruct yVarR_z_sysincl_exp_1Y13_nCurSeqNo =
  {xVariableEC xSymbTLink((xIdNode)0, (xIdNode)0),
  (xIdNode)&ySrtR_z_sysincl_exp_1Y_tagMAC_ST xIdNames("nCurSeqNo")
  XCOMMON_EXTRAS, &xSrtR_SDL_Integer, (tSDLTypeInfo *)&ySDL_SDL_Integer,
  xOffsetOf(z_sysincl_exp_1Y_tagMAC_ST, nCurSeqNo), (xptrint)0, 0 XVAR_EXTRAS};
static XCONST struct xVarIdStruct yVarR_z_sysincl_exp_1Y14_nSSRC = {xVariableEC
  xSymbTLink((xIdNode)0, (xIdNode)0),
  (xIdNode)&ySrtR_z_sysincl_exp_1Y_tagMAC_ST xIdNames("nSSRC") XCOMMON_EXTRAS,
  &xSrtR_SDL_Integer, (tSDLTypeInfo *)&ySDL_SDL_Integer,
  xOffsetOf(z_sysincl_exp_1Y_tagMAC_ST, nSSRC), (xptrint)0, 0 XVAR_EXTRAS};
static XCONST struct xVarIdStruct yVarR_z_sysincl_exp_1Y15_nSLRC = {xVariableEC
  xSymbTLink((xIdNode)0, (xIdNode)0),
  (xIdNode)&ySrtR_z_sysincl_exp_1Y_tagMAC_ST xIdNames("nSLRC") XCOMMON_EXTRAS,
  &xSrtR_SDL_Integer, (tSDLTypeInfo *)&ySDL_SDL_Integer,
  xOffsetOf(z_sysincl_exp_1Y_tagMAC_ST, nSLRC), (xptrint)0, 0 XVAR_EXTRAS};
static XCONST struct xVarIdStruct yVarR_z_sysincl_exp_1Y16_nFrags =
  {xVariableEC xSymbTLink((xIdNode)0, (xIdNode)0),
  (xIdNode)&ySrtR_z_sysincl_exp_1Y_tagMAC_ST xIdNames("nFrags") XCOMMON_EXTRAS,
  &xSrtR_SDL_Integer, (tSDLTypeInfo *)&ySDL_SDL_Integer,
  xOffsetOf(z_sysincl_exp_1Y_tagMAC_ST, nFrags), (xptrint)0, 0 XVAR_EXTRAS};
static XCONST struct xVarIdStruct yVarR_z_sysincl_exp_1Y17_nCurFrag =
  {xVariableEC xSymbTLink((xIdNode)0, (xIdNode)0),
  (xIdNode)&ySrtR_z_sysincl_exp_1Y_tagMAC_ST xIdNames("nCurFrag")
  XCOMMON_EXTRAS, &xSrtR_SDL_Integer, (tSDLTypeInfo *)&ySDL_SDL_Integer,
  xOffsetOf(z_sysincl_exp_1Y_tagMAC_ST, nCurFrag), (xptrint)0, 0 XVAR_EXTRAS};
static XCONST struct xVarIdStruct yVarR_z_sysincl_exp_1Y18_MIBC = {xVariableEC
  xSymbTLink((xIdNode)0, (xIdNode)0),
  (xIdNode)&ySrtR_z_sysincl_exp_1Y_tagMAC_ST xIdNames("MIBC") XCOMMON_EXTRAS,
  &ySrtR_z_sysincl_exp_1W_tagMAC_MIBCNTRS,
  (tSDLTypeInfo *)&ySDL_z_sysincl_exp_1W_tagMAC_MIBCNTRS,
  xOffsetOf(z_sysincl_exp_1Y_tagMAC_ST, MIBC), (xptrint)0, 0 XVAR_EXTRAS};
static XCONST struct xVarIdStruct yVarR_z_sysincl_exp_1Y19_pktCTRL =
  {xVariableEC xSymbTLink((xIdNode)0, (xIdNode)0),
  (xIdNode)&ySrtR_z_sysincl_exp_1Y_tagMAC_ST xIdNames("pktCTRL")
  XCOMMON_EXTRAS, &ySrtR_z_sysincl_exp_1S_tagPKT,
  (tSDLTypeInfo *)&ySDL_z_sysincl_exp_1S_tagPKT,
  xOffsetOf(z_sysincl_exp_1Y_tagMAC_ST, pktCTRL), (xptrint)0, 0 XVAR_EXTRAS};
static XCONST struct xVarIdStruct yVarR_z_sysincl_exp_1Y1A_pktRTS =
  {xVariableEC xSymbTLink((xIdNode)0, (xIdNode)0),
  (xIdNode)&ySrtR_z_sysincl_exp_1Y_tagMAC_ST xIdNames("pktRTS") XCOMMON_EXTRAS,
  &ySrtR_z_sysincl_exp_1S_tagPKT,
  (tSDLTypeInfo *)&ySDL_z_sysincl_exp_1S_tagPKT,
  xOffsetOf(z_sysincl_exp_1Y_tagMAC_ST, pktRTS), (xptrint)0, 0 XVAR_EXTRAS};
static XCONST struct xVarIdStruct yVarR_z_sysincl_exp_1Y1B_pktTx = {xVariableEC
  xSymbTLink((xIdNode)0, (xIdNode)0),
  (xIdNode)&ySrtR_z_sysincl_exp_1Y_tagMAC_ST xIdNames("pktTx") XCOMMON_EXTRAS,
  &ySrtR_z_sysincl_exp_1S_tagPKT,
  (tSDLTypeInfo *)&ySDL_z_sysincl_exp_1S_tagPKT,
  xOffsetOf(z_sysincl_exp_1Y_tagMAC_ST, pktTx), (xptrint)0, 0 XVAR_EXTRAS};
static XCONST struct xVarIdStruct yVarR_z_sysincl_exp_1Y1C_pktRx = {xVariableEC
  xSymbTLink((xIdNode)0, (xIdNode)0),
  (xIdNode)&ySrtR_z_sysincl_exp_1Y_tagMAC_ST xIdNames("pktRx") XCOMMON_EXTRAS,
  &ySrtR_z_sysincl_exp_1S_tagPKT,
  (tSDLTypeInfo *)&ySDL_z_sysincl_exp_1S_tagPKT,
  xOffsetOf(z_sysincl_exp_1Y_tagMAC_ST, pktRx), (xptrint)0, 0 XVAR_EXTRAS};
static XCONST struct xVarIdStruct yVarR_z_sysincl_exp_1Y1D_pktTxFr =
  {xVariableEC xSymbTLink((xIdNode)0, (xIdNode)0),
  (xIdNode)&ySrtR_z_sysincl_exp_1Y_tagMAC_ST xIdNames("pktTxFr")
  XCOMMON_EXTRAS, &ySrtR_z_sysincl_exp_1S_tagPKT,
  (tSDLTypeInfo *)&ySDL_z_sysincl_exp_1S_tagPKT,
  xOffsetOf(z_sysincl_exp_1Y_tagMAC_ST, pktTxFr), (xptrint)0, 0 XVAR_EXTRAS};
static XCONST struct xVarIdStruct yVarR_z_sysincl_exp_1Y1E_m_nCacheAccessNo =
  {xVariableEC xSymbTLink((xIdNode)0, (xIdNode)0),
  (xIdNode)&ySrtR_z_sysincl_exp_1Y_tagMAC_ST xIdNames("m_nCacheAccessNo")
  XCOMMON_EXTRAS, &xSrtR_SDL_Integer, (tSDLTypeInfo *)&ySDL_SDL_Integer,
  xOffsetOf(z_sysincl_exp_1Y_tagMAC_ST, m_nCacheAccessNo), (xptrint)0, 0
  XVAR_EXTRAS};
static XCONST struct xVarIdStruct yVarR_z_sysincl_exp_1Y1F_m_nCacheSize =
  {xVariableEC xSymbTLink((xIdNode)0, (xIdNode)0),
  (xIdNode)&ySrtR_z_sysincl_exp_1Y_tagMAC_ST xIdNames("m_nCacheSize")
  XCOMMON_EXTRAS, &xSrtR_SDL_Integer, (tSDLTypeInfo *)&ySDL_SDL_Integer,
  xOffsetOf(z_sysincl_exp_1Y_tagMAC_ST, m_nCacheSize), (xptrint)0, 0
  XVAR_EXTRAS};
static XCONST struct xVarIdStruct yVarR_z_sysincl_exp_1Y1G_m_pDC = {xVariableEC
  xSymbTLink((xIdNode)0, (xIdNode)0),
  (xIdNode)&ySrtR_z_sysincl_exp_1Y_tagMAC_ST xIdNames("m_pDC") XCOMMON_EXTRAS,
  &ySrtR_z_sysincl_exp_1X_CA_sysincl_exp_16_X_tagMACDUPLC,
  (tSDLTypeInfo *)&ySDL_z_sysincl_exp_1X_CA_sysincl_exp_16_X_tagMACDUPLC,
  xOffsetOf(z_sysincl_exp_1Y_tagMAC_ST, m_pDC), (xptrint)0, 0 XVAR_EXTRAS};
#endif

/*****
* NEWTYPE CA_sysincl_exp_4096_X_Octet  (BODY section)
* <<PACKAGE sysincl_exp>>
* #SDTREF(TEXT,C:\\Kolevatov\\Projects\\SDL\\STACK80211\\proc_phyctrl_exp.h,32)
******/

/* *** CA_sysincl_exp_4096_X_Octet *** */
tSDLArrayInfo ySDL_z_sysincl_exp_1Z_CA_sysincl_exp_4096_X_Octet =
  {type_SDL_Carray, 6,
  (xptrint)sizeof(z_sysincl_exp_1Z_CA_sysincl_exp_4096_X_Octet)
  T_SDL_OPFUNCS(0) T_SDL_EXTRA_VALUE T_SDL_Names("CA_sysincl_exp_4096_X_Octet")
  xRaWF((xIdNode)&yPacR_z_sysincl_exp__sysincl_exp)
  xRaWF(&ySrtR_z_sysincl_exp_1Z_CA_sysincl_exp_4096_X_Octet),
  (tSDLTypeInfo *)&ySDL_SDL_Octet, SDL_INTEGER_LIT(4096)
  xRaWF((tSDLTypeInfo *)&ySDL_SDL_Integer) xRaWF(0)};
#ifndef XOPTSORT
XCONST struct xSortIdStruct ySrtR_z_sysincl_exp_1Z_CA_sysincl_exp_4096_X_Octet =
  {xSortEC xSymbTLink((xIdNode)0, (xIdNode)0),
  (xIdNode)&yPacR_z_sysincl_exp__sysincl_exp
  xIdNames("CA_sysincl_exp_4096_X_Octet") XCOMMON_EXTRAS xFreF(0)
  xAssF(yAss_z_sysincl_exp_1Z_CA_sysincl_exp_4096_X_Octet)
  xEqF(yEq_z_sysincl_exp_1Z_CA_sysincl_exp_4096_X_Octet) xTestF(0),
  (xptrint)sizeof(z_sysincl_exp_1Z_CA_sysincl_exp_4096_X_Octet), xCArray,
  &xSrtR_SDL_Octet, xSrtN_SDL_Integer, 0, SDL_INTEGER_LIT(4096)-1, 0, 0
  xRaWF((tSDLTypeInfo *)&ySDL_z_sysincl_exp_1Z_CA_sysincl_exp_4096_X_Octet)
  XSRT_EXTRAS};
#endif

/*-------------------TSTI-------------------*/
#ifdef XEINDEX
SDL_Integer yTstI_z_sysincl_exp_1Z_CA_sysincl_exp_4096_X_Octet
  (SDL_Integer yExpr)
{
  if (yExpr < 0 || yExpr >= SDL_INTEGER_LIT(4096)) {
    xErrorIndex((tSDLTypeInfo *)&ySDL_SDL_Integer, &yExpr);
    return 0;
  }
  return yExpr;
}
#endif

/*****
* NEWTYPE tagFLDPSDU  (BODY section)
* <<PACKAGE sysincl_exp>>
* #SDTREF(TEXT,C:\\Kolevatov\\Projects\\SDL\\STACK80211\\proc_phyctrl_exp.h,32)
******/

/* *** tagFLDPSDU *** */
static tSDLFieldInfo fSDL_z_sysincl_exp_20_tagFLDPSDU[] = {
  {(tSDLTypeInfo *)&ySDL_SDL_Integer  T_SDL_Names("m_nSize"),
    xOffsetOf(z_sysincl_exp_20_tagFLDPSDU, m_nSize), 0},
  {(tSDLTypeInfo *)&ySDL_z_sysincl_exp_1Z_CA_sysincl_exp_4096_X_Octet
    T_SDL_Names("m_pData"), xOffsetOf(z_sysincl_exp_20_tagFLDPSDU, m_pData), 0}
};
tSDLStructInfo ySDL_z_sysincl_exp_20_tagFLDPSDU = {type_SDL_Struct, 6,
  (xptrint)sizeof(z_sysincl_exp_20_tagFLDPSDU) T_SDL_OPFUNCS(0)
  T_SDL_EXTRA_VALUE T_SDL_Names("tagFLDPSDU")
  xRaWF((xIdNode)&yPacR_z_sysincl_exp__sysincl_exp)
  xRaWF(&ySrtR_z_sysincl_exp_20_tagFLDPSDU), fSDL_z_sysincl_exp_20_tagFLDPSDU,
  2};
#ifndef XOPTSORT
XCONST struct xSortIdStruct ySrtR_z_sysincl_exp_20_tagFLDPSDU = {xSortEC
  xSymbTLink((xIdNode)0, (xIdNode)0),
  (xIdNode)&yPacR_z_sysincl_exp__sysincl_exp xIdNames("tagFLDPSDU")
  XCOMMON_EXTRAS xFreF(0) xAssF(yAss_z_sysincl_exp_20_tagFLDPSDU)
  xEqF(yEq_z_sysincl_exp_20_tagFLDPSDU) xTestF(0),
  (xptrint)sizeof(z_sysincl_exp_20_tagFLDPSDU), xStruct, (xSortIdNode)0,
  (xSortIdNode)0, 0, 0, 0, 0
  xRaWF((tSDLTypeInfo *)&ySDL_z_sysincl_exp_20_tagFLDPSDU) XSRT_EXTRAS};
#endif
#ifndef XOPTSTRUCT
/*---------------COMPONENTS----------------*/
static XCONST struct xVarIdStruct yVarR_z_sysincl_exp_209_m_nSize =
  {xVariableEC xSymbTLink((xIdNode)0, (xIdNode)0),
  (xIdNode)&ySrtR_z_sysincl_exp_20_tagFLDPSDU xIdNames("m_nSize")
  XCOMMON_EXTRAS, &xSrtR_SDL_Integer, (tSDLTypeInfo *)&ySDL_SDL_Integer,
  xOffsetOf(z_sysincl_exp_20_tagFLDPSDU, m_nSize), (xptrint)0, 0 XVAR_EXTRAS};
static XCONST struct xVarIdStruct yVarR_z_sysincl_exp_20A_m_pData =
  {xVariableEC xSymbTLink((xIdNode)0, (xIdNode)0),
  (xIdNode)&ySrtR_z_sysincl_exp_20_tagFLDPSDU xIdNames("m_pData")
  XCOMMON_EXTRAS, &ySrtR_z_sysincl_exp_1Z_CA_sysincl_exp_4096_X_Octet,
  (tSDLTypeInfo *)&ySDL_z_sysincl_exp_1Z_CA_sysincl_exp_4096_X_Octet,
  xOffsetOf(z_sysincl_exp_20_tagFLDPSDU, m_pData), (xptrint)0, 0 XVAR_EXTRAS};
#endif

/*****
* NEWTYPE tagSIGNAL  (BODY section)
* <<PACKAGE sysincl_exp>>
* #SDTREF(TEXT,C:\\Kolevatov\\Projects\\SDL\\STACK80211\\proc_phyctrl_exp.h,40)
******/

/* *** tagSIGNAL *** */
static int GetBitField_z_sysincl_exp_21F_nRate(void *Addr)
{
  return (int)((z_sysincl_exp_21_tagSIGNAL *)Addr)->nRate;
}
static void PutBitField_z_sysincl_exp_21F_nRate(void *Addr, int Value)
{
  ((z_sysincl_exp_21_tagSIGNAL *)Addr)->nRate = Value;
}
static tSDLFieldBitFInfo z_sysincl_exp_21F_nRate_ExtraInfo =
  {GetBitField_z_sysincl_exp_21F_nRate, PutBitField_z_sysincl_exp_21F_nRate};
static int GetBitField_z_sysincl_exp_21G_nR(void *Addr)
{
  return (int)((z_sysincl_exp_21_tagSIGNAL *)Addr)->nR;
}
static void PutBitField_z_sysincl_exp_21G_nR(void *Addr, int Value)
{
  ((z_sysincl_exp_21_tagSIGNAL *)Addr)->nR = Value;
}
static tSDLFieldBitFInfo z_sysincl_exp_21G_nR_ExtraInfo =
  {GetBitField_z_sysincl_exp_21G_nR, PutBitField_z_sysincl_exp_21G_nR};
static int GetBitField_z_sysincl_exp_21H_nLen(void *Addr)
{
  return (int)((z_sysincl_exp_21_tagSIGNAL *)Addr)->nLen;
}
static void PutBitField_z_sysincl_exp_21H_nLen(void *Addr, int Value)
{
  ((z_sysincl_exp_21_tagSIGNAL *)Addr)->nLen = Value;
}
static tSDLFieldBitFInfo z_sysincl_exp_21H_nLen_ExtraInfo =
  {GetBitField_z_sysincl_exp_21H_nLen, PutBitField_z_sysincl_exp_21H_nLen};
static int GetBitField_z_sysincl_exp_21I_nParity(void *Addr)
{
  return (int)((z_sysincl_exp_21_tagSIGNAL *)Addr)->nParity;
}
static void PutBitField_z_sysincl_exp_21I_nParity(void *Addr, int Value)
{
  ((z_sysincl_exp_21_tagSIGNAL *)Addr)->nParity = Value;
}
static tSDLFieldBitFInfo z_sysincl_exp_21I_nParity_ExtraInfo =
  {GetBitField_z_sysincl_exp_21I_nParity,
  PutBitField_z_sysincl_exp_21I_nParity};
static int GetBitField_z_sysincl_exp_21J_nTail(void *Addr)
{
  return (int)((z_sysincl_exp_21_tagSIGNAL *)Addr)->nTail;
}
static void PutBitField_z_sysincl_exp_21J_nTail(void *Addr, int Value)
{
  ((z_sysincl_exp_21_tagSIGNAL *)Addr)->nTail = Value;
}
static tSDLFieldBitFInfo z_sysincl_exp_21J_nTail_ExtraInfo =
  {GetBitField_z_sysincl_exp_21J_nTail, PutBitField_z_sysincl_exp_21J_nTail};
static tSDLFieldInfo fSDL_z_sysincl_exp_21_tagSIGNAL[] = {
  {(tSDLTypeInfo *)&ySDL_z_ctypes_9_UnsignedInt  T_SDL_Names("nRate"), ~0,
    (tSDLFieldOptInfo *)&z_sysincl_exp_21F_nRate_ExtraInfo},
  {(tSDLTypeInfo *)&ySDL_z_ctypes_9_UnsignedInt  T_SDL_Names("nR"), ~0,
    (tSDLFieldOptInfo *)&z_sysincl_exp_21G_nR_ExtraInfo},
  {(tSDLTypeInfo *)&ySDL_z_ctypes_9_UnsignedInt  T_SDL_Names("nLen"), ~0,
    (tSDLFieldOptInfo *)&z_sysincl_exp_21H_nLen_ExtraInfo},
  {(tSDLTypeInfo *)&ySDL_z_ctypes_9_UnsignedInt  T_SDL_Names("nParity"), ~0,
    (tSDLFieldOptInfo *)&z_sysincl_exp_21I_nParity_ExtraInfo},
  {(tSDLTypeInfo *)&ySDL_z_ctypes_9_UnsignedInt  T_SDL_Names("nTail"), ~0,
    (tSDLFieldOptInfo *)&z_sysincl_exp_21J_nTail_ExtraInfo}
};
tSDLStructInfo ySDL_z_sysincl_exp_21_tagSIGNAL = {type_SDL_Struct, 2,
  (xptrint)sizeof(z_sysincl_exp_21_tagSIGNAL) T_SDL_OPFUNCS(0)
  T_SDL_EXTRA_VALUE T_SDL_Names("tagSIGNAL")
  xRaWF((xIdNode)&yPacR_z_sysincl_exp__sysincl_exp)
  xRaWF(&ySrtR_z_sysincl_exp_21_tagSIGNAL), fSDL_z_sysincl_exp_21_tagSIGNAL, 5};
#ifndef XOPTSORT
XCONST struct xSortIdStruct ySrtR_z_sysincl_exp_21_tagSIGNAL = {xSortEC
  xSymbTLink((xIdNode)0, (xIdNode)0),
  (xIdNode)&yPacR_z_sysincl_exp__sysincl_exp xIdNames("tagSIGNAL")
  XCOMMON_EXTRAS xFreF(0) xAssF(0) xEqF(yEq_z_sysincl_exp_21_tagSIGNAL)
  xTestF(0), (xptrint)sizeof(z_sysincl_exp_21_tagSIGNAL), xStruct,
  (xSortIdNode)0, (xSortIdNode)0, 0, 0, 0, 0
  xRaWF((tSDLTypeInfo *)&ySDL_z_sysincl_exp_21_tagSIGNAL) XSRT_EXTRAS};
#endif
#ifndef XOPTSTRUCT
/*---------------COMPONENTS----------------*/
static XCONST struct xVarIdStruct yVarR_z_sysincl_exp_21F_nRate = {xVariableEC
  xSymbTLink((xIdNode)0, (xIdNode)0),
  (xIdNode)&ySrtR_z_sysincl_exp_21_tagSIGNAL xIdNames("nRate") XCOMMON_EXTRAS,
  &ySrtR_z_ctypes_9_UnsignedInt, (tSDLTypeInfo *)&ySDL_z_ctypes_9_UnsignedInt,
  65535, (xptrint)0, 0 XVAR_EXTRAS};
static XCONST struct xVarIdStruct yVarR_z_sysincl_exp_21G_nR = {xVariableEC
  xSymbTLink((xIdNode)0, (xIdNode)0),
  (xIdNode)&ySrtR_z_sysincl_exp_21_tagSIGNAL xIdNames("nR") XCOMMON_EXTRAS,
  &ySrtR_z_ctypes_9_UnsignedInt, (tSDLTypeInfo *)&ySDL_z_ctypes_9_UnsignedInt,
  65535, (xptrint)0, 0 XVAR_EXTRAS};
static XCONST struct xVarIdStruct yVarR_z_sysincl_exp_21H_nLen = {xVariableEC
  xSymbTLink((xIdNode)0, (xIdNode)0),
  (xIdNode)&ySrtR_z_sysincl_exp_21_tagSIGNAL xIdNames("nLen") XCOMMON_EXTRAS,
  &ySrtR_z_ctypes_9_UnsignedInt, (tSDLTypeInfo *)&ySDL_z_ctypes_9_UnsignedInt,
  65535, (xptrint)0, 0 XVAR_EXTRAS};
static XCONST struct xVarIdStruct yVarR_z_sysincl_exp_21I_nParity =
  {xVariableEC xSymbTLink((xIdNode)0, (xIdNode)0),
  (xIdNode)&ySrtR_z_sysincl_exp_21_tagSIGNAL xIdNames("nParity")
  XCOMMON_EXTRAS, &ySrtR_z_ctypes_9_UnsignedInt,
  (tSDLTypeInfo *)&ySDL_z_ctypes_9_UnsignedInt, 65535, (xptrint)0, 0
  XVAR_EXTRAS};
static XCONST struct xVarIdStruct yVarR_z_sysincl_exp_21J_nTail = {xVariableEC
  xSymbTLink((xIdNode)0, (xIdNode)0),
  (xIdNode)&ySrtR_z_sysincl_exp_21_tagSIGNAL xIdNames("nTail") XCOMMON_EXTRAS,
  &ySrtR_z_ctypes_9_UnsignedInt, (tSDLTypeInfo *)&ySDL_z_ctypes_9_UnsignedInt,
  65535, (xptrint)0, 0 XVAR_EXTRAS};
#endif

/*****
* NEWTYPE CA_sysincl_exp_216_X_Octet  (BODY section)
* <<PACKAGE sysincl_exp>>
* #SDTREF(TEXT,C:\\Kolevatov\\Projects\\SDL\\STACK80211\\proc_phyctrl_exp.h,51)
******/

/* *** CA_sysincl_exp_216_X_Octet *** */
tSDLArrayInfo ySDL_z_sysincl_exp_22_CA_sysincl_exp_216_X_Octet =
  {type_SDL_Carray, 6,
  (xptrint)sizeof(z_sysincl_exp_22_CA_sysincl_exp_216_X_Octet) T_SDL_OPFUNCS(0)
  T_SDL_EXTRA_VALUE T_SDL_Names("CA_sysincl_exp_216_X_Octet")
  xRaWF((xIdNode)&yPacR_z_sysincl_exp__sysincl_exp)
  xRaWF(&ySrtR_z_sysincl_exp_22_CA_sysincl_exp_216_X_Octet),
  (tSDLTypeInfo *)&ySDL_SDL_Octet, SDL_INTEGER_LIT(216)
  xRaWF((tSDLTypeInfo *)&ySDL_SDL_Integer) xRaWF(0)};
#ifndef XOPTSORT
XCONST struct xSortIdStruct ySrtR_z_sysincl_exp_22_CA_sysincl_exp_216_X_Octet =
  {xSortEC xSymbTLink((xIdNode)0, (xIdNode)0),
  (xIdNode)&yPacR_z_sysincl_exp__sysincl_exp
  xIdNames("CA_sysincl_exp_216_X_Octet") XCOMMON_EXTRAS xFreF(0)
  xAssF(yAss_z_sysincl_exp_22_CA_sysincl_exp_216_X_Octet)
  xEqF(yEq_z_sysincl_exp_22_CA_sysincl_exp_216_X_Octet) xTestF(0),
  (xptrint)sizeof(z_sysincl_exp_22_CA_sysincl_exp_216_X_Octet), xCArray,
  &xSrtR_SDL_Octet, xSrtN_SDL_Integer, 0, SDL_INTEGER_LIT(216)-1, 0, 0
  xRaWF((tSDLTypeInfo *)&ySDL_z_sysincl_exp_22_CA_sysincl_exp_216_X_Octet)
  XSRT_EXTRAS};
#endif

/*-------------------TSTI-------------------*/
#ifdef XEINDEX
SDL_Integer yTstI_z_sysincl_exp_22_CA_sysincl_exp_216_X_Octet(SDL_Integer yExpr)
{
  if (yExpr < 0 || yExpr >= SDL_INTEGER_LIT(216)) {
    xErrorIndex((tSDLTypeInfo *)&ySDL_SDL_Integer, &yExpr);
    return 0;
  }
  return yExpr;
}
#endif

/*****
* NEWTYPE tagBITSEQ  (BODY section)
* <<PACKAGE sysincl_exp>>
* #SDTREF(TEXT,C:\\Kolevatov\\Projects\\SDL\\STACK80211\\proc_phyctrl_exp.h,51)
******/

/* *** tagBITSEQ *** */
static tSDLFieldInfo fSDL_z_sysincl_exp_23_tagBITSEQ[] = {
  {(tSDLTypeInfo *)&ySDL_SDL_Integer  T_SDL_Names("m_nSize"),
    xOffsetOf(z_sysincl_exp_23_tagBITSEQ, m_nSize), 0},
  {(tSDLTypeInfo *)&ySDL_z_sysincl_exp_22_CA_sysincl_exp_216_X_Octet
    T_SDL_Names("m_pData"), xOffsetOf(z_sysincl_exp_23_tagBITSEQ, m_pData), 0}
};
tSDLStructInfo ySDL_z_sysincl_exp_23_tagBITSEQ = {type_SDL_Struct, 6,
  (xptrint)sizeof(z_sysincl_exp_23_tagBITSEQ) T_SDL_OPFUNCS(0)
  T_SDL_EXTRA_VALUE T_SDL_Names("tagBITSEQ")
  xRaWF((xIdNode)&yPacR_z_sysincl_exp__sysincl_exp)
  xRaWF(&ySrtR_z_sysincl_exp_23_tagBITSEQ), fSDL_z_sysincl_exp_23_tagBITSEQ, 2};
#ifndef XOPTSORT
XCONST struct xSortIdStruct ySrtR_z_sysincl_exp_23_tagBITSEQ = {xSortEC
  xSymbTLink((xIdNode)0, (xIdNode)0),
  (xIdNode)&yPacR_z_sysincl_exp__sysincl_exp xIdNames("tagBITSEQ")
  XCOMMON_EXTRAS xFreF(0) xAssF(yAss_z_sysincl_exp_23_tagBITSEQ)
  xEqF(yEq_z_sysincl_exp_23_tagBITSEQ) xTestF(0),
  (xptrint)sizeof(z_sysincl_exp_23_tagBITSEQ), xStruct, (xSortIdNode)0,
  (xSortIdNode)0, 0, 0, 0, 0
  xRaWF((tSDLTypeInfo *)&ySDL_z_sysincl_exp_23_tagBITSEQ) XSRT_EXTRAS};
#endif
#ifndef XOPTSTRUCT
/*---------------COMPONENTS----------------*/
static XCONST struct xVarIdStruct yVarR_z_sysincl_exp_239_m_nSize =
  {xVariableEC xSymbTLink((xIdNode)0, (xIdNode)0),
  (xIdNode)&ySrtR_z_sysincl_exp_23_tagBITSEQ xIdNames("m_nSize")
  XCOMMON_EXTRAS, &xSrtR_SDL_Integer, (tSDLTypeInfo *)&ySDL_SDL_Integer,
  xOffsetOf(z_sysincl_exp_23_tagBITSEQ, m_nSize), (xptrint)0, 0 XVAR_EXTRAS};
static XCONST struct xVarIdStruct yVarR_z_sysincl_exp_23A_m_pData =
  {xVariableEC xSymbTLink((xIdNode)0, (xIdNode)0),
  (xIdNode)&ySrtR_z_sysincl_exp_23_tagBITSEQ xIdNames("m_pData")
  XCOMMON_EXTRAS, &ySrtR_z_sysincl_exp_22_CA_sysincl_exp_216_X_Octet,
  (tSDLTypeInfo *)&ySDL_z_sysincl_exp_22_CA_sysincl_exp_216_X_Octet,
  xOffsetOf(z_sysincl_exp_23_tagBITSEQ, m_pData), (xptrint)0, 0 XVAR_EXTRAS};
#endif

/*****
* SYNTYPE PSDU  (BODY section)
* <<PACKAGE sysincl_exp>>
* #SDTREF(TEXT,C:\\Kolevatov\\Projects\\SDL\\STACK80211\\proc_phyctrl_exp.h,57)
******/

/* *** PSDU *** */
tSDLGenInfo ySDL_z_sysincl_exp_2J_PSDU = {type_SDL_Syntype, 6,
  (xptrint)sizeof(z_sysincl_exp_2J_PSDU) T_SDL_OPFUNCS(0) T_SDL_EXTRA_VALUE
  T_SDL_Names("PSDU") xRaWF((xIdNode)&yPacR_z_sysincl_exp__sysincl_exp)
  xRaWF(&ySrtR_z_sysincl_exp_2J_PSDU),
  (tSDLTypeInfo *)&ySDL_z_sysincl_exp_20_tagFLDPSDU};
#ifndef XOPTSORT
XCONST struct xSortIdStruct ySrtR_z_sysincl_exp_2J_PSDU = {xSortEC
  xSymbTLink((xIdNode)0, (xIdNode)0),
  (xIdNode)&yPacR_z_sysincl_exp__sysincl_exp xIdNames("PSDU") XCOMMON_EXTRAS
  xFreF(0) xAssF(yAss_z_sysincl_exp_20_tagFLDPSDU)
  xEqF(yEq_z_sysincl_exp_20_tagFLDPSDU) xTestF(0),
  (xptrint)sizeof(z_sysincl_exp_2J_PSDU), xSyntype,
  &ySrtR_z_sysincl_exp_20_tagFLDPSDU, &ySrtR_z_sysincl_exp_20_tagFLDPSDU, 0, 0,
  0, 0 xRaWF((tSDLTypeInfo *)&ySDL_z_sysincl_exp_2J_PSDU) XSRT_EXTRAS};
#endif

/*****
* SYNTYPE HDR  (BODY section)
* <<PACKAGE sysincl_exp>>
* #SDTREF(TEXT,C:\\Kolevatov\\Projects\\SDL\\STACK80211\\proc_phyctrl_exp.h,58)
******/

/* *** HDR *** */
tSDLGenInfo ySDL_z_sysincl_exp_2K_HDR = {type_SDL_Syntype, 2,
  (xptrint)sizeof(z_sysincl_exp_2K_HDR) T_SDL_OPFUNCS(0) T_SDL_EXTRA_VALUE
  T_SDL_Names("HDR") xRaWF((xIdNode)&yPacR_z_sysincl_exp__sysincl_exp)
  xRaWF(&ySrtR_z_sysincl_exp_2K_HDR),
  (tSDLTypeInfo *)&ySDL_z_sysincl_exp_21_tagSIGNAL};
#ifndef XOPTSORT
XCONST struct xSortIdStruct ySrtR_z_sysincl_exp_2K_HDR = {xSortEC
  xSymbTLink((xIdNode)0, (xIdNode)0),
  (xIdNode)&yPacR_z_sysincl_exp__sysincl_exp xIdNames("HDR") XCOMMON_EXTRAS
  xFreF(0) xAssF(0) xEqF(yEq_z_sysincl_exp_21_tagSIGNAL) xTestF(0),
  (xptrint)sizeof(z_sysincl_exp_2K_HDR), xSyntype,
  &ySrtR_z_sysincl_exp_21_tagSIGNAL, &ySrtR_z_sysincl_exp_21_tagSIGNAL, 0, 0,
  0, 0 xRaWF((tSDLTypeInfo *)&ySDL_z_sysincl_exp_2K_HDR) XSRT_EXTRAS};
#endif

/*****
* SYNTYPE BITSEQ  (BODY section)
* <<PACKAGE sysincl_exp>>
* #SDTREF(TEXT,C:\\Kolevatov\\Projects\\SDL\\STACK80211\\proc_phyctrl_exp.h,59)
******/

/* *** BITSEQ *** */
tSDLGenInfo ySDL_z_sysincl_exp_2L_BITSEQ = {type_SDL_Syntype, 6,
  (xptrint)sizeof(z_sysincl_exp_2L_BITSEQ) T_SDL_OPFUNCS(0) T_SDL_EXTRA_VALUE
  T_SDL_Names("BITSEQ") xRaWF((xIdNode)&yPacR_z_sysincl_exp__sysincl_exp)
  xRaWF(&ySrtR_z_sysincl_exp_2L_BITSEQ),
  (tSDLTypeInfo *)&ySDL_z_sysincl_exp_23_tagBITSEQ};
#ifndef XOPTSORT
XCONST struct xSortIdStruct ySrtR_z_sysincl_exp_2L_BITSEQ = {xSortEC
  xSymbTLink((xIdNode)0, (xIdNode)0),
  (xIdNode)&yPacR_z_sysincl_exp__sysincl_exp xIdNames("BITSEQ") XCOMMON_EXTRAS
  xFreF(0) xAssF(yAss_z_sysincl_exp_23_tagBITSEQ)
  xEqF(yEq_z_sysincl_exp_23_tagBITSEQ) xTestF(0),
  (xptrint)sizeof(z_sysincl_exp_2L_BITSEQ), xSyntype,
  &ySrtR_z_sysincl_exp_23_tagBITSEQ, &ySrtR_z_sysincl_exp_23_tagBITSEQ, 0, 0,
  0, 0 xRaWF((tSDLTypeInfo *)&ySDL_z_sysincl_exp_2L_BITSEQ) XSRT_EXTRAS};
#endif

/*****
* NEWTYPE tagCMPLX  (BODY section)
* <<PACKAGE sysincl_exp>>
* #SDTREF(TEXT,C:\\Kolevatov\\Projects\\SDL\\STACK80211\\proc_phy_exp.h,17)
******/

/* *** tagCMPLX *** */
static tSDLFieldInfo fSDL_z_sysincl_exp_24_tagCMPLX[] = {
  {(tSDLTypeInfo *)&ySDL_SDL_Real  T_SDL_Names("R"),
    xOffsetOf(z_sysincl_exp_24_tagCMPLX, R), 0},
  {(tSDLTypeInfo *)&ySDL_SDL_Real  T_SDL_Names("I"),
    xOffsetOf(z_sysincl_exp_24_tagCMPLX, I), 0}
};
tSDLStructInfo ySDL_z_sysincl_exp_24_tagCMPLX = {type_SDL_Struct, 2,
  (xptrint)sizeof(z_sysincl_exp_24_tagCMPLX) T_SDL_OPFUNCS(0) T_SDL_EXTRA_VALUE
  T_SDL_Names("tagCMPLX") xRaWF((xIdNode)&yPacR_z_sysincl_exp__sysincl_exp)
  xRaWF(&ySrtR_z_sysincl_exp_24_tagCMPLX), fSDL_z_sysincl_exp_24_tagCMPLX, 2};
#ifndef XOPTSORT
XCONST struct xSortIdStruct ySrtR_z_sysincl_exp_24_tagCMPLX = {xSortEC
  xSymbTLink((xIdNode)0, (xIdNode)0),
  (xIdNode)&yPacR_z_sysincl_exp__sysincl_exp xIdNames("tagCMPLX")
  XCOMMON_EXTRAS xFreF(0) xAssF(0) xEqF(yEq_z_sysincl_exp_24_tagCMPLX)
  xTestF(0), (xptrint)sizeof(z_sysincl_exp_24_tagCMPLX), xStruct,
  (xSortIdNode)0, (xSortIdNode)0, 0, 0, 0, 0
  xRaWF((tSDLTypeInfo *)&ySDL_z_sysincl_exp_24_tagCMPLX) XSRT_EXTRAS};
#endif
#ifndef XOPTSTRUCT
/*---------------COMPONENTS----------------*/
static XCONST struct xVarIdStruct yVarR_z_sysincl_exp_249_R = {xVariableEC
  xSymbTLink((xIdNode)0, (xIdNode)0), (xIdNode)&ySrtR_z_sysincl_exp_24_tagCMPLX
  xIdNames("R") XCOMMON_EXTRAS, &xSrtR_SDL_Real,
  (tSDLTypeInfo *)&ySDL_SDL_Real, xOffsetOf(z_sysincl_exp_24_tagCMPLX, R),
  (xptrint)0, 0 XVAR_EXTRAS};
static XCONST struct xVarIdStruct yVarR_z_sysincl_exp_24A_I = {xVariableEC
  xSymbTLink((xIdNode)0, (xIdNode)0), (xIdNode)&ySrtR_z_sysincl_exp_24_tagCMPLX
  xIdNames("I") XCOMMON_EXTRAS, &xSrtR_SDL_Real,
  (tSDLTypeInfo *)&ySDL_SDL_Real, xOffsetOf(z_sysincl_exp_24_tagCMPLX, I),
  (xptrint)0, 0 XVAR_EXTRAS};
#endif

/*****
* NEWTYPE CA_sysincl_exp_80_X_tagCMPLX  (BODY section)
* <<PACKAGE sysincl_exp>>
* #SDTREF(TEXT,C:\\Kolevatov\\Projects\\SDL\\STACK80211\\proc_phy_exp.h,24)
******/

/* *** CA_sysincl_exp_80_X_tagCMPLX *** */
tSDLArrayInfo ySDL_z_sysincl_exp_25_CA_sysincl_exp_80_X_tagCMPLX =
  {type_SDL_Carray, 6,
  (xptrint)sizeof(z_sysincl_exp_25_CA_sysincl_exp_80_X_tagCMPLX)
  T_SDL_OPFUNCS(0) T_SDL_EXTRA_VALUE
  T_SDL_Names("CA_sysincl_exp_80_X_tagCMPLX")
  xRaWF((xIdNode)&yPacR_z_sysincl_exp__sysincl_exp)
  xRaWF(&ySrtR_z_sysincl_exp_25_CA_sysincl_exp_80_X_tagCMPLX),
  (tSDLTypeInfo *)&ySDL_z_sysincl_exp_24_tagCMPLX, SDL_INTEGER_LIT(80)
  xRaWF((tSDLTypeInfo *)&ySDL_SDL_Integer) xRaWF(0)};
#ifndef XOPTSORT
XCONST struct xSortIdStruct ySrtR_z_sysincl_exp_25_CA_sysincl_exp_80_X_tagCMPLX =
  {xSortEC xSymbTLink((xIdNode)0, (xIdNode)0),
  (xIdNode)&yPacR_z_sysincl_exp__sysincl_exp
  xIdNames("CA_sysincl_exp_80_X_tagCMPLX") XCOMMON_EXTRAS xFreF(0)
  xAssF(yAss_z_sysincl_exp_25_CA_sysincl_exp_80_X_tagCMPLX)
  xEqF(yEq_z_sysincl_exp_25_CA_sysincl_exp_80_X_tagCMPLX) xTestF(0),
  (xptrint)sizeof(z_sysincl_exp_25_CA_sysincl_exp_80_X_tagCMPLX), xCArray,
  &ySrtR_z_sysincl_exp_24_tagCMPLX, xSrtN_SDL_Integer, 0,
  SDL_INTEGER_LIT(80)-1, 0, 0
  xRaWF((tSDLTypeInfo *)&ySDL_z_sysincl_exp_25_CA_sysincl_exp_80_X_tagCMPLX)
  XSRT_EXTRAS};
#endif

/*-------------------TSTI-------------------*/
#ifdef XEINDEX
SDL_Integer yTstI_z_sysincl_exp_25_CA_sysincl_exp_80_X_tagCMPLX
  (SDL_Integer yExpr)
{
  if (yExpr < 0 || yExpr >= SDL_INTEGER_LIT(80)) {
    xErrorIndex((tSDLTypeInfo *)&ySDL_SDL_Integer, &yExpr);
    return 0;
  }
  return yExpr;
}
#endif

/*****
* NEWTYPE tagSYMBOL  (BODY section)
* <<PACKAGE sysincl_exp>>
* #SDTREF(TEXT,C:\\Kolevatov\\Projects\\SDL\\STACK80211\\proc_phy_exp.h,24)
******/

/* *** tagSYMBOL *** */
static tSDLFieldInfo fSDL_z_sysincl_exp_26_tagSYMBOL[] = {
  {(tSDLTypeInfo *)&ySDL_z_sysincl_exp_25_CA_sysincl_exp_80_X_tagCMPLX
    T_SDL_Names("m_pData"), xOffsetOf(z_sysincl_exp_26_tagSYMBOL, m_pData), 0}
};
tSDLStructInfo ySDL_z_sysincl_exp_26_tagSYMBOL = {type_SDL_Struct, 6,
  (xptrint)sizeof(z_sysincl_exp_26_tagSYMBOL) T_SDL_OPFUNCS(0)
  T_SDL_EXTRA_VALUE T_SDL_Names("tagSYMBOL")
  xRaWF((xIdNode)&yPacR_z_sysincl_exp__sysincl_exp)
  xRaWF(&ySrtR_z_sysincl_exp_26_tagSYMBOL), fSDL_z_sysincl_exp_26_tagSYMBOL, 1};
#ifndef XOPTSORT
XCONST struct xSortIdStruct ySrtR_z_sysincl_exp_26_tagSYMBOL = {xSortEC
  xSymbTLink((xIdNode)0, (xIdNode)0),
  (xIdNode)&yPacR_z_sysincl_exp__sysincl_exp xIdNames("tagSYMBOL")
  XCOMMON_EXTRAS xFreF(0) xAssF(yAss_z_sysincl_exp_26_tagSYMBOL)
  xEqF(yEq_z_sysincl_exp_26_tagSYMBOL) xTestF(0),
  (xptrint)sizeof(z_sysincl_exp_26_tagSYMBOL), xStruct, (xSortIdNode)0,
  (xSortIdNode)0, 0, 0, 0, 0
  xRaWF((tSDLTypeInfo *)&ySDL_z_sysincl_exp_26_tagSYMBOL) XSRT_EXTRAS};
#endif
#ifndef XOPTSTRUCT
/*---------------COMPONENTS----------------*/
static XCONST struct xVarIdStruct yVarR_z_sysincl_exp_267_m_pData =
  {xVariableEC xSymbTLink((xIdNode)0, (xIdNode)0),
  (xIdNode)&ySrtR_z_sysincl_exp_26_tagSYMBOL xIdNames("m_pData")
  XCOMMON_EXTRAS, &ySrtR_z_sysincl_exp_25_CA_sysincl_exp_80_X_tagCMPLX,
  (tSDLTypeInfo *)&ySDL_z_sysincl_exp_25_CA_sysincl_exp_80_X_tagCMPLX,
  xOffsetOf(z_sysincl_exp_26_tagSYMBOL, m_pData), (xptrint)0, 0 XVAR_EXTRAS};
#endif

/*****
* NEWTYPE CA_sysincl_exp_20_X_tagCMPLX  (BODY section)
* <<PACKAGE sysincl_exp>>
* #SDTREF(TEXT,C:\\Kolevatov\\Projects\\SDL\\STACK80211\\proc_phy_exp.h,31)
******/

/* *** CA_sysincl_exp_20_X_tagCMPLX *** */
tSDLArrayInfo ySDL_z_sysincl_exp_27_CA_sysincl_exp_20_X_tagCMPLX =
  {type_SDL_Carray, 6,
  (xptrint)sizeof(z_sysincl_exp_27_CA_sysincl_exp_20_X_tagCMPLX)
  T_SDL_OPFUNCS(0) T_SDL_EXTRA_VALUE
  T_SDL_Names("CA_sysincl_exp_20_X_tagCMPLX")
  xRaWF((xIdNode)&yPacR_z_sysincl_exp__sysincl_exp)
  xRaWF(&ySrtR_z_sysincl_exp_27_CA_sysincl_exp_20_X_tagCMPLX),
  (tSDLTypeInfo *)&ySDL_z_sysincl_exp_24_tagCMPLX, SDL_INTEGER_LIT(20)
  xRaWF((tSDLTypeInfo *)&ySDL_SDL_Integer) xRaWF(0)};
#ifndef XOPTSORT
XCONST struct xSortIdStruct ySrtR_z_sysincl_exp_27_CA_sysincl_exp_20_X_tagCMPLX =
  {xSortEC xSymbTLink((xIdNode)0, (xIdNode)0),
  (xIdNode)&yPacR_z_sysincl_exp__sysincl_exp
  xIdNames("CA_sysincl_exp_20_X_tagCMPLX") XCOMMON_EXTRAS xFreF(0)
  xAssF(yAss_z_sysincl_exp_27_CA_sysincl_exp_20_X_tagCMPLX)
  xEqF(yEq_z_sysincl_exp_27_CA_sysincl_exp_20_X_tagCMPLX) xTestF(0),
  (xptrint)sizeof(z_sysincl_exp_27_CA_sysincl_exp_20_X_tagCMPLX), xCArray,
  &ySrtR_z_sysincl_exp_24_tagCMPLX, xSrtN_SDL_Integer, 0,
  SDL_INTEGER_LIT(20)-1, 0, 0
  xRaWF((tSDLTypeInfo *)&ySDL_z_sysincl_exp_27_CA_sysincl_exp_20_X_tagCMPLX)
  XSRT_EXTRAS};
#endif

/*-------------------TSTI-------------------*/
#ifdef XEINDEX
SDL_Integer yTstI_z_sysincl_exp_27_CA_sysincl_exp_20_X_tagCMPLX
  (SDL_Integer yExpr)
{
  if (yExpr < 0 || yExpr >= SDL_INTEGER_LIT(20)) {
    xErrorIndex((tSDLTypeInfo *)&ySDL_SDL_Integer, &yExpr);
    return 0;
  }
  return yExpr;
}
#endif

/*****
* NEWTYPE tagMDM_SAMPLES  (BODY section)
* <<PACKAGE sysincl_exp>>
* #SDTREF(TEXT,C:\\Kolevatov\\Projects\\SDL\\STACK80211\\proc_phy_exp.h,31)
******/

/* *** tagMDM_SAMPLES *** */
static tSDLFieldInfo fSDL_z_sysincl_exp_28_tagMDM_SAMPLES[] = {
  {(tSDLTypeInfo *)&ySDL_z_sysincl_exp_27_CA_sysincl_exp_20_X_tagCMPLX
    T_SDL_Names("m_pData"),
    xOffsetOf(z_sysincl_exp_28_tagMDM_SAMPLES, m_pData), 0}
};
tSDLStructInfo ySDL_z_sysincl_exp_28_tagMDM_SAMPLES = {type_SDL_Struct, 6,
  (xptrint)sizeof(z_sysincl_exp_28_tagMDM_SAMPLES) T_SDL_OPFUNCS(0)
  T_SDL_EXTRA_VALUE T_SDL_Names("tagMDM_SAMPLES")
  xRaWF((xIdNode)&yPacR_z_sysincl_exp__sysincl_exp)
  xRaWF(&ySrtR_z_sysincl_exp_28_tagMDM_SAMPLES),
  fSDL_z_sysincl_exp_28_tagMDM_SAMPLES, 1};
#ifndef XOPTSORT
XCONST struct xSortIdStruct ySrtR_z_sysincl_exp_28_tagMDM_SAMPLES = {xSortEC
  xSymbTLink((xIdNode)0, (xIdNode)0),
  (xIdNode)&yPacR_z_sysincl_exp__sysincl_exp xIdNames("tagMDM_SAMPLES")
  XCOMMON_EXTRAS xFreF(0) xAssF(yAss_z_sysincl_exp_28_tagMDM_SAMPLES)
  xEqF(yEq_z_sysincl_exp_28_tagMDM_SAMPLES) xTestF(0),
  (xptrint)sizeof(z_sysincl_exp_28_tagMDM_SAMPLES), xStruct, (xSortIdNode)0,
  (xSortIdNode)0, 0, 0, 0, 0
  xRaWF((tSDLTypeInfo *)&ySDL_z_sysincl_exp_28_tagMDM_SAMPLES) XSRT_EXTRAS};
#endif
#ifndef XOPTSTRUCT
/*---------------COMPONENTS----------------*/
static XCONST struct xVarIdStruct yVarR_z_sysincl_exp_287_m_pData =
  {xVariableEC xSymbTLink((xIdNode)0, (xIdNode)0),
  (xIdNode)&ySrtR_z_sysincl_exp_28_tagMDM_SAMPLES xIdNames("m_pData")
  XCOMMON_EXTRAS, &ySrtR_z_sysincl_exp_27_CA_sysincl_exp_20_X_tagCMPLX,
  (tSDLTypeInfo *)&ySDL_z_sysincl_exp_27_CA_sysincl_exp_20_X_tagCMPLX,
  xOffsetOf(z_sysincl_exp_28_tagMDM_SAMPLES, m_pData), (xptrint)0, 0
  XVAR_EXTRAS};
#endif

/*****
* SYNTYPE SYMB  (BODY section)
* <<PACKAGE sysincl_exp>>
* #SDTREF(TEXT,C:\\Kolevatov\\Projects\\SDL\\STACK80211\\proc_phy_exp.h,36)
******/

/* *** SYMB *** */
tSDLGenInfo ySDL_z_sysincl_exp_2M_SYMB = {type_SDL_Syntype, 6,
  (xptrint)sizeof(z_sysincl_exp_2M_SYMB) T_SDL_OPFUNCS(0) T_SDL_EXTRA_VALUE
  T_SDL_Names("SYMB") xRaWF((xIdNode)&yPacR_z_sysincl_exp__sysincl_exp)
  xRaWF(&ySrtR_z_sysincl_exp_2M_SYMB),
  (tSDLTypeInfo *)&ySDL_z_sysincl_exp_26_tagSYMBOL};
#ifndef XOPTSORT
XCONST struct xSortIdStruct ySrtR_z_sysincl_exp_2M_SYMB = {xSortEC
  xSymbTLink((xIdNode)0, (xIdNode)0),
  (xIdNode)&yPacR_z_sysincl_exp__sysincl_exp xIdNames("SYMB") XCOMMON_EXTRAS
  xFreF(0) xAssF(yAss_z_sysincl_exp_26_tagSYMBOL)
  xEqF(yEq_z_sysincl_exp_26_tagSYMBOL) xTestF(0),
  (xptrint)sizeof(z_sysincl_exp_2M_SYMB), xSyntype,
  &ySrtR_z_sysincl_exp_26_tagSYMBOL, &ySrtR_z_sysincl_exp_26_tagSYMBOL, 0, 0,
  0, 0 xRaWF((tSDLTypeInfo *)&ySDL_z_sysincl_exp_2M_SYMB) XSRT_EXTRAS};
#endif

/*****
* SYNTYPE SMPLS  (BODY section)
* <<PACKAGE sysincl_exp>>
* #SDTREF(TEXT,C:\\Kolevatov\\Projects\\SDL\\STACK80211\\proc_phy_exp.h,37)
******/

/* *** SMPLS *** */
tSDLGenInfo ySDL_z_sysincl_exp_2N_SMPLS = {type_SDL_Syntype, 6,
  (xptrint)sizeof(z_sysincl_exp_2N_SMPLS) T_SDL_OPFUNCS(0) T_SDL_EXTRA_VALUE
  T_SDL_Names("SMPLS") xRaWF((xIdNode)&yPacR_z_sysincl_exp__sysincl_exp)
  xRaWF(&ySrtR_z_sysincl_exp_2N_SMPLS),
  (tSDLTypeInfo *)&ySDL_z_sysincl_exp_28_tagMDM_SAMPLES};
#ifndef XOPTSORT
XCONST struct xSortIdStruct ySrtR_z_sysincl_exp_2N_SMPLS = {xSortEC
  xSymbTLink((xIdNode)0, (xIdNode)0),
  (xIdNode)&yPacR_z_sysincl_exp__sysincl_exp xIdNames("SMPLS") XCOMMON_EXTRAS
  xFreF(0) xAssF(yAss_z_sysincl_exp_28_tagMDM_SAMPLES)
  xEqF(yEq_z_sysincl_exp_28_tagMDM_SAMPLES) xTestF(0),
  (xptrint)sizeof(z_sysincl_exp_2N_SMPLS), xSyntype,
  &ySrtR_z_sysincl_exp_28_tagMDM_SAMPLES,
  &ySrtR_z_sysincl_exp_28_tagMDM_SAMPLES, 0, 0, 0, 0
  xRaWF((tSDLTypeInfo *)&ySDL_z_sysincl_exp_2N_SMPLS) XSRT_EXTRAS};
#endif

/*****
* NEWTYPE Ref_sysincl_exp_Integer  (BODY section)
* <<PACKAGE sysincl_exp>>
* #SDTREF(TEXT,C:\\Kolevatov\\Projects\\SDL\\STACK80211\\export_sdl_exp.h,33)
******/

/* *** Ref_sysincl_exp_Integer *** */
tSDLGenInfo ySDL_z_sysincl_exp_29_Ref_sysincl_exp_Integer = {type_SDL_Ref, 0,
  (xptrint)sizeof(z_sysincl_exp_29_Ref_sysincl_exp_Integer) T_SDL_OPFUNCS(0)
  T_SDL_EXTRA_VALUE T_SDL_Names("Ref_sysincl_exp_Integer")
  xRaWF((xIdNode)&yPacR_z_sysincl_exp__sysincl_exp)
  xRaWF(&ySrtR_z_sysincl_exp_29_Ref_sysincl_exp_Integer),
  (tSDLTypeInfo *)&ySDL_SDL_Integer};
#ifndef XOPTSORT
XCONST struct xSortIdStruct ySrtR_z_sysincl_exp_29_Ref_sysincl_exp_Integer =
  {xSortEC xSymbTLink((xIdNode)0, (xIdNode)0),
  (xIdNode)&yPacR_z_sysincl_exp__sysincl_exp
  xIdNames("Ref_sysincl_exp_Integer") XCOMMON_EXTRAS xFreF(0) xAssF(0) xEqF(0)
  xTestF(0), (xptrint)sizeof(z_sysincl_exp_29_Ref_sysincl_exp_Integer), xRef,
  &xSrtR_SDL_Integer, (xSortIdNode)0, 0, 0, 0, 0
  xRaWF((tSDLTypeInfo *)&ySDL_z_sysincl_exp_29_Ref_sysincl_exp_Integer)
  XSRT_EXTRAS};
#endif

void * yMkAddr_z_sysincl_exp_29_Ref_sysincl_exp_Integer (z_sysincl_exp_29_Ref_sysincl_exp_Integer yMkValue, z_sysincl_exp_29_Ref_sysincl_exp_Integer * yMkResult)
{
  *yMkResult = yMkValue;
  return (void *)yMkResult;
}

/*****
* NEWTYPE Ref_sysincl_exp_tagMAC_ST  (BODY section)
* <<PACKAGE sysincl_exp>>
* #SDTREF(TEXT,C:\\Kolevatov\\Projects\\SDL\\STACK80211\\export_sdl_exp.h,38)
******/

/* *** Ref_sysincl_exp_tagMAC_ST *** */
tSDLGenInfo ySDL_z_sysincl_exp_2A_Ref_sysincl_exp_tagMAC_ST = {type_SDL_Ref, 0,
  (xptrint)sizeof(z_sysincl_exp_2A_Ref_sysincl_exp_tagMAC_ST) T_SDL_OPFUNCS(0)
  T_SDL_EXTRA_VALUE T_SDL_Names("Ref_sysincl_exp_tagMAC_ST")
  xRaWF((xIdNode)&yPacR_z_sysincl_exp__sysincl_exp)
  xRaWF(&ySrtR_z_sysincl_exp_2A_Ref_sysincl_exp_tagMAC_ST),
  (tSDLTypeInfo *)&ySDL_z_sysincl_exp_1Y_tagMAC_ST};
#ifndef XOPTSORT
XCONST struct xSortIdStruct ySrtR_z_sysincl_exp_2A_Ref_sysincl_exp_tagMAC_ST =
  {xSortEC xSymbTLink((xIdNode)0, (xIdNode)0),
  (xIdNode)&yPacR_z_sysincl_exp__sysincl_exp
  xIdNames("Ref_sysincl_exp_tagMAC_ST") XCOMMON_EXTRAS xFreF(0) xAssF(0)
  xEqF(0) xTestF(0),
  (xptrint)sizeof(z_sysincl_exp_2A_Ref_sysincl_exp_tagMAC_ST), xRef,
  &ySrtR_z_sysincl_exp_1Y_tagMAC_ST, (xSortIdNode)0, 0, 0, 0, 0
  xRaWF((tSDLTypeInfo *)&ySDL_z_sysincl_exp_2A_Ref_sysincl_exp_tagMAC_ST)
  XSRT_EXTRAS};
#endif

void * yMkAddr_z_sysincl_exp_2A_Ref_sysincl_exp_tagMAC_ST (z_sysincl_exp_2A_Ref_sysincl_exp_tagMAC_ST yMkValue, z_sysincl_exp_2A_Ref_sysincl_exp_tagMAC_ST * yMkResult)
{
  *yMkResult = yMkValue;
  return (void *)yMkResult;
}

/*****
* NEWTYPE Ref_sysincl_exp_tagMACADDR  (BODY section)
* <<PACKAGE sysincl_exp>>
* #SDTREF(TEXT,C:\\Kolevatov\\Projects\\SDL\\STACK80211\\export_sdl_exp.h,44)
******/

/* *** Ref_sysincl_exp_tagMACADDR *** */
tSDLGenInfo ySDL_z_sysincl_exp_2B_Ref_sysincl_exp_tagMACADDR = {type_SDL_Ref,
  0, (xptrint)sizeof(z_sysincl_exp_2B_Ref_sysincl_exp_tagMACADDR)
  T_SDL_OPFUNCS(0) T_SDL_EXTRA_VALUE T_SDL_Names("Ref_sysincl_exp_tagMACADDR")
  xRaWF((xIdNode)&yPacR_z_sysincl_exp__sysincl_exp)
  xRaWF(&ySrtR_z_sysincl_exp_2B_Ref_sysincl_exp_tagMACADDR),
  (tSDLTypeInfo *)&ySDL_z_sysincl_exp_1R_tagMACADDR};
#ifndef XOPTSORT
XCONST struct xSortIdStruct ySrtR_z_sysincl_exp_2B_Ref_sysincl_exp_tagMACADDR =
  {xSortEC xSymbTLink((xIdNode)0, (xIdNode)0),
  (xIdNode)&yPacR_z_sysincl_exp__sysincl_exp
  xIdNames("Ref_sysincl_exp_tagMACADDR") XCOMMON_EXTRAS xFreF(0) xAssF(0)
  xEqF(0) xTestF(0),
  (xptrint)sizeof(z_sysincl_exp_2B_Ref_sysincl_exp_tagMACADDR), xRef,
  &ySrtR_z_sysincl_exp_1R_tagMACADDR, (xSortIdNode)0, 0, 0, 0, 0
  xRaWF((tSDLTypeInfo *)&ySDL_z_sysincl_exp_2B_Ref_sysincl_exp_tagMACADDR)
  XSRT_EXTRAS};
#endif

void * yMkAddr_z_sysincl_exp_2B_Ref_sysincl_exp_tagMACADDR (z_sysincl_exp_2B_Ref_sysincl_exp_tagMACADDR yMkValue, z_sysincl_exp_2B_Ref_sysincl_exp_tagMACADDR * yMkResult)
{
  *yMkResult = yMkValue;
  return (void *)yMkResult;
}

/*****
* NEWTYPE Ref_sysincl_exp_tagFLATARRAY  (BODY section)
* <<PACKAGE sysincl_exp>>
* #SDTREF(TEXT,C:\\Kolevatov\\Projects\\SDL\\STACK80211\\export_sdl_exp.h,44)
******/

/* *** Ref_sysincl_exp_tagFLATARRAY *** */
tSDLGenInfo ySDL_z_sysincl_exp_2C_Ref_sysincl_exp_tagFLATARRAY = {type_SDL_Ref,
  0, (xptrint)sizeof(z_sysincl_exp_2C_Ref_sysincl_exp_tagFLATARRAY)
  T_SDL_OPFUNCS(0) T_SDL_EXTRA_VALUE
  T_SDL_Names("Ref_sysincl_exp_tagFLATARRAY")
  xRaWF((xIdNode)&yPacR_z_sysincl_exp__sysincl_exp)
  xRaWF(&ySrtR_z_sysincl_exp_2C_Ref_sysincl_exp_tagFLATARRAY),
  (tSDLTypeInfo *)&ySDL_z_sysincl_exp_1U_tagFLATARRAY};
#ifndef XOPTSORT
XCONST struct xSortIdStruct ySrtR_z_sysincl_exp_2C_Ref_sysincl_exp_tagFLATARRAY =
  {xSortEC xSymbTLink((xIdNode)0, (xIdNode)0),
  (xIdNode)&yPacR_z_sysincl_exp__sysincl_exp
  xIdNames("Ref_sysincl_exp_tagFLATARRAY") XCOMMON_EXTRAS xFreF(0) xAssF(0)
  xEqF(0) xTestF(0),
  (xptrint)sizeof(z_sysincl_exp_2C_Ref_sysincl_exp_tagFLATARRAY), xRef,
  &ySrtR_z_sysincl_exp_1U_tagFLATARRAY, (xSortIdNode)0, 0, 0, 0, 0
  xRaWF((tSDLTypeInfo *)&ySDL_z_sysincl_exp_2C_Ref_sysincl_exp_tagFLATARRAY)
  XSRT_EXTRAS};
#endif

void * yMkAddr_z_sysincl_exp_2C_Ref_sysincl_exp_tagFLATARRAY (z_sysincl_exp_2C_Ref_sysincl_exp_tagFLATARRAY yMkValue, z_sysincl_exp_2C_Ref_sysincl_exp_tagFLATARRAY * yMkResult)
{
  *yMkResult = yMkValue;
  return (void *)yMkResult;
}

/*****
* NEWTYPE Ref_sysincl_exp_tagFLDPSDU  (BODY section)
* <<PACKAGE sysincl_exp>>
* #SDTREF(TEXT,C:\\Kolevatov\\Projects\\SDL\\STACK80211\\export_sdl_exp.h,45)
******/

/* *** Ref_sysincl_exp_tagFLDPSDU *** */
tSDLGenInfo ySDL_z_sysincl_exp_2D_Ref_sysincl_exp_tagFLDPSDU = {type_SDL_Ref,
  0, (xptrint)sizeof(z_sysincl_exp_2D_Ref_sysincl_exp_tagFLDPSDU)
  T_SDL_OPFUNCS(0) T_SDL_EXTRA_VALUE T_SDL_Names("Ref_sysincl_exp_tagFLDPSDU")
  xRaWF((xIdNode)&yPacR_z_sysincl_exp__sysincl_exp)
  xRaWF(&ySrtR_z_sysincl_exp_2D_Ref_sysincl_exp_tagFLDPSDU),
  (tSDLTypeInfo *)&ySDL_z_sysincl_exp_20_tagFLDPSDU};
#ifndef XOPTSORT
XCONST struct xSortIdStruct ySrtR_z_sysincl_exp_2D_Ref_sysincl_exp_tagFLDPSDU =
  {xSortEC xSymbTLink((xIdNode)0, (xIdNode)0),
  (xIdNode)&yPacR_z_sysincl_exp__sysincl_exp
  xIdNames("Ref_sysincl_exp_tagFLDPSDU") XCOMMON_EXTRAS xFreF(0) xAssF(0)
  xEqF(0) xTestF(0),
  (xptrint)sizeof(z_sysincl_exp_2D_Ref_sysincl_exp_tagFLDPSDU), xRef,
  &ySrtR_z_sysincl_exp_20_tagFLDPSDU, (xSortIdNode)0, 0, 0, 0, 0
  xRaWF((tSDLTypeInfo *)&ySDL_z_sysincl_exp_2D_Ref_sysincl_exp_tagFLDPSDU)
  XSRT_EXTRAS};
#endif

void * yMkAddr_z_sysincl_exp_2D_Ref_sysincl_exp_tagFLDPSDU (z_sysincl_exp_2D_Ref_sysincl_exp_tagFLDPSDU yMkValue, z_sysincl_exp_2D_Ref_sysincl_exp_tagFLDPSDU * yMkResult)
{
  *yMkResult = yMkValue;
  return (void *)yMkResult;
}

/*****
* NEWTYPE Ref_sysincl_exp_tagBITSEQ  (BODY section)
* <<PACKAGE sysincl_exp>>
* #SDTREF(TEXT,C:\\Kolevatov\\Projects\\SDL\\STACK80211\\export_sdl_exp.h,71)
******/

/* *** Ref_sysincl_exp_tagBITSEQ *** */
tSDLGenInfo ySDL_z_sysincl_exp_2E_Ref_sysincl_exp_tagBITSEQ = {type_SDL_Ref, 0,
  (xptrint)sizeof(z_sysincl_exp_2E_Ref_sysincl_exp_tagBITSEQ) T_SDL_OPFUNCS(0)
  T_SDL_EXTRA_VALUE T_SDL_Names("Ref_sysincl_exp_tagBITSEQ")
  xRaWF((xIdNode)&yPacR_z_sysincl_exp__sysincl_exp)
  xRaWF(&ySrtR_z_sysincl_exp_2E_Ref_sysincl_exp_tagBITSEQ),
  (tSDLTypeInfo *)&ySDL_z_sysincl_exp_23_tagBITSEQ};
#ifndef XOPTSORT
XCONST struct xSortIdStruct ySrtR_z_sysincl_exp_2E_Ref_sysincl_exp_tagBITSEQ =
  {xSortEC xSymbTLink((xIdNode)0, (xIdNode)0),
  (xIdNode)&yPacR_z_sysincl_exp__sysincl_exp
  xIdNames("Ref_sysincl_exp_tagBITSEQ") XCOMMON_EXTRAS xFreF(0) xAssF(0)
  xEqF(0) xTestF(0),
  (xptrint)sizeof(z_sysincl_exp_2E_Ref_sysincl_exp_tagBITSEQ), xRef,
  &ySrtR_z_sysincl_exp_23_tagBITSEQ, (xSortIdNode)0, 0, 0, 0, 0
  xRaWF((tSDLTypeInfo *)&ySDL_z_sysincl_exp_2E_Ref_sysincl_exp_tagBITSEQ)
  XSRT_EXTRAS};
#endif

void * yMkAddr_z_sysincl_exp_2E_Ref_sysincl_exp_tagBITSEQ (z_sysincl_exp_2E_Ref_sysincl_exp_tagBITSEQ yMkValue, z_sysincl_exp_2E_Ref_sysincl_exp_tagBITSEQ * yMkResult)
{
  *yMkResult = yMkValue;
  return (void *)yMkResult;
}

/*****
* NEWTYPE Ref_sysincl_exp_tagSIGNAL  (BODY section)
* <<PACKAGE sysincl_exp>>
* #SDTREF(TEXT,C:\\Kolevatov\\Projects\\SDL\\STACK80211\\export_sdl_exp.h,71)
******/

/* *** Ref_sysincl_exp_tagSIGNAL *** */
tSDLGenInfo ySDL_z_sysincl_exp_2F_Ref_sysincl_exp_tagSIGNAL = {type_SDL_Ref, 0,
  (xptrint)sizeof(z_sysincl_exp_2F_Ref_sysincl_exp_tagSIGNAL) T_SDL_OPFUNCS(0)
  T_SDL_EXTRA_VALUE T_SDL_Names("Ref_sysincl_exp_tagSIGNAL")
  xRaWF((xIdNode)&yPacR_z_sysincl_exp__sysincl_exp)
  xRaWF(&ySrtR_z_sysincl_exp_2F_Ref_sysincl_exp_tagSIGNAL),
  (tSDLTypeInfo *)&ySDL_z_sysincl_exp_21_tagSIGNAL};
#ifndef XOPTSORT
XCONST struct xSortIdStruct ySrtR_z_sysincl_exp_2F_Ref_sysincl_exp_tagSIGNAL =
  {xSortEC xSymbTLink((xIdNode)0, (xIdNode)0),
  (xIdNode)&yPacR_z_sysincl_exp__sysincl_exp
  xIdNames("Ref_sysincl_exp_tagSIGNAL") XCOMMON_EXTRAS xFreF(0) xAssF(0)
  xEqF(0) xTestF(0),
  (xptrint)sizeof(z_sysincl_exp_2F_Ref_sysincl_exp_tagSIGNAL), xRef,
  &ySrtR_z_sysincl_exp_21_tagSIGNAL, (xSortIdNode)0, 0, 0, 0, 0
  xRaWF((tSDLTypeInfo *)&ySDL_z_sysincl_exp_2F_Ref_sysincl_exp_tagSIGNAL)
  XSRT_EXTRAS};
#endif

void * yMkAddr_z_sysincl_exp_2F_Ref_sysincl_exp_tagSIGNAL (z_sysincl_exp_2F_Ref_sysincl_exp_tagSIGNAL yMkValue, z_sysincl_exp_2F_Ref_sysincl_exp_tagSIGNAL * yMkResult)
{
  *yMkResult = yMkValue;
  return (void *)yMkResult;
}

/*****
* NEWTYPE Ref_sysincl_exp_tagSYMBOL  (BODY section)
* <<PACKAGE sysincl_exp>>
* #SDTREF(TEXT,C:\\Kolevatov\\Projects\\SDL\\STACK80211\\export_sdl_exp.h,75)
******/

/* *** Ref_sysincl_exp_tagSYMBOL *** */
tSDLGenInfo ySDL_z_sysincl_exp_2G_Ref_sysincl_exp_tagSYMBOL = {type_SDL_Ref, 0,
  (xptrint)sizeof(z_sysincl_exp_2G_Ref_sysincl_exp_tagSYMBOL) T_SDL_OPFUNCS(0)
  T_SDL_EXTRA_VALUE T_SDL_Names("Ref_sysincl_exp_tagSYMBOL")
  xRaWF((xIdNode)&yPacR_z_sysincl_exp__sysincl_exp)
  xRaWF(&ySrtR_z_sysincl_exp_2G_Ref_sysincl_exp_tagSYMBOL),
  (tSDLTypeInfo *)&ySDL_z_sysincl_exp_26_tagSYMBOL};
#ifndef XOPTSORT
XCONST struct xSortIdStruct ySrtR_z_sysincl_exp_2G_Ref_sysincl_exp_tagSYMBOL =
  {xSortEC xSymbTLink((xIdNode)0, (xIdNode)0),
  (xIdNode)&yPacR_z_sysincl_exp__sysincl_exp
  xIdNames("Ref_sysincl_exp_tagSYMBOL") XCOMMON_EXTRAS xFreF(0) xAssF(0)
  xEqF(0) xTestF(0),
  (xptrint)sizeof(z_sysincl_exp_2G_Ref_sysincl_exp_tagSYMBOL), xRef,
  &ySrtR_z_sysincl_exp_26_tagSYMBOL, (xSortIdNode)0, 0, 0, 0, 0
  xRaWF((tSDLTypeInfo *)&ySDL_z_sysincl_exp_2G_Ref_sysincl_exp_tagSYMBOL)
  XSRT_EXTRAS};
#endif

void * yMkAddr_z_sysincl_exp_2G_Ref_sysincl_exp_tagSYMBOL (z_sysincl_exp_2G_Ref_sysincl_exp_tagSYMBOL yMkValue, z_sysincl_exp_2G_Ref_sysincl_exp_tagSYMBOL * yMkResult)
{
  *yMkResult = yMkValue;
  return (void *)yMkResult;
}

/*****
* NEWTYPE Ref_sysincl_exp_tagMDM_SAMPLES  (BODY section)
* <<PACKAGE sysincl_exp>>
* #SDTREF(TEXT,C:\\Kolevatov\\Projects\\SDL\\STACK80211\\export_sdl_exp.h,103)
******/

/* *** Ref_sysincl_exp_tagMDM_SAMPLES *** */
tSDLGenInfo ySDL_z_sysincl_exp_2H_Ref_sysincl_exp_tagMDM_SAMPLES =
  {type_SDL_Ref, 0,
  (xptrint)sizeof(z_sysincl_exp_2H_Ref_sysincl_exp_tagMDM_SAMPLES)
  T_SDL_OPFUNCS(0) T_SDL_EXTRA_VALUE
  T_SDL_Names("Ref_sysincl_exp_tagMDM_SAMPLES")
  xRaWF((xIdNode)&yPacR_z_sysincl_exp__sysincl_exp)
  xRaWF(&ySrtR_z_sysincl_exp_2H_Ref_sysincl_exp_tagMDM_SAMPLES),
  (tSDLTypeInfo *)&ySDL_z_sysincl_exp_28_tagMDM_SAMPLES};
#ifndef XOPTSORT
XCONST struct xSortIdStruct ySrtR_z_sysincl_exp_2H_Ref_sysincl_exp_tagMDM_SAMPLES =
  {xSortEC xSymbTLink((xIdNode)0, (xIdNode)0),
  (xIdNode)&yPacR_z_sysincl_exp__sysincl_exp
  xIdNames("Ref_sysincl_exp_tagMDM_SAMPLES") XCOMMON_EXTRAS xFreF(0) xAssF(0)
  xEqF(0) xTestF(0),
  (xptrint)sizeof(z_sysincl_exp_2H_Ref_sysincl_exp_tagMDM_SAMPLES), xRef,
  &ySrtR_z_sysincl_exp_28_tagMDM_SAMPLES, (xSortIdNode)0, 0, 0, 0, 0
  xRaWF((tSDLTypeInfo *)&ySDL_z_sysincl_exp_2H_Ref_sysincl_exp_tagMDM_SAMPLES)
  XSRT_EXTRAS};
#endif

void * yMkAddr_z_sysincl_exp_2H_Ref_sysincl_exp_tagMDM_SAMPLES (z_sysincl_exp_2H_Ref_sysincl_exp_tagMDM_SAMPLES yMkValue, z_sysincl_exp_2H_Ref_sysincl_exp_tagMDM_SAMPLES * yMkResult)
{
  *yMkResult = yMkValue;
  return (void *)yMkResult;
}

/*****
* NEWTYPE Ref_sysincl_exp_Real  (BODY section)
* <<PACKAGE sysincl_exp>>
* #SDTREF(TEXT,C:\\Kolevatov\\Projects\\SDL\\STACK80211\\export_sdl_exp.h,109)
******/

/* *** Ref_sysincl_exp_Real *** */
tSDLGenInfo ySDL_z_sysincl_exp_2I_Ref_sysincl_exp_Real = {type_SDL_Ref, 0,
  (xptrint)sizeof(z_sysincl_exp_2I_Ref_sysincl_exp_Real) T_SDL_OPFUNCS(0)
  T_SDL_EXTRA_VALUE T_SDL_Names("Ref_sysincl_exp_Real")
  xRaWF((xIdNode)&yPacR_z_sysincl_exp__sysincl_exp)
  xRaWF(&ySrtR_z_sysincl_exp_2I_Ref_sysincl_exp_Real),
  (tSDLTypeInfo *)&ySDL_SDL_Real};
#ifndef XOPTSORT
XCONST struct xSortIdStruct ySrtR_z_sysincl_exp_2I_Ref_sysincl_exp_Real =
  {xSortEC xSymbTLink((xIdNode)0, (xIdNode)0),
  (xIdNode)&yPacR_z_sysincl_exp__sysincl_exp xIdNames("Ref_sysincl_exp_Real")
  XCOMMON_EXTRAS xFreF(0) xAssF(0) xEqF(0) xTestF(0),
  (xptrint)sizeof(z_sysincl_exp_2I_Ref_sysincl_exp_Real), xRef,
  &xSrtR_SDL_Real, (xSortIdNode)0, 0, 0, 0, 0
  xRaWF((tSDLTypeInfo *)&ySDL_z_sysincl_exp_2I_Ref_sysincl_exp_Real)
  XSRT_EXTRAS};
#endif

void * yMkAddr_z_sysincl_exp_2I_Ref_sysincl_exp_Real (z_sysincl_exp_2I_Ref_sysincl_exp_Real yMkValue, z_sysincl_exp_2I_Ref_sysincl_exp_Real * yMkResult)
{
  *yMkResult = yMkValue;
  return (void *)yMkResult;
}

/*************************************************************************
**                       SECTION Initialization                         **
*************************************************************************/
extern void yInit_sysincl_exp (void)
{
  static int IsCalled = 0;
  int  Temp;
  YINIT_TEMP_VARS
  if (IsCalled) return;
  IsCalled = 1;
  xInsertIdNode((xIdNode)&yPacR_z_sysincl_exp__sysincl_exp);
  yInit_ctypes();
#ifndef XOPTSORT
  xInsertIdNode((xIdNode)&ySrtR_z_sysincl_exp_1Q_CA_sysincl_exp_6_X_Octet);
#endif
#ifndef XOPTSORT
  xInsertIdNode((xIdNode)&ySrtR_z_sysincl_exp_1R_tagMACADDR);
#endif
#ifndef XOPTSTRUCT
  xInsertIdNode((xIdNode)&yVarR_z_sysincl_exp_1R7_ab);
#endif
#ifndef XOPTSORT
  xInsertIdNode((xIdNode)&ySrtR_z_sysincl_exp_1S_tagPKT);
#endif
#ifndef XOPTSTRUCT
  xInsertIdNode((xIdNode)&yVarR_z_sysincl_exp_1S13_da);
  xInsertIdNode((xIdNode)&yVarR_z_sysincl_exp_1S14_sa);
  xInsertIdNode((xIdNode)&yVarR_z_sysincl_exp_1S15_bssid);
  xInsertIdNode((xIdNode)&yVarR_z_sysincl_exp_1S16_ra);
  xInsertIdNode((xIdNode)&yVarR_z_sysincl_exp_1S17_ta);
  xInsertIdNode((xIdNode)&yVarR_z_sysincl_exp_1S18_nType);
  xInsertIdNode((xIdNode)&yVarR_z_sysincl_exp_1S19_nSubtype);
  xInsertIdNode((xIdNode)&yVarR_z_sysincl_exp_1S1A_nSize);
  xInsertIdNode((xIdNode)&yVarR_z_sysincl_exp_1S1B_nSeqNo);
  xInsertIdNode((xIdNode)&yVarR_z_sysincl_exp_1S1C_nFragNo);
  xInsertIdNode((xIdNode)&yVarR_z_sysincl_exp_1S1D_dDurat);
  xInsertIdNode((xIdNode)&yVarR_z_sysincl_exp_1S1E_nCRC32);
  xInsertIdNode((xIdNode)&yVarR_z_sysincl_exp_1S1F_bRetry);
  xInsertIdNode((xIdNode)&yVarR_z_sysincl_exp_1S1G_bMF);
  xInsertIdNode((xIdNode)&yVarR_z_sysincl_exp_1S1H_bValid);
  xInsertIdNode((xIdNode)&yVarR_z_sysincl_exp_1S1I_m_bHaveData);
  xInsertIdNode((xIdNode)&yVarR_z_sysincl_exp_1S1J_m_pData);
#endif
#ifndef XOPTSORT
  xInsertIdNode((xIdNode)&ySrtR_z_sysincl_exp_1T_Ref_sysincl_exp_Octet);
#endif
#ifndef XOPTSORT
  xInsertIdNode((xIdNode)&ySrtR_z_sysincl_exp_1U_tagFLATARRAY);
#endif
#ifndef XOPTSTRUCT
  xInsertIdNode((xIdNode)&yVarR_z_sysincl_exp_1U9_nSize);
  xInsertIdNode((xIdNode)&yVarR_z_sysincl_exp_1UA_pData);
#endif
#ifndef XOPTSORT
  xInsertIdNode((xIdNode)&ySrtR_z_sysincl_exp_1V_tagMACDUPLC);
#endif
#ifndef XOPTSTRUCT
  xInsertIdNode((xIdNode)&yVarR_z_sysincl_exp_1VD_nAccessNo);
  xInsertIdNode((xIdNode)&yVarR_z_sysincl_exp_1VE_tAddr2);
  xInsertIdNode((xIdNode)&yVarR_z_sysincl_exp_1VF_nSeqNo);
  xInsertIdNode((xIdNode)&yVarR_z_sysincl_exp_1VG_nFragNo);
#endif
#ifndef XOPTSORT
  xInsertIdNode((xIdNode)&ySrtR_z_sysincl_exp_1W_tagMAC_MIBCNTRS);
#endif
#ifndef XOPTSTRUCT
  xInsertIdNode((xIdNode)&yVarR_z_sysincl_exp_1W0T_TransmittedFragmentCount);
  xInsertIdNode((xIdNode)&yVarR_z_sysincl_exp_1W0U_MulticastTransmittedFrameCount);
  xInsertIdNode((xIdNode)&yVarR_z_sysincl_exp_1W0V_FailedCount);
  xInsertIdNode((xIdNode)&yVarR_z_sysincl_exp_1W0W_RetryCount);
  xInsertIdNode((xIdNode)&yVarR_z_sysincl_exp_1W0X_MultipleRetryCount);
  xInsertIdNode((xIdNode)&yVarR_z_sysincl_exp_1W0Y_RTSSuccessCount);
  xInsertIdNode((xIdNode)&yVarR_z_sysincl_exp_1W0Z_RTSFailureCount);
  xInsertIdNode((xIdNode)&yVarR_z_sysincl_exp_1W10_ACKFailureCount);
  xInsertIdNode((xIdNode)&yVarR_z_sysincl_exp_1W11_ReceivedFragmentCount);
  xInsertIdNode((xIdNode)&yVarR_z_sysincl_exp_1W12_MulticastReceivedFrameCount);
  xInsertIdNode((xIdNode)&yVarR_z_sysincl_exp_1W13_FCSErrorCount);
  xInsertIdNode((xIdNode)&yVarR_z_sysincl_exp_1W14_FrameDuplicateCount);
#endif
#ifndef XOPTSORT
  xInsertIdNode((xIdNode)&ySrtR_z_sysincl_exp_1X_CA_sysincl_exp_16_X_tagMACDUPLC);
#endif
#ifndef XOPTSORT
  xInsertIdNode((xIdNode)&ySrtR_z_sysincl_exp_1Y_tagMAC_ST);
#endif
#ifndef XOPTSTRUCT
  xInsertIdNode((xIdNode)&yVarR_z_sysincl_exp_1Y11_bVCFree);
  xInsertIdNode((xIdNode)&yVarR_z_sysincl_exp_1Y12_nCW);
  xInsertIdNode((xIdNode)&yVarR_z_sysincl_exp_1Y13_nCurSeqNo);
  xInsertIdNode((xIdNode)&yVarR_z_sysincl_exp_1Y14_nSSRC);
  xInsertIdNode((xIdNode)&yVarR_z_sysincl_exp_1Y15_nSLRC);
  xInsertIdNode((xIdNode)&yVarR_z_sysincl_exp_1Y16_nFrags);
  xInsertIdNode((xIdNode)&yVarR_z_sysincl_exp_1Y17_nCurFrag);
  xInsertIdNode((xIdNode)&yVarR_z_sysincl_exp_1Y18_MIBC);
  xInsertIdNode((xIdNode)&yVarR_z_sysincl_exp_1Y19_pktCTRL);
  xInsertIdNode((xIdNode)&yVarR_z_sysincl_exp_1Y1A_pktRTS);
  xInsertIdNode((xIdNode)&yVarR_z_sysincl_exp_1Y1B_pktTx);
  xInsertIdNode((xIdNode)&yVarR_z_sysincl_exp_1Y1C_pktRx);
  xInsertIdNode((xIdNode)&yVarR_z_sysincl_exp_1Y1D_pktTxFr);
  xInsertIdNode((xIdNode)&yVarR_z_sysincl_exp_1Y1E_m_nCacheAccessNo);
  xInsertIdNode((xIdNode)&yVarR_z_sysincl_exp_1Y1F_m_nCacheSize);
  xInsertIdNode((xIdNode)&yVarR_z_sysincl_exp_1Y1G_m_pDC);
#endif
#ifndef XOPTSORT
  xInsertIdNode((xIdNode)&ySrtR_z_sysincl_exp_1Z_CA_sysincl_exp_4096_X_Octet);
#endif
#ifndef XOPTSORT
  xInsertIdNode((xIdNode)&ySrtR_z_sysincl_exp_20_tagFLDPSDU);
#endif
#ifndef XOPTSTRUCT
  xInsertIdNode((xIdNode)&yVarR_z_sysincl_exp_209_m_nSize);
  xInsertIdNode((xIdNode)&yVarR_z_sysincl_exp_20A_m_pData);
#endif
#ifndef XOPTSORT
  xInsertIdNode((xIdNode)&ySrtR_z_sysincl_exp_21_tagSIGNAL);
#endif
#ifndef XOPTSTRUCT
  xInsertIdNode((xIdNode)&yVarR_z_sysincl_exp_21F_nRate);
  xInsertIdNode((xIdNode)&yVarR_z_sysincl_exp_21G_nR);
  xInsertIdNode((xIdNode)&yVarR_z_sysincl_exp_21H_nLen);
  xInsertIdNode((xIdNode)&yVarR_z_sysincl_exp_21I_nParity);
  xInsertIdNode((xIdNode)&yVarR_z_sysincl_exp_21J_nTail);
#endif
#ifndef XOPTSORT
  xInsertIdNode((xIdNode)&ySrtR_z_sysincl_exp_22_CA_sysincl_exp_216_X_Octet);
#endif
#ifndef XOPTSORT
  xInsertIdNode((xIdNode)&ySrtR_z_sysincl_exp_23_tagBITSEQ);
#endif
#ifndef XOPTSTRUCT
  xInsertIdNode((xIdNode)&yVarR_z_sysincl_exp_239_m_nSize);
  xInsertIdNode((xIdNode)&yVarR_z_sysincl_exp_23A_m_pData);
#endif
#ifndef XOPTSORT
  xInsertIdNode((xIdNode)&ySrtR_z_sysincl_exp_24_tagCMPLX);
#endif
#ifndef XOPTSTRUCT
  xInsertIdNode((xIdNode)&yVarR_z_sysincl_exp_249_R);
  xInsertIdNode((xIdNode)&yVarR_z_sysincl_exp_24A_I);
#endif
#ifndef XOPTSORT
  xInsertIdNode((xIdNode)&ySrtR_z_sysincl_exp_25_CA_sysincl_exp_80_X_tagCMPLX);
#endif
#ifndef XOPTSORT
  xInsertIdNode((xIdNode)&ySrtR_z_sysincl_exp_26_tagSYMBOL);
#endif
#ifndef XOPTSTRUCT
  xInsertIdNode((xIdNode)&yVarR_z_sysincl_exp_267_m_pData);
#endif
#ifndef XOPTSORT
  xInsertIdNode((xIdNode)&ySrtR_z_sysincl_exp_27_CA_sysincl_exp_20_X_tagCMPLX);
#endif
#ifndef XOPTSORT
  xInsertIdNode((xIdNode)&ySrtR_z_sysincl_exp_28_tagMDM_SAMPLES);
#endif
#ifndef XOPTSTRUCT
  xInsertIdNode((xIdNode)&yVarR_z_sysincl_exp_287_m_pData);
#endif
#ifndef XOPTSORT
  xInsertIdNode((xIdNode)&ySrtR_z_sysincl_exp_29_Ref_sysincl_exp_Integer);
#endif
#ifndef XOPTSORT
  xInsertIdNode((xIdNode)&ySrtR_z_sysincl_exp_2A_Ref_sysincl_exp_tagMAC_ST);
#endif
#ifndef XOPTSORT
  xInsertIdNode((xIdNode)&ySrtR_z_sysincl_exp_2B_Ref_sysincl_exp_tagMACADDR);
#endif
#ifndef XOPTSORT
  xInsertIdNode((xIdNode)&ySrtR_z_sysincl_exp_2C_Ref_sysincl_exp_tagFLATARRAY);
#endif
#ifndef XOPTSORT
  xInsertIdNode((xIdNode)&ySrtR_z_sysincl_exp_2D_Ref_sysincl_exp_tagFLDPSDU);
#endif
#ifndef XOPTSORT
  xInsertIdNode((xIdNode)&ySrtR_z_sysincl_exp_2E_Ref_sysincl_exp_tagBITSEQ);
#endif
#ifndef XOPTSORT
  xInsertIdNode((xIdNode)&ySrtR_z_sysincl_exp_2F_Ref_sysincl_exp_tagSIGNAL);
#endif
#ifndef XOPTSORT
  xInsertIdNode((xIdNode)&ySrtR_z_sysincl_exp_2G_Ref_sysincl_exp_tagSYMBOL);
#endif
#ifndef XOPTSORT
  xInsertIdNode((xIdNode)&ySrtR_z_sysincl_exp_2H_Ref_sysincl_exp_tagMDM_SAMPLES);
#endif
#ifndef XOPTSORT
  xInsertIdNode((xIdNode)&ySrtR_z_sysincl_exp_2I_Ref_sysincl_exp_Real);
#endif
#ifndef XOPTSORT
  xInsertIdNode((xIdNode)&ySrtR_z_sysincl_exp_2J_PSDU);
#endif
#ifndef XOPTSORT
  xInsertIdNode((xIdNode)&ySrtR_z_sysincl_exp_2K_HDR);
#endif
#ifndef XOPTSORT
  xInsertIdNode((xIdNode)&ySrtR_z_sysincl_exp_2L_BITSEQ);
#endif
#ifndef XOPTSORT
  xInsertIdNode((xIdNode)&ySrtR_z_sysincl_exp_2M_SYMB);
#endif
#ifndef XOPTSORT
  xInsertIdNode((xIdNode)&ySrtR_z_sysincl_exp_2N_SMPLS);
#endif
}
