
/* Program generated by Cadvanced 4.3.0  */
#define XSCT_CADVANCED

#ifndef XX_sysincl_exp_H
#define XX_sysincl_exp_H
#include "C:\Kolevatov\Projects\SDL\STACK80211\sysincl_exp.h"

/*************************************************************************
**                SECTION Types and Forward references                  **
*************************************************************************/

/*****
* PACKAGE sysincl_exp
* #SDTREF(TEXT,C:\Kolevatov\Projects\SDL\STACK80211\sysincl_exp.h,4,9)
******/
extern XCONST struct xPackageIdStruct yPacR_z_sysincl_exp__sysincl_exp;

extern void yInit_sysincl_exp (void);
                /* #SDTREF(TEXT,C:\Kolevatov\Projects\SDL\STACK80211\sysincl_exp.h,4) */
#define H2SDL_USCR(ident) ident


/*****
* NEWTYPE CA_sysincl_exp_6_X_Octet  (TYPE section)
* <<PACKAGE sysincl_exp>>
* #SDTREF(TEXT,C:\\Kolevatov\\Projects\\SDL\\STACK80211\\procpkt_exp.h,61)
******/
extern tSDLArrayInfo ySDL_z_sysincl_exp_1Q_CA_sysincl_exp_6_X_Octet;
typedef SDL_Octet z_sysincl_exp_1Q_CA_sysincl_exp_6_X_Octet[SDL_INTEGER_LIT(6)];

/*****
* NEWTYPE tagMACADDR  (TYPE section)
* <<PACKAGE sysincl_exp>>
* #SDTREF(TEXT,C:\\Kolevatov\\Projects\\SDL\\STACK80211\\procpkt_exp.h,61)
******/
extern tSDLStructInfo ySDL_z_sysincl_exp_1R_tagMACADDR;
/*
typedef struct z_sysincl_exp_1R_tagMACADDR_s {
    z_sysincl_exp_1Q_CA_sysincl_exp_6_X_Octet  ab;
} z_sysincl_exp_1R_tagMACADDR;
*/
#define z_sysincl_exp_1R_tagMACADDR tagMACADDR

/*****
* NEWTYPE tagPKT  (TYPE section)
* <<PACKAGE sysincl_exp>>
* #SDTREF(TEXT,C:\\Kolevatov\\Projects\\SDL\\STACK80211\\procpkt_exp.h,68)
******/
extern tSDLStructInfo ySDL_z_sysincl_exp_1S_tagPKT;
/*
typedef struct z_sysincl_exp_1S_tagPKT_s {
    z_sysincl_exp_1R_tagMACADDR  da;
    z_sysincl_exp_1R_tagMACADDR  sa;
    z_sysincl_exp_1R_tagMACADDR  bssid;
    z_sysincl_exp_1R_tagMACADDR  ra;
    z_sysincl_exp_1R_tagMACADDR  ta;
    SDL_Integer  nType;
    SDL_Integer  nSubtype;
    SDL_Integer  nSize;
    SDL_Integer  nSeqNo;
    SDL_Integer  nFragNo;
    SDL_Real  dDurat;
    SDL_Integer  nCRC32;
    SDL_Integer  bRetry;
    SDL_Integer  bMF;
    SDL_Integer  bValid;
    SDL_Integer  m_bHaveData;
    z_ctypes_3_Charstar  m_pData;
} z_sysincl_exp_1S_tagPKT;
*/
#define z_sysincl_exp_1S_tagPKT tagPKT

/*****
* NEWTYPE Ref_sysincl_exp_Octet  (TYPE section)
* <<PACKAGE sysincl_exp>>
* #SDTREF(TEXT,C:\\Kolevatov\\Projects\\SDL\\STACK80211\\proc_mac_exp.h,33)
******/
extern tSDLGenInfo ySDL_z_sysincl_exp_1T_Ref_sysincl_exp_Octet;
typedef SDL_Octet *z_sysincl_exp_1T_Ref_sysincl_exp_Octet;

/*****
* NEWTYPE tagFLATARRAY  (TYPE section)
* <<PACKAGE sysincl_exp>>
* #SDTREF(TEXT,C:\\Kolevatov\\Projects\\SDL\\STACK80211\\proc_mac_exp.h,33)
******/
extern tSDLStructInfo ySDL_z_sysincl_exp_1U_tagFLATARRAY;
/*
typedef struct z_sysincl_exp_1U_tagFLATARRAY_s {
    SDL_Integer  nSize;
    z_sysincl_exp_1T_Ref_sysincl_exp_Octet  pData;
} z_sysincl_exp_1U_tagFLATARRAY;
*/
#define z_sysincl_exp_1U_tagFLATARRAY tagFLATARRAY

/*****
* NEWTYPE tagMACDUPLC  (TYPE section)
* <<PACKAGE sysincl_exp>>
* #SDTREF(TEXT,C:\\Kolevatov\\Projects\\SDL\\STACK80211\\proc_mac_exp.h,41)
******/
extern tSDLStructInfo ySDL_z_sysincl_exp_1V_tagMACDUPLC;
/*
typedef struct z_sysincl_exp_1V_tagMACDUPLC_s {
    SDL_Integer  nAccessNo;
    z_sysincl_exp_1R_tagMACADDR  tAddr2;
    SDL_Integer  nSeqNo;
    SDL_Integer  nFragNo;
} z_sysincl_exp_1V_tagMACDUPLC;
*/
#define z_sysincl_exp_1V_tagMACDUPLC tagMACDUPLC

/*****
* NEWTYPE tagMAC_MIBCNTRS  (TYPE section)
* <<PACKAGE sysincl_exp>>
* #SDTREF(TEXT,C:\\Kolevatov\\Projects\\SDL\\STACK80211\\proc_mac_exp.h,50)
******/
extern tSDLStructInfo ySDL_z_sysincl_exp_1W_tagMAC_MIBCNTRS;
/*
typedef struct z_sysincl_exp_1W_tagMAC_MIBCNTRS_s {
    SDL_Integer  TransmittedFragmentCount;
    SDL_Integer  MulticastTransmittedFrameCount;
    SDL_Integer  FailedCount;
    SDL_Integer  RetryCount;
    SDL_Integer  MultipleRetryCount;
    SDL_Integer  RTSSuccessCount;
    SDL_Integer  RTSFailureCount;
    SDL_Integer  ACKFailureCount;
    SDL_Integer  ReceivedFragmentCount;
    SDL_Integer  MulticastReceivedFrameCount;
    SDL_Integer  FCSErrorCount;
    SDL_Integer  FrameDuplicateCount;
} z_sysincl_exp_1W_tagMAC_MIBCNTRS;
*/
#define z_sysincl_exp_1W_tagMAC_MIBCNTRS tagMAC_MIBCNTRS

/*****
* NEWTYPE CA_sysincl_exp_16_X_tagMACDUPLC  (TYPE section)
* <<PACKAGE sysincl_exp>>
* #SDTREF(TEXT,C:\\Kolevatov\\Projects\\SDL\\STACK80211\\proc_mac_exp.h,68)
******/
extern tSDLArrayInfo ySDL_z_sysincl_exp_1X_CA_sysincl_exp_16_X_tagMACDUPLC;
typedef z_sysincl_exp_1V_tagMACDUPLC z_sysincl_exp_1X_CA_sysincl_exp_16_X_tagMACDUPLC[SDL_INTEGER_LIT(16)];

/*****
* NEWTYPE tagMAC_ST  (TYPE section)
* <<PACKAGE sysincl_exp>>
* #SDTREF(TEXT,C:\\Kolevatov\\Projects\\SDL\\STACK80211\\proc_mac_exp.h,68)
******/
extern tSDLStructInfo ySDL_z_sysincl_exp_1Y_tagMAC_ST;
/*
typedef struct z_sysincl_exp_1Y_tagMAC_ST_s {
    SDL_Integer  bVCFree;
    SDL_Integer  nCW;
    SDL_Integer  nCurSeqNo;
    SDL_Integer  nSSRC;
    SDL_Integer  nSLRC;
    SDL_Integer  nFrags;
    SDL_Integer  nCurFrag;
    z_sysincl_exp_1W_tagMAC_MIBCNTRS  MIBC;
    z_sysincl_exp_1S_tagPKT  pktCTRL;
    z_sysincl_exp_1S_tagPKT  pktRTS;
    z_sysincl_exp_1S_tagPKT  pktTx;
    z_sysincl_exp_1S_tagPKT  pktRx;
    z_sysincl_exp_1S_tagPKT  pktTxFr;
    SDL_Integer  m_nCacheAccessNo;
    SDL_Integer  m_nCacheSize;
    z_sysincl_exp_1X_CA_sysincl_exp_16_X_tagMACDUPLC  m_pDC;
} z_sysincl_exp_1Y_tagMAC_ST;
*/
#define z_sysincl_exp_1Y_tagMAC_ST tagMAC_ST

/*****
* NEWTYPE CA_sysincl_exp_4096_X_Octet  (TYPE section)
* <<PACKAGE sysincl_exp>>
* #SDTREF(TEXT,C:\\Kolevatov\\Projects\\SDL\\STACK80211\\proc_phyctrl_exp.h,32)
******/
extern tSDLArrayInfo ySDL_z_sysincl_exp_1Z_CA_sysincl_exp_4096_X_Octet;
typedef SDL_Octet z_sysincl_exp_1Z_CA_sysincl_exp_4096_X_Octet[SDL_INTEGER_LIT(4096)];

/*****
* NEWTYPE tagFLDPSDU  (TYPE section)
* <<PACKAGE sysincl_exp>>
* #SDTREF(TEXT,C:\\Kolevatov\\Projects\\SDL\\STACK80211\\proc_phyctrl_exp.h,32)
******/
extern tSDLStructInfo ySDL_z_sysincl_exp_20_tagFLDPSDU;
/*
typedef struct z_sysincl_exp_20_tagFLDPSDU_s {
    SDL_Integer  m_nSize;
    z_sysincl_exp_1Z_CA_sysincl_exp_4096_X_Octet  m_pData;
} z_sysincl_exp_20_tagFLDPSDU;
*/
#define z_sysincl_exp_20_tagFLDPSDU tagFLDPSDU

/*****
* NEWTYPE tagSIGNAL  (TYPE section)
* <<PACKAGE sysincl_exp>>
* #SDTREF(TEXT,C:\\Kolevatov\\Projects\\SDL\\STACK80211\\proc_phyctrl_exp.h,40)
******/
extern tSDLStructInfo ySDL_z_sysincl_exp_21_tagSIGNAL;
/*
typedef struct z_sysincl_exp_21_tagSIGNAL_s {
    z_ctypes_9_UnsignedInt  nRate : SDL_INTEGER_LIT(4);
    z_ctypes_9_UnsignedInt  nR : SDL_INTEGER_LIT(1);
    z_ctypes_9_UnsignedInt  nLen : SDL_INTEGER_LIT(12);
    z_ctypes_9_UnsignedInt  nParity : SDL_INTEGER_LIT(1);
    z_ctypes_9_UnsignedInt  nTail : SDL_INTEGER_LIT(6);
} z_sysincl_exp_21_tagSIGNAL;
*/
#define z_sysincl_exp_21_tagSIGNAL tagSIGNAL

/*****
* NEWTYPE CA_sysincl_exp_216_X_Octet  (TYPE section)
* <<PACKAGE sysincl_exp>>
* #SDTREF(TEXT,C:\\Kolevatov\\Projects\\SDL\\STACK80211\\proc_phyctrl_exp.h,51)
******/
extern tSDLArrayInfo ySDL_z_sysincl_exp_22_CA_sysincl_exp_216_X_Octet;
typedef SDL_Octet z_sysincl_exp_22_CA_sysincl_exp_216_X_Octet[SDL_INTEGER_LIT(216)];

/*****
* NEWTYPE tagBITSEQ  (TYPE section)
* <<PACKAGE sysincl_exp>>
* #SDTREF(TEXT,C:\\Kolevatov\\Projects\\SDL\\STACK80211\\proc_phyctrl_exp.h,51)
******/
extern tSDLStructInfo ySDL_z_sysincl_exp_23_tagBITSEQ;
/*
typedef struct z_sysincl_exp_23_tagBITSEQ_s {
    SDL_Integer  m_nSize;
    z_sysincl_exp_22_CA_sysincl_exp_216_X_Octet  m_pData;
} z_sysincl_exp_23_tagBITSEQ;
*/
#define z_sysincl_exp_23_tagBITSEQ tagBITSEQ

/*****
* SYNTYPE PSDU  (TYPE section)
* <<PACKAGE sysincl_exp>>
* #SDTREF(TEXT,C:\\Kolevatov\\Projects\\SDL\\STACK80211\\proc_phyctrl_exp.h,57)
******/
extern tSDLGenInfo ySDL_z_sysincl_exp_2J_PSDU;
/*
typedef z_sysincl_exp_20_tagFLDPSDU  z_sysincl_exp_2J_PSDU;
*/
#define z_sysincl_exp_2J_PSDU PSDU

/*****
* SYNTYPE HDR  (TYPE section)
* <<PACKAGE sysincl_exp>>
* #SDTREF(TEXT,C:\\Kolevatov\\Projects\\SDL\\STACK80211\\proc_phyctrl_exp.h,58)
******/
extern tSDLGenInfo ySDL_z_sysincl_exp_2K_HDR;
/*
typedef z_sysincl_exp_21_tagSIGNAL  z_sysincl_exp_2K_HDR;
*/
#define z_sysincl_exp_2K_HDR HDR

/*****
* SYNTYPE BITSEQ  (TYPE section)
* <<PACKAGE sysincl_exp>>
* #SDTREF(TEXT,C:\\Kolevatov\\Projects\\SDL\\STACK80211\\proc_phyctrl_exp.h,59)
******/
extern tSDLGenInfo ySDL_z_sysincl_exp_2L_BITSEQ;
/*
typedef z_sysincl_exp_23_tagBITSEQ  z_sysincl_exp_2L_BITSEQ;
*/
#define z_sysincl_exp_2L_BITSEQ BITSEQ

/*****
* NEWTYPE tagCMPLX  (TYPE section)
* <<PACKAGE sysincl_exp>>
* #SDTREF(TEXT,C:\\Kolevatov\\Projects\\SDL\\STACK80211\\proc_phy_exp.h,17)
******/
extern tSDLStructInfo ySDL_z_sysincl_exp_24_tagCMPLX;
/*
typedef struct z_sysincl_exp_24_tagCMPLX_s {
    SDL_Real  R;
    SDL_Real  I;
} z_sysincl_exp_24_tagCMPLX;
*/
#define z_sysincl_exp_24_tagCMPLX tagCMPLX

/*****
* NEWTYPE CA_sysincl_exp_80_X_tagCMPLX  (TYPE section)
* <<PACKAGE sysincl_exp>>
* #SDTREF(TEXT,C:\\Kolevatov\\Projects\\SDL\\STACK80211\\proc_phy_exp.h,24)
******/
extern tSDLArrayInfo ySDL_z_sysincl_exp_25_CA_sysincl_exp_80_X_tagCMPLX;
typedef z_sysincl_exp_24_tagCMPLX z_sysincl_exp_25_CA_sysincl_exp_80_X_tagCMPLX[SDL_INTEGER_LIT(80)];

/*****
* NEWTYPE tagSYMBOL  (TYPE section)
* <<PACKAGE sysincl_exp>>
* #SDTREF(TEXT,C:\\Kolevatov\\Projects\\SDL\\STACK80211\\proc_phy_exp.h,24)
******/
extern tSDLStructInfo ySDL_z_sysincl_exp_26_tagSYMBOL;
/*
typedef struct z_sysincl_exp_26_tagSYMBOL_s {
    z_sysincl_exp_25_CA_sysincl_exp_80_X_tagCMPLX  m_pData;
} z_sysincl_exp_26_tagSYMBOL;
*/
#define z_sysincl_exp_26_tagSYMBOL tagSYMBOL

/*****
* NEWTYPE CA_sysincl_exp_20_X_tagCMPLX  (TYPE section)
* <<PACKAGE sysincl_exp>>
* #SDTREF(TEXT,C:\\Kolevatov\\Projects\\SDL\\STACK80211\\proc_phy_exp.h,31)
******/
extern tSDLArrayInfo ySDL_z_sysincl_exp_27_CA_sysincl_exp_20_X_tagCMPLX;
typedef z_sysincl_exp_24_tagCMPLX z_sysincl_exp_27_CA_sysincl_exp_20_X_tagCMPLX[SDL_INTEGER_LIT(20)];

/*****
* NEWTYPE tagMDM_SAMPLES  (TYPE section)
* <<PACKAGE sysincl_exp>>
* #SDTREF(TEXT,C:\\Kolevatov\\Projects\\SDL\\STACK80211\\proc_phy_exp.h,31)
******/
extern tSDLStructInfo ySDL_z_sysincl_exp_28_tagMDM_SAMPLES;
/*
typedef struct z_sysincl_exp_28_tagMDM_SAMPLES_s {
    z_sysincl_exp_27_CA_sysincl_exp_20_X_tagCMPLX  m_pData;
} z_sysincl_exp_28_tagMDM_SAMPLES;
*/
#define z_sysincl_exp_28_tagMDM_SAMPLES tagMDM_SAMPLES

/*****
* SYNTYPE SYMB  (TYPE section)
* <<PACKAGE sysincl_exp>>
* #SDTREF(TEXT,C:\\Kolevatov\\Projects\\SDL\\STACK80211\\proc_phy_exp.h,36)
******/
extern tSDLGenInfo ySDL_z_sysincl_exp_2M_SYMB;
/*
typedef z_sysincl_exp_26_tagSYMBOL  z_sysincl_exp_2M_SYMB;
*/
#define z_sysincl_exp_2M_SYMB SYMB

/*****
* SYNTYPE SMPLS  (TYPE section)
* <<PACKAGE sysincl_exp>>
* #SDTREF(TEXT,C:\\Kolevatov\\Projects\\SDL\\STACK80211\\proc_phy_exp.h,37)
******/
extern tSDLGenInfo ySDL_z_sysincl_exp_2N_SMPLS;
/*
typedef z_sysincl_exp_28_tagMDM_SAMPLES  z_sysincl_exp_2N_SMPLS;
*/
#define z_sysincl_exp_2N_SMPLS SMPLS

/*****
* NEWTYPE Ref_sysincl_exp_Integer  (TYPE section)
* <<PACKAGE sysincl_exp>>
* #SDTREF(TEXT,C:\\Kolevatov\\Projects\\SDL\\STACK80211\\export_sdl_exp.h,33)
******/
extern tSDLGenInfo ySDL_z_sysincl_exp_29_Ref_sysincl_exp_Integer;
typedef SDL_Integer *z_sysincl_exp_29_Ref_sysincl_exp_Integer;

/*****
* NEWTYPE Ref_sysincl_exp_tagMAC_ST  (TYPE section)
* <<PACKAGE sysincl_exp>>
* #SDTREF(TEXT,C:\\Kolevatov\\Projects\\SDL\\STACK80211\\export_sdl_exp.h,38)
******/
extern tSDLGenInfo ySDL_z_sysincl_exp_2A_Ref_sysincl_exp_tagMAC_ST;
/*
typedef struct z_sysincl_exp_1Y_tagMAC_ST_s *z_sysincl_exp_2A_Ref_sysincl_exp_tagMAC_ST;
*/
#define z_sysincl_exp_2A_Ref_sysincl_exp_tagMAC_ST Ref_sysincl_exp_tagMAC_ST
                /* #SDTREF(TEXT,C:\\Kolevatov\\Projects\\SDL\\STACK80211\\export_sdl_exp.h,38) */
typedef z_sysincl_exp_1Y_tagMAC_ST *z_sysincl_exp_2A_Ref_sysincl_exp_tagMAC_ST;


/*****
* NEWTYPE Ref_sysincl_exp_tagMACADDR  (TYPE section)
* <<PACKAGE sysincl_exp>>
* #SDTREF(TEXT,C:\\Kolevatov\\Projects\\SDL\\STACK80211\\export_sdl_exp.h,44)
******/
extern tSDLGenInfo ySDL_z_sysincl_exp_2B_Ref_sysincl_exp_tagMACADDR;
/*
typedef struct z_sysincl_exp_1R_tagMACADDR_s *z_sysincl_exp_2B_Ref_sysincl_exp_tagMACADDR;
*/
#define z_sysincl_exp_2B_Ref_sysincl_exp_tagMACADDR Ref_sysincl_exp_tagMACADDR
                /* #SDTREF(TEXT,C:\\Kolevatov\\Projects\\SDL\\STACK80211\\export_sdl_exp.h,44) */
typedef z_sysincl_exp_1R_tagMACADDR *z_sysincl_exp_2B_Ref_sysincl_exp_tagMACADDR;


/*****
* NEWTYPE Ref_sysincl_exp_tagFLATARRAY  (TYPE section)
* <<PACKAGE sysincl_exp>>
* #SDTREF(TEXT,C:\\Kolevatov\\Projects\\SDL\\STACK80211\\export_sdl_exp.h,44)
******/
extern tSDLGenInfo ySDL_z_sysincl_exp_2C_Ref_sysincl_exp_tagFLATARRAY;
/*
typedef struct z_sysincl_exp_1U_tagFLATARRAY_s *z_sysincl_exp_2C_Ref_sysincl_exp_tagFLATARRAY;
*/
#define z_sysincl_exp_2C_Ref_sysincl_exp_tagFLATARRAY Ref_sysincl_exp_tagFLATARRAY
                /* #SDTREF(TEXT,C:\\Kolevatov\\Projects\\SDL\\STACK80211\\export_sdl_exp.h,44) */
typedef z_sysincl_exp_1U_tagFLATARRAY *z_sysincl_exp_2C_Ref_sysincl_exp_tagFLATARRAY;


/*****
* NEWTYPE Ref_sysincl_exp_tagFLDPSDU  (TYPE section)
* <<PACKAGE sysincl_exp>>
* #SDTREF(TEXT,C:\\Kolevatov\\Projects\\SDL\\STACK80211\\export_sdl_exp.h,45)
******/
extern tSDLGenInfo ySDL_z_sysincl_exp_2D_Ref_sysincl_exp_tagFLDPSDU;
/*
typedef struct z_sysincl_exp_20_tagFLDPSDU_s *z_sysincl_exp_2D_Ref_sysincl_exp_tagFLDPSDU;
*/
#define z_sysincl_exp_2D_Ref_sysincl_exp_tagFLDPSDU Ref_sysincl_exp_tagFLDPSDU
                /* #SDTREF(TEXT,C:\\Kolevatov\\Projects\\SDL\\STACK80211\\export_sdl_exp.h,45) */
typedef z_sysincl_exp_20_tagFLDPSDU *z_sysincl_exp_2D_Ref_sysincl_exp_tagFLDPSDU;


/*****
* NEWTYPE Ref_sysincl_exp_tagBITSEQ  (TYPE section)
* <<PACKAGE sysincl_exp>>
* #SDTREF(TEXT,C:\\Kolevatov\\Projects\\SDL\\STACK80211\\export_sdl_exp.h,71)
******/
extern tSDLGenInfo ySDL_z_sysincl_exp_2E_Ref_sysincl_exp_tagBITSEQ;
/*
typedef struct z_sysincl_exp_23_tagBITSEQ_s *z_sysincl_exp_2E_Ref_sysincl_exp_tagBITSEQ;
*/
#define z_sysincl_exp_2E_Ref_sysincl_exp_tagBITSEQ Ref_sysincl_exp_tagBITSEQ
                /* #SDTREF(TEXT,C:\\Kolevatov\\Projects\\SDL\\STACK80211\\export_sdl_exp.h,71) */
typedef z_sysincl_exp_23_tagBITSEQ *z_sysincl_exp_2E_Ref_sysincl_exp_tagBITSEQ;


/*****
* NEWTYPE Ref_sysincl_exp_tagSIGNAL  (TYPE section)
* <<PACKAGE sysincl_exp>>
* #SDTREF(TEXT,C:\\Kolevatov\\Projects\\SDL\\STACK80211\\export_sdl_exp.h,71)
******/
extern tSDLGenInfo ySDL_z_sysincl_exp_2F_Ref_sysincl_exp_tagSIGNAL;
/*
typedef struct z_sysincl_exp_21_tagSIGNAL_s *z_sysincl_exp_2F_Ref_sysincl_exp_tagSIGNAL;
*/
#define z_sysincl_exp_2F_Ref_sysincl_exp_tagSIGNAL Ref_sysincl_exp_tagSIGNAL
                /* #SDTREF(TEXT,C:\\Kolevatov\\Projects\\SDL\\STACK80211\\export_sdl_exp.h,71) */
typedef z_sysincl_exp_21_tagSIGNAL *z_sysincl_exp_2F_Ref_sysincl_exp_tagSIGNAL;


/*****
* NEWTYPE Ref_sysincl_exp_tagSYMBOL  (TYPE section)
* <<PACKAGE sysincl_exp>>
* #SDTREF(TEXT,C:\\Kolevatov\\Projects\\SDL\\STACK80211\\export_sdl_exp.h,75)
******/
extern tSDLGenInfo ySDL_z_sysincl_exp_2G_Ref_sysincl_exp_tagSYMBOL;
/*
typedef struct z_sysincl_exp_26_tagSYMBOL_s *z_sysincl_exp_2G_Ref_sysincl_exp_tagSYMBOL;
*/
#define z_sysincl_exp_2G_Ref_sysincl_exp_tagSYMBOL Ref_sysincl_exp_tagSYMBOL
                /* #SDTREF(TEXT,C:\\Kolevatov\\Projects\\SDL\\STACK80211\\export_sdl_exp.h,75) */
typedef z_sysincl_exp_26_tagSYMBOL *z_sysincl_exp_2G_Ref_sysincl_exp_tagSYMBOL;


/*****
* NEWTYPE Ref_sysincl_exp_tagMDM_SAMPLES  (TYPE section)
* <<PACKAGE sysincl_exp>>
* #SDTREF(TEXT,C:\\Kolevatov\\Projects\\SDL\\STACK80211\\export_sdl_exp.h,103)
******/
extern tSDLGenInfo ySDL_z_sysincl_exp_2H_Ref_sysincl_exp_tagMDM_SAMPLES;
/*
typedef struct z_sysincl_exp_28_tagMDM_SAMPLES_s *z_sysincl_exp_2H_Ref_sysincl_exp_tagMDM_SAMPLES;
*/
#define z_sysincl_exp_2H_Ref_sysincl_exp_tagMDM_SAMPLES Ref_sysincl_exp_tagMDM_SAMPLES
                /* #SDTREF(TEXT,C:\\Kolevatov\\Projects\\SDL\\STACK80211\\export_sdl_exp.h,103) */
typedef z_sysincl_exp_28_tagMDM_SAMPLES *z_sysincl_exp_2H_Ref_sysincl_exp_tagMDM_SAMPLES;


/*****
* NEWTYPE Ref_sysincl_exp_Real  (TYPE section)
* <<PACKAGE sysincl_exp>>
* #SDTREF(TEXT,C:\\Kolevatov\\Projects\\SDL\\STACK80211\\export_sdl_exp.h,109)
******/
extern tSDLGenInfo ySDL_z_sysincl_exp_2I_Ref_sysincl_exp_Real;
typedef SDL_Real *z_sysincl_exp_2I_Ref_sysincl_exp_Real;

/*****
* NEWTYPE CA_sysincl_exp_6_X_Octet  (HEADING section)
* <<PACKAGE sysincl_exp>>
* #SDTREF(TEXT,C:\\Kolevatov\\Projects\\SDL\\STACK80211\\procpkt_exp.h,61)
******/
#ifndef XOPTSORT
extern XCONST struct xSortIdStruct ySrtR_z_sysincl_exp_1Q_CA_sysincl_exp_6_X_Octet;
#define ySrtN_z_sysincl_exp_1Q_CA_sysincl_exp_6_X_Octet  (&ySrtR_z_sysincl_exp_1Q_CA_sysincl_exp_6_X_Octet)
#endif

#define yAss_z_sysincl_exp_1Q_CA_sysincl_exp_6_X_Octet(Addr,Expr,AssName) (void)GenericAssignSort(Addr,Expr,AssName,(tSDLTypeInfo *)&ySDL_z_sysincl_exp_1Q_CA_sysincl_exp_6_X_Octet)
#define yAssF_z_sysincl_exp_1Q_CA_sysincl_exp_6_X_Octet(V,E,A)  yAss_z_sysincl_exp_1Q_CA_sysincl_exp_6_X_Octet(V,E,A)
#define yEq_z_sysincl_exp_1Q_CA_sysincl_exp_6_X_Octet(Expr1,Expr2) GenericEqualSort((void *)Expr1,(void *)Expr2,(tSDLTypeInfo *)&ySDL_z_sysincl_exp_1Q_CA_sysincl_exp_6_X_Octet)
#define yEqF_z_sysincl_exp_1Q_CA_sysincl_exp_6_X_Octet(Expr1,Expr2)  yEq_z_sysincl_exp_1Q_CA_sysincl_exp_6_X_Octet(Expr1,Expr2)
#define yNEqF_z_sysincl_exp_1Q_CA_sysincl_exp_6_X_Octet(Expr1,Expr2)  ( ! yEq_z_sysincl_exp_1Q_CA_sysincl_exp_6_X_Octet(Expr1,Expr2) )
#ifdef XEINDEX
extern SDL_Integer yTstI_z_sysincl_exp_1Q_CA_sysincl_exp_6_X_Octet (
  SDL_Integer);
#else
#define yTstI_z_sysincl_exp_1Q_CA_sysincl_exp_6_X_Octet(yExpr)  yExpr
#endif
#ifndef ANY_z_sysincl_exp_1Q_CA_sysincl_exp_6_X_Octet
#define ANY_z_sysincl_exp_1Q_CA_sysincl_exp_6_X_Octet
#endif
#define z_sysincl_exp_1Q5_copy(P)  P

/*****
* NEWTYPE tagMACADDR  (HEADING section)
* <<PACKAGE sysincl_exp>>
* #SDTREF(TEXT,C:\\Kolevatov\\Projects\\SDL\\STACK80211\\procpkt_exp.h,61)
******/
#ifndef XOPTSORT
extern XCONST struct xSortIdStruct ySrtR_z_sysincl_exp_1R_tagMACADDR;
#define ySrtN_z_sysincl_exp_1R_tagMACADDR  (&ySrtR_z_sysincl_exp_1R_tagMACADDR)
#endif

#define yAss_z_sysincl_exp_1R_tagMACADDR(Addr,Expr,AssName) (void)GenericAssignSort(Addr,Expr,AssName,(tSDLTypeInfo *)&ySDL_z_sysincl_exp_1R_tagMACADDR)
#define yAssF_z_sysincl_exp_1R_tagMACADDR(V,E,A)  yAss_z_sysincl_exp_1R_tagMACADDR(&(V),E,A)
#define yEq_z_sysincl_exp_1R_tagMACADDR(Expr1,Expr2) GenericEqualSort((void *)Expr1,(void *)Expr2,(tSDLTypeInfo *)&ySDL_z_sysincl_exp_1R_tagMACADDR)
#define yEqF_z_sysincl_exp_1R_tagMACADDR(Expr1,Expr2)  yEq_z_sysincl_exp_1R_tagMACADDR(Expr1,Expr2)
#define yNEqF_z_sysincl_exp_1R_tagMACADDR(Expr1,Expr2)  ( ! yEq_z_sysincl_exp_1R_tagMACADDR(Expr1,Expr2) )
#ifndef ANY_z_sysincl_exp_1R_tagMACADDR
#define ANY_z_sysincl_exp_1R_tagMACADDR(R) (z_sysincl_exp_1R_tagMACADDR *)GenericAnySort(R, (tSDLTypeInfo *)&ySDL_z_sysincl_exp_1R_tagMACADDR)
#endif
#define z_sysincl_exp_1R3_copy(P)  P

/*****
* NEWTYPE tagPKT  (HEADING section)
* <<PACKAGE sysincl_exp>>
* #SDTREF(TEXT,C:\\Kolevatov\\Projects\\SDL\\STACK80211\\procpkt_exp.h,68)
******/
#ifndef XOPTSORT
extern XCONST struct xSortIdStruct ySrtR_z_sysincl_exp_1S_tagPKT;
#define ySrtN_z_sysincl_exp_1S_tagPKT  (&ySrtR_z_sysincl_exp_1S_tagPKT)
#endif

#define yAss_z_sysincl_exp_1S_tagPKT(Addr,Expr,AssName) (void)GenericAssignSort(Addr,Expr,AssName,(tSDLTypeInfo *)&ySDL_z_sysincl_exp_1S_tagPKT)
#define yAssF_z_sysincl_exp_1S_tagPKT(V,E,A)  yAss_z_sysincl_exp_1S_tagPKT(&(V),E,A)
#define yEq_z_sysincl_exp_1S_tagPKT(Expr1,Expr2) GenericEqualSort((void *)Expr1,(void *)Expr2,(tSDLTypeInfo *)&ySDL_z_sysincl_exp_1S_tagPKT)
#define yEqF_z_sysincl_exp_1S_tagPKT(Expr1,Expr2)  yEq_z_sysincl_exp_1S_tagPKT(Expr1,Expr2)
#define yNEqF_z_sysincl_exp_1S_tagPKT(Expr1,Expr2)  ( ! yEq_z_sysincl_exp_1S_tagPKT(Expr1,Expr2) )
#ifndef ANY_z_sysincl_exp_1S_tagPKT
#define ANY_z_sysincl_exp_1S_tagPKT(R) (z_sysincl_exp_1S_tagPKT *)GenericAnySort(R, (tSDLTypeInfo *)&ySDL_z_sysincl_exp_1S_tagPKT)
#endif
#define z_sysincl_exp_1S03_copy(P)  P

/*****
* NEWTYPE Ref_sysincl_exp_Octet  (HEADING section)
* <<PACKAGE sysincl_exp>>
* #SDTREF(TEXT,C:\\Kolevatov\\Projects\\SDL\\STACK80211\\proc_mac_exp.h,33)
******/
#ifndef XOPTSORT
extern XCONST struct xSortIdStruct ySrtR_z_sysincl_exp_1T_Ref_sysincl_exp_Octet;
#define ySrtN_z_sysincl_exp_1T_Ref_sysincl_exp_Octet  (&ySrtR_z_sysincl_exp_1T_Ref_sysincl_exp_Octet)
#endif

#define yAssF_z_sysincl_exp_1T_Ref_sysincl_exp_Octet(V,E,A)  V = E
#define yEqF_z_sysincl_exp_1T_Ref_sysincl_exp_Octet(Expr1,Expr2)  (Expr1) == (Expr2)
#define yNEqF_z_sysincl_exp_1T_Ref_sysincl_exp_Octet(Expr1,Expr2)  (Expr1) != (Expr2)
extern void * yMkAddr_z_sysincl_exp_1T_Ref_sysincl_exp_Octet (z_sysincl_exp_1T_Ref_sysincl_exp_Octet, z_sysincl_exp_1T_Ref_sysincl_exp_Octet *);
#ifndef ANY_z_sysincl_exp_1T_Ref_sysincl_exp_Octet
#define ANY_z_sysincl_exp_1T_Ref_sysincl_exp_Octet 0
#endif
#define z_sysincl_exp_1TF_copy(P)  P
#ifdef XVALIDATOR_LIB
#define yAll_z_sysincl_exp_1T_Ref_sysincl_exp_Octet() (z_sysincl_exp_1T_Ref_sysincl_exp_Octet)XALLOC_REF_VAL(sizeof(SDL_Octet), ySrtN_z_sysincl_exp_1T_Ref_sysincl_exp_Octet)
#else
#define yAll_z_sysincl_exp_1T_Ref_sysincl_exp_Octet() (z_sysincl_exp_1T_Ref_sysincl_exp_Octet)XALLOC(sizeof(SDL_Octet), \
  (tSDLTypeInfo *)&ySDL_z_sysincl_exp_1T_Ref_sysincl_exp_Octet)
#endif
#define yPlus_z_sysincl_exp_1T_Ref_sysincl_exp_Octet(P1,P2) (P1+P2)
#define yMinus_z_sysincl_exp_1T_Ref_sysincl_exp_Octet(P1,P2) (P1-P2)
#define z_sysincl_exp_1T0_Null() 0
#define z_sysincl_exp_1T1_Alloc() yAll_z_sysincl_exp_1T_Ref_sysincl_exp_Octet()
#ifdef XVALIDATOR_LIB
#define z_sysincl_exp_1T6_free(P) XFREE_REF_VAL((void **)(P), sizeof(SDL_Octet))
#else
#define z_sysincl_exp_1T6_free(P) XFREE((void **)(P), sizeof(SDL_Octet))
#endif
#define z_sysincl_exp_1T9_ref2vstar(P) (z_ctypes_4_Voidstar)(P)
#define z_sysincl_exp_1TA_vstar2ref(P) (z_ctypes_4_Voidstar)(P)
#define z_sysincl_exp_1TB_ref2vstarstar(P) (z_ctypes_5_Voidstarstar)(P)

/*****
* NEWTYPE tagFLATARRAY  (HEADING section)
* <<PACKAGE sysincl_exp>>
* #SDTREF(TEXT,C:\\Kolevatov\\Projects\\SDL\\STACK80211\\proc_mac_exp.h,33)
******/
#ifndef XOPTSORT
extern XCONST struct xSortIdStruct ySrtR_z_sysincl_exp_1U_tagFLATARRAY;
#define ySrtN_z_sysincl_exp_1U_tagFLATARRAY  (&ySrtR_z_sysincl_exp_1U_tagFLATARRAY)
#endif

#define yAssF_z_sysincl_exp_1U_tagFLATARRAY(V,E,A)  V = *(z_sysincl_exp_1U_tagFLATARRAY *)(E)
#define yEq_z_sysincl_exp_1U_tagFLATARRAY(Expr1,Expr2) GenericEqualSort((void *)Expr1,(void *)Expr2,(tSDLTypeInfo *)&ySDL_z_sysincl_exp_1U_tagFLATARRAY)
#define yEqF_z_sysincl_exp_1U_tagFLATARRAY(Expr1,Expr2)  yEq_z_sysincl_exp_1U_tagFLATARRAY(Expr1,Expr2)
#define yNEqF_z_sysincl_exp_1U_tagFLATARRAY(Expr1,Expr2)  ( ! yEq_z_sysincl_exp_1U_tagFLATARRAY(Expr1,Expr2) )
#ifndef ANY_z_sysincl_exp_1U_tagFLATARRAY
#define ANY_z_sysincl_exp_1U_tagFLATARRAY(R) (z_sysincl_exp_1U_tagFLATARRAY *)GenericAnySort(R, (tSDLTypeInfo *)&ySDL_z_sysincl_exp_1U_tagFLATARRAY)
#endif
#define z_sysincl_exp_1U3_copy(P)  P

/*****
* NEWTYPE tagMACDUPLC  (HEADING section)
* <<PACKAGE sysincl_exp>>
* #SDTREF(TEXT,C:\\Kolevatov\\Projects\\SDL\\STACK80211\\proc_mac_exp.h,41)
******/
#ifndef XOPTSORT
extern XCONST struct xSortIdStruct ySrtR_z_sysincl_exp_1V_tagMACDUPLC;
#define ySrtN_z_sysincl_exp_1V_tagMACDUPLC  (&ySrtR_z_sysincl_exp_1V_tagMACDUPLC)
#endif

#define yAss_z_sysincl_exp_1V_tagMACDUPLC(Addr,Expr,AssName) (void)GenericAssignSort(Addr,Expr,AssName,(tSDLTypeInfo *)&ySDL_z_sysincl_exp_1V_tagMACDUPLC)
#define yAssF_z_sysincl_exp_1V_tagMACDUPLC(V,E,A)  yAss_z_sysincl_exp_1V_tagMACDUPLC(&(V),E,A)
#define yEq_z_sysincl_exp_1V_tagMACDUPLC(Expr1,Expr2) GenericEqualSort((void *)Expr1,(void *)Expr2,(tSDLTypeInfo *)&ySDL_z_sysincl_exp_1V_tagMACDUPLC)
#define yEqF_z_sysincl_exp_1V_tagMACDUPLC(Expr1,Expr2)  yEq_z_sysincl_exp_1V_tagMACDUPLC(Expr1,Expr2)
#define yNEqF_z_sysincl_exp_1V_tagMACDUPLC(Expr1,Expr2)  ( ! yEq_z_sysincl_exp_1V_tagMACDUPLC(Expr1,Expr2) )
#ifndef ANY_z_sysincl_exp_1V_tagMACDUPLC
#define ANY_z_sysincl_exp_1V_tagMACDUPLC(R) (z_sysincl_exp_1V_tagMACDUPLC *)GenericAnySort(R, (tSDLTypeInfo *)&ySDL_z_sysincl_exp_1V_tagMACDUPLC)
#endif
#define z_sysincl_exp_1V3_copy(P)  P

/*****
* NEWTYPE tagMAC_MIBCNTRS  (HEADING section)
* <<PACKAGE sysincl_exp>>
* #SDTREF(TEXT,C:\\Kolevatov\\Projects\\SDL\\STACK80211\\proc_mac_exp.h,50)
******/
#ifndef XOPTSORT
extern XCONST struct xSortIdStruct ySrtR_z_sysincl_exp_1W_tagMAC_MIBCNTRS;
#define ySrtN_z_sysincl_exp_1W_tagMAC_MIBCNTRS  (&ySrtR_z_sysincl_exp_1W_tagMAC_MIBCNTRS)
#endif

#define yAssF_z_sysincl_exp_1W_tagMAC_MIBCNTRS(V,E,A)  V = *(z_sysincl_exp_1W_tagMAC_MIBCNTRS *)(E)
#define yEq_z_sysincl_exp_1W_tagMAC_MIBCNTRS(Expr1,Expr2) GenericEqualSort((void *)Expr1,(void *)Expr2,(tSDLTypeInfo *)&ySDL_z_sysincl_exp_1W_tagMAC_MIBCNTRS)
#define yEqF_z_sysincl_exp_1W_tagMAC_MIBCNTRS(Expr1,Expr2)  yEq_z_sysincl_exp_1W_tagMAC_MIBCNTRS(Expr1,Expr2)
#define yNEqF_z_sysincl_exp_1W_tagMAC_MIBCNTRS(Expr1,Expr2)  ( ! yEq_z_sysincl_exp_1W_tagMAC_MIBCNTRS(Expr1,Expr2) )
#ifndef ANY_z_sysincl_exp_1W_tagMAC_MIBCNTRS
#define ANY_z_sysincl_exp_1W_tagMAC_MIBCNTRS(R) (z_sysincl_exp_1W_tagMAC_MIBCNTRS *)GenericAnySort(R, (tSDLTypeInfo *)&ySDL_z_sysincl_exp_1W_tagMAC_MIBCNTRS)
#endif
#define z_sysincl_exp_1W03_copy(P)  P

/*****
* NEWTYPE CA_sysincl_exp_16_X_tagMACDUPLC  (HEADING section)
* <<PACKAGE sysincl_exp>>
* #SDTREF(TEXT,C:\\Kolevatov\\Projects\\SDL\\STACK80211\\proc_mac_exp.h,68)
******/
#ifndef XOPTSORT
extern XCONST struct xSortIdStruct ySrtR_z_sysincl_exp_1X_CA_sysincl_exp_16_X_tagMACDUPLC;
#define ySrtN_z_sysincl_exp_1X_CA_sysincl_exp_16_X_tagMACDUPLC  (&ySrtR_z_sysincl_exp_1X_CA_sysincl_exp_16_X_tagMACDUPLC)
#endif

#define yAss_z_sysincl_exp_1X_CA_sysincl_exp_16_X_tagMACDUPLC(Addr,Expr,AssName) (void)GenericAssignSort(Addr,Expr,AssName,(tSDLTypeInfo *)&ySDL_z_sysincl_exp_1X_CA_sysincl_exp_16_X_tagMACDUPLC)
#define yAssF_z_sysincl_exp_1X_CA_sysincl_exp_16_X_tagMACDUPLC(V,E,A)  yAss_z_sysincl_exp_1X_CA_sysincl_exp_16_X_tagMACDUPLC(V,E,A)
#define yEq_z_sysincl_exp_1X_CA_sysincl_exp_16_X_tagMACDUPLC(Expr1,Expr2) GenericEqualSort((void *)Expr1,(void *)Expr2,(tSDLTypeInfo *)&ySDL_z_sysincl_exp_1X_CA_sysincl_exp_16_X_tagMACDUPLC)
#define yEqF_z_sysincl_exp_1X_CA_sysincl_exp_16_X_tagMACDUPLC(Expr1,Expr2)  yEq_z_sysincl_exp_1X_CA_sysincl_exp_16_X_tagMACDUPLC(Expr1,Expr2)
#define yNEqF_z_sysincl_exp_1X_CA_sysincl_exp_16_X_tagMACDUPLC(Expr1,Expr2)  ( ! yEq_z_sysincl_exp_1X_CA_sysincl_exp_16_X_tagMACDUPLC(Expr1,Expr2) )
#ifdef XEINDEX
extern SDL_Integer yTstI_z_sysincl_exp_1X_CA_sysincl_exp_16_X_tagMACDUPLC (
  SDL_Integer);
#else
#define yTstI_z_sysincl_exp_1X_CA_sysincl_exp_16_X_tagMACDUPLC(yExpr)  yExpr
#endif
#ifndef ANY_z_sysincl_exp_1X_CA_sysincl_exp_16_X_tagMACDUPLC
#define ANY_z_sysincl_exp_1X_CA_sysincl_exp_16_X_tagMACDUPLC
#endif
#define z_sysincl_exp_1X5_copy(P)  P

/*****
* NEWTYPE tagMAC_ST  (HEADING section)
* <<PACKAGE sysincl_exp>>
* #SDTREF(TEXT,C:\\Kolevatov\\Projects\\SDL\\STACK80211\\proc_mac_exp.h,68)
******/
#ifndef XOPTSORT
extern XCONST struct xSortIdStruct ySrtR_z_sysincl_exp_1Y_tagMAC_ST;
#define ySrtN_z_sysincl_exp_1Y_tagMAC_ST  (&ySrtR_z_sysincl_exp_1Y_tagMAC_ST)
#endif

#define yAss_z_sysincl_exp_1Y_tagMAC_ST(Addr,Expr,AssName) (void)GenericAssignSort(Addr,Expr,AssName,(tSDLTypeInfo *)&ySDL_z_sysincl_exp_1Y_tagMAC_ST)
#define yAssF_z_sysincl_exp_1Y_tagMAC_ST(V,E,A)  yAss_z_sysincl_exp_1Y_tagMAC_ST(&(V),E,A)
#define yEq_z_sysincl_exp_1Y_tagMAC_ST(Expr1,Expr2) GenericEqualSort((void *)Expr1,(void *)Expr2,(tSDLTypeInfo *)&ySDL_z_sysincl_exp_1Y_tagMAC_ST)
#define yEqF_z_sysincl_exp_1Y_tagMAC_ST(Expr1,Expr2)  yEq_z_sysincl_exp_1Y_tagMAC_ST(Expr1,Expr2)
#define yNEqF_z_sysincl_exp_1Y_tagMAC_ST(Expr1,Expr2)  ( ! yEq_z_sysincl_exp_1Y_tagMAC_ST(Expr1,Expr2) )
#ifndef ANY_z_sysincl_exp_1Y_tagMAC_ST
#define ANY_z_sysincl_exp_1Y_tagMAC_ST(R) (z_sysincl_exp_1Y_tagMAC_ST *)GenericAnySort(R, (tSDLTypeInfo *)&ySDL_z_sysincl_exp_1Y_tagMAC_ST)
#endif
#define z_sysincl_exp_1Y03_copy(P)  P

/*****
* NEWTYPE CA_sysincl_exp_4096_X_Octet  (HEADING section)
* <<PACKAGE sysincl_exp>>
* #SDTREF(TEXT,C:\\Kolevatov\\Projects\\SDL\\STACK80211\\proc_phyctrl_exp.h,32)
******/
#ifndef XOPTSORT
extern XCONST struct xSortIdStruct ySrtR_z_sysincl_exp_1Z_CA_sysincl_exp_4096_X_Octet;
#define ySrtN_z_sysincl_exp_1Z_CA_sysincl_exp_4096_X_Octet  (&ySrtR_z_sysincl_exp_1Z_CA_sysincl_exp_4096_X_Octet)
#endif

#define yAss_z_sysincl_exp_1Z_CA_sysincl_exp_4096_X_Octet(Addr,Expr,AssName) (void)GenericAssignSort(Addr,Expr,AssName,(tSDLTypeInfo *)&ySDL_z_sysincl_exp_1Z_CA_sysincl_exp_4096_X_Octet)
#define yAssF_z_sysincl_exp_1Z_CA_sysincl_exp_4096_X_Octet(V,E,A)  yAss_z_sysincl_exp_1Z_CA_sysincl_exp_4096_X_Octet(V,E,A)
#define yEq_z_sysincl_exp_1Z_CA_sysincl_exp_4096_X_Octet(Expr1,Expr2) GenericEqualSort((void *)Expr1,(void *)Expr2,(tSDLTypeInfo *)&ySDL_z_sysincl_exp_1Z_CA_sysincl_exp_4096_X_Octet)
#define yEqF_z_sysincl_exp_1Z_CA_sysincl_exp_4096_X_Octet(Expr1,Expr2)  yEq_z_sysincl_exp_1Z_CA_sysincl_exp_4096_X_Octet(Expr1,Expr2)
#define yNEqF_z_sysincl_exp_1Z_CA_sysincl_exp_4096_X_Octet(Expr1,Expr2)  ( ! yEq_z_sysincl_exp_1Z_CA_sysincl_exp_4096_X_Octet(Expr1,Expr2) )
#ifdef XEINDEX
extern SDL_Integer yTstI_z_sysincl_exp_1Z_CA_sysincl_exp_4096_X_Octet (
  SDL_Integer);
#else
#define yTstI_z_sysincl_exp_1Z_CA_sysincl_exp_4096_X_Octet(yExpr)  yExpr
#endif
#ifndef ANY_z_sysincl_exp_1Z_CA_sysincl_exp_4096_X_Octet
#define ANY_z_sysincl_exp_1Z_CA_sysincl_exp_4096_X_Octet
#endif
#define z_sysincl_exp_1Z5_copy(P)  P

/*****
* NEWTYPE tagFLDPSDU  (HEADING section)
* <<PACKAGE sysincl_exp>>
* #SDTREF(TEXT,C:\\Kolevatov\\Projects\\SDL\\STACK80211\\proc_phyctrl_exp.h,32)
******/
#ifndef XOPTSORT
extern XCONST struct xSortIdStruct ySrtR_z_sysincl_exp_20_tagFLDPSDU;
#define ySrtN_z_sysincl_exp_20_tagFLDPSDU  (&ySrtR_z_sysincl_exp_20_tagFLDPSDU)
#endif

#define yAss_z_sysincl_exp_20_tagFLDPSDU(Addr,Expr,AssName) (void)GenericAssignSort(Addr,Expr,AssName,(tSDLTypeInfo *)&ySDL_z_sysincl_exp_20_tagFLDPSDU)
#define yAssF_z_sysincl_exp_20_tagFLDPSDU(V,E,A)  yAss_z_sysincl_exp_20_tagFLDPSDU(&(V),E,A)
#define yEq_z_sysincl_exp_20_tagFLDPSDU(Expr1,Expr2) GenericEqualSort((void *)Expr1,(void *)Expr2,(tSDLTypeInfo *)&ySDL_z_sysincl_exp_20_tagFLDPSDU)
#define yEqF_z_sysincl_exp_20_tagFLDPSDU(Expr1,Expr2)  yEq_z_sysincl_exp_20_tagFLDPSDU(Expr1,Expr2)
#define yNEqF_z_sysincl_exp_20_tagFLDPSDU(Expr1,Expr2)  ( ! yEq_z_sysincl_exp_20_tagFLDPSDU(Expr1,Expr2) )
#ifndef ANY_z_sysincl_exp_20_tagFLDPSDU
#define ANY_z_sysincl_exp_20_tagFLDPSDU(R) (z_sysincl_exp_20_tagFLDPSDU *)GenericAnySort(R, (tSDLTypeInfo *)&ySDL_z_sysincl_exp_20_tagFLDPSDU)
#endif
#define z_sysincl_exp_203_copy(P)  P

/*****
* NEWTYPE tagSIGNAL  (HEADING section)
* <<PACKAGE sysincl_exp>>
* #SDTREF(TEXT,C:\\Kolevatov\\Projects\\SDL\\STACK80211\\proc_phyctrl_exp.h,40)
******/
#ifndef XOPTSORT
extern XCONST struct xSortIdStruct ySrtR_z_sysincl_exp_21_tagSIGNAL;
#define ySrtN_z_sysincl_exp_21_tagSIGNAL  (&ySrtR_z_sysincl_exp_21_tagSIGNAL)
#endif

#define yAssF_z_sysincl_exp_21_tagSIGNAL(V,E,A)  V = *(z_sysincl_exp_21_tagSIGNAL *)(E)
#define yEq_z_sysincl_exp_21_tagSIGNAL(Expr1,Expr2) GenericEqualSort((void *)Expr1,(void *)Expr2,(tSDLTypeInfo *)&ySDL_z_sysincl_exp_21_tagSIGNAL)
#define yEqF_z_sysincl_exp_21_tagSIGNAL(Expr1,Expr2)  yEq_z_sysincl_exp_21_tagSIGNAL(Expr1,Expr2)
#define yNEqF_z_sysincl_exp_21_tagSIGNAL(Expr1,Expr2)  ( ! yEq_z_sysincl_exp_21_tagSIGNAL(Expr1,Expr2) )
#ifndef ANY_z_sysincl_exp_21_tagSIGNAL
#define ANY_z_sysincl_exp_21_tagSIGNAL(R) (z_sysincl_exp_21_tagSIGNAL *)GenericAnySort(R, (tSDLTypeInfo *)&ySDL_z_sysincl_exp_21_tagSIGNAL)
#endif
#define z_sysincl_exp_213_copy(P)  P

/*****
* NEWTYPE CA_sysincl_exp_216_X_Octet  (HEADING section)
* <<PACKAGE sysincl_exp>>
* #SDTREF(TEXT,C:\\Kolevatov\\Projects\\SDL\\STACK80211\\proc_phyctrl_exp.h,51)
******/
#ifndef XOPTSORT
extern XCONST struct xSortIdStruct ySrtR_z_sysincl_exp_22_CA_sysincl_exp_216_X_Octet;
#define ySrtN_z_sysincl_exp_22_CA_sysincl_exp_216_X_Octet  (&ySrtR_z_sysincl_exp_22_CA_sysincl_exp_216_X_Octet)
#endif

#define yAss_z_sysincl_exp_22_CA_sysincl_exp_216_X_Octet(Addr,Expr,AssName) (void)GenericAssignSort(Addr,Expr,AssName,(tSDLTypeInfo *)&ySDL_z_sysincl_exp_22_CA_sysincl_exp_216_X_Octet)
#define yAssF_z_sysincl_exp_22_CA_sysincl_exp_216_X_Octet(V,E,A)  yAss_z_sysincl_exp_22_CA_sysincl_exp_216_X_Octet(V,E,A)
#define yEq_z_sysincl_exp_22_CA_sysincl_exp_216_X_Octet(Expr1,Expr2) GenericEqualSort((void *)Expr1,(void *)Expr2,(tSDLTypeInfo *)&ySDL_z_sysincl_exp_22_CA_sysincl_exp_216_X_Octet)
#define yEqF_z_sysincl_exp_22_CA_sysincl_exp_216_X_Octet(Expr1,Expr2)  yEq_z_sysincl_exp_22_CA_sysincl_exp_216_X_Octet(Expr1,Expr2)
#define yNEqF_z_sysincl_exp_22_CA_sysincl_exp_216_X_Octet(Expr1,Expr2)  ( ! yEq_z_sysincl_exp_22_CA_sysincl_exp_216_X_Octet(Expr1,Expr2) )
#ifdef XEINDEX
extern SDL_Integer yTstI_z_sysincl_exp_22_CA_sysincl_exp_216_X_Octet (
  SDL_Integer);
#else
#define yTstI_z_sysincl_exp_22_CA_sysincl_exp_216_X_Octet(yExpr)  yExpr
#endif
#ifndef ANY_z_sysincl_exp_22_CA_sysincl_exp_216_X_Octet
#define ANY_z_sysincl_exp_22_CA_sysincl_exp_216_X_Octet
#endif
#define z_sysincl_exp_225_copy(P)  P

/*****
* NEWTYPE tagBITSEQ  (HEADING section)
* <<PACKAGE sysincl_exp>>
* #SDTREF(TEXT,C:\\Kolevatov\\Projects\\SDL\\STACK80211\\proc_phyctrl_exp.h,51)
******/
#ifndef XOPTSORT
extern XCONST struct xSortIdStruct ySrtR_z_sysincl_exp_23_tagBITSEQ;
#define ySrtN_z_sysincl_exp_23_tagBITSEQ  (&ySrtR_z_sysincl_exp_23_tagBITSEQ)
#endif

#define yAss_z_sysincl_exp_23_tagBITSEQ(Addr,Expr,AssName) (void)GenericAssignSort(Addr,Expr,AssName,(tSDLTypeInfo *)&ySDL_z_sysincl_exp_23_tagBITSEQ)
#define yAssF_z_sysincl_exp_23_tagBITSEQ(V,E,A)  yAss_z_sysincl_exp_23_tagBITSEQ(&(V),E,A)
#define yEq_z_sysincl_exp_23_tagBITSEQ(Expr1,Expr2) GenericEqualSort((void *)Expr1,(void *)Expr2,(tSDLTypeInfo *)&ySDL_z_sysincl_exp_23_tagBITSEQ)
#define yEqF_z_sysincl_exp_23_tagBITSEQ(Expr1,Expr2)  yEq_z_sysincl_exp_23_tagBITSEQ(Expr1,Expr2)
#define yNEqF_z_sysincl_exp_23_tagBITSEQ(Expr1,Expr2)  ( ! yEq_z_sysincl_exp_23_tagBITSEQ(Expr1,Expr2) )
#ifndef ANY_z_sysincl_exp_23_tagBITSEQ
#define ANY_z_sysincl_exp_23_tagBITSEQ(R) (z_sysincl_exp_23_tagBITSEQ *)GenericAnySort(R, (tSDLTypeInfo *)&ySDL_z_sysincl_exp_23_tagBITSEQ)
#endif
#define z_sysincl_exp_233_copy(P)  P

/*****
* SYNTYPE PSDU  (HEADING section)
* <<PACKAGE sysincl_exp>>
* #SDTREF(TEXT,C:\\Kolevatov\\Projects\\SDL\\STACK80211\\proc_phyctrl_exp.h,57)
******/
#ifndef XOPTSORT
extern XCONST struct xSortIdStruct ySrtR_z_sysincl_exp_2J_PSDU;
#define ySrtN_z_sysincl_exp_2J_PSDU  (&ySrtR_z_sysincl_exp_2J_PSDU)
#endif

#define yAssF_z_sysincl_exp_2J_PSDU(V,E,A)  yAssF_z_sysincl_exp_20_tagFLDPSDU(V,E,A)
#define yEqF_z_sysincl_exp_2J_PSDU(Expr1,Expr2)  yEqF_z_sysincl_exp_20_tagFLDPSDU(Expr1,Expr2)
#define yNEqF_z_sysincl_exp_2J_PSDU(Expr1,Expr2)  yNEqF_z_sysincl_exp_20_tagFLDPSDU(Expr1,Expr2)
#ifndef ANY_z_sysincl_exp_2J_PSDU
#define ANY_z_sysincl_exp_2J_PSDU ANY_z_sysincl_exp_20_tagFLDPSDU
#endif

/*****
* SYNTYPE HDR  (HEADING section)
* <<PACKAGE sysincl_exp>>
* #SDTREF(TEXT,C:\\Kolevatov\\Projects\\SDL\\STACK80211\\proc_phyctrl_exp.h,58)
******/
#ifndef XOPTSORT
extern XCONST struct xSortIdStruct ySrtR_z_sysincl_exp_2K_HDR;
#define ySrtN_z_sysincl_exp_2K_HDR  (&ySrtR_z_sysincl_exp_2K_HDR)
#endif

#define yAssF_z_sysincl_exp_2K_HDR(V,E,A)  yAssF_z_sysincl_exp_21_tagSIGNAL(V,E,A)
#define yEqF_z_sysincl_exp_2K_HDR(Expr1,Expr2)  yEqF_z_sysincl_exp_21_tagSIGNAL(Expr1,Expr2)
#define yNEqF_z_sysincl_exp_2K_HDR(Expr1,Expr2)  yNEqF_z_sysincl_exp_21_tagSIGNAL(Expr1,Expr2)
#ifndef ANY_z_sysincl_exp_2K_HDR
#define ANY_z_sysincl_exp_2K_HDR ANY_z_sysincl_exp_21_tagSIGNAL
#endif

/*****
* SYNTYPE BITSEQ  (HEADING section)
* <<PACKAGE sysincl_exp>>
* #SDTREF(TEXT,C:\\Kolevatov\\Projects\\SDL\\STACK80211\\proc_phyctrl_exp.h,59)
******/
#ifndef XOPTSORT
extern XCONST struct xSortIdStruct ySrtR_z_sysincl_exp_2L_BITSEQ;
#define ySrtN_z_sysincl_exp_2L_BITSEQ  (&ySrtR_z_sysincl_exp_2L_BITSEQ)
#endif

#define yAssF_z_sysincl_exp_2L_BITSEQ(V,E,A)  yAssF_z_sysincl_exp_23_tagBITSEQ(V,E,A)
#define yEqF_z_sysincl_exp_2L_BITSEQ(Expr1,Expr2)  yEqF_z_sysincl_exp_23_tagBITSEQ(Expr1,Expr2)
#define yNEqF_z_sysincl_exp_2L_BITSEQ(Expr1,Expr2)  yNEqF_z_sysincl_exp_23_tagBITSEQ(Expr1,Expr2)
#ifndef ANY_z_sysincl_exp_2L_BITSEQ
#define ANY_z_sysincl_exp_2L_BITSEQ ANY_z_sysincl_exp_23_tagBITSEQ
#endif

/*****
* NEWTYPE tagCMPLX  (HEADING section)
* <<PACKAGE sysincl_exp>>
* #SDTREF(TEXT,C:\\Kolevatov\\Projects\\SDL\\STACK80211\\proc_phy_exp.h,17)
******/
#ifndef XOPTSORT
extern XCONST struct xSortIdStruct ySrtR_z_sysincl_exp_24_tagCMPLX;
#define ySrtN_z_sysincl_exp_24_tagCMPLX  (&ySrtR_z_sysincl_exp_24_tagCMPLX)
#endif

#define yAssF_z_sysincl_exp_24_tagCMPLX(V,E,A)  V = *(z_sysincl_exp_24_tagCMPLX *)(E)
#define yEq_z_sysincl_exp_24_tagCMPLX(Expr1,Expr2) GenericEqualSort((void *)Expr1,(void *)Expr2,(tSDLTypeInfo *)&ySDL_z_sysincl_exp_24_tagCMPLX)
#define yEqF_z_sysincl_exp_24_tagCMPLX(Expr1,Expr2)  yEq_z_sysincl_exp_24_tagCMPLX(Expr1,Expr2)
#define yNEqF_z_sysincl_exp_24_tagCMPLX(Expr1,Expr2)  ( ! yEq_z_sysincl_exp_24_tagCMPLX(Expr1,Expr2) )
#ifndef ANY_z_sysincl_exp_24_tagCMPLX
#define ANY_z_sysincl_exp_24_tagCMPLX(R) (z_sysincl_exp_24_tagCMPLX *)GenericAnySort(R, (tSDLTypeInfo *)&ySDL_z_sysincl_exp_24_tagCMPLX)
#endif
#define z_sysincl_exp_243_copy(P)  P

/*****
* NEWTYPE CA_sysincl_exp_80_X_tagCMPLX  (HEADING section)
* <<PACKAGE sysincl_exp>>
* #SDTREF(TEXT,C:\\Kolevatov\\Projects\\SDL\\STACK80211\\proc_phy_exp.h,24)
******/
#ifndef XOPTSORT
extern XCONST struct xSortIdStruct ySrtR_z_sysincl_exp_25_CA_sysincl_exp_80_X_tagCMPLX;
#define ySrtN_z_sysincl_exp_25_CA_sysincl_exp_80_X_tagCMPLX  (&ySrtR_z_sysincl_exp_25_CA_sysincl_exp_80_X_tagCMPLX)
#endif

#define yAss_z_sysincl_exp_25_CA_sysincl_exp_80_X_tagCMPLX(Addr,Expr,AssName) (void)GenericAssignSort(Addr,Expr,AssName,(tSDLTypeInfo *)&ySDL_z_sysincl_exp_25_CA_sysincl_exp_80_X_tagCMPLX)
#define yAssF_z_sysincl_exp_25_CA_sysincl_exp_80_X_tagCMPLX(V,E,A)  yAss_z_sysincl_exp_25_CA_sysincl_exp_80_X_tagCMPLX(V,E,A)
#define yEq_z_sysincl_exp_25_CA_sysincl_exp_80_X_tagCMPLX(Expr1,Expr2) GenericEqualSort((void *)Expr1,(void *)Expr2,(tSDLTypeInfo *)&ySDL_z_sysincl_exp_25_CA_sysincl_exp_80_X_tagCMPLX)
#define yEqF_z_sysincl_exp_25_CA_sysincl_exp_80_X_tagCMPLX(Expr1,Expr2)  yEq_z_sysincl_exp_25_CA_sysincl_exp_80_X_tagCMPLX(Expr1,Expr2)
#define yNEqF_z_sysincl_exp_25_CA_sysincl_exp_80_X_tagCMPLX(Expr1,Expr2)  ( ! yEq_z_sysincl_exp_25_CA_sysincl_exp_80_X_tagCMPLX(Expr1,Expr2) )
#ifdef XEINDEX
extern SDL_Integer yTstI_z_sysincl_exp_25_CA_sysincl_exp_80_X_tagCMPLX (
  SDL_Integer);
#else
#define yTstI_z_sysincl_exp_25_CA_sysincl_exp_80_X_tagCMPLX(yExpr)  yExpr
#endif
#ifndef ANY_z_sysincl_exp_25_CA_sysincl_exp_80_X_tagCMPLX
#define ANY_z_sysincl_exp_25_CA_sysincl_exp_80_X_tagCMPLX
#endif
#define z_sysincl_exp_255_copy(P)  P

/*****
* NEWTYPE tagSYMBOL  (HEADING section)
* <<PACKAGE sysincl_exp>>
* #SDTREF(TEXT,C:\\Kolevatov\\Projects\\SDL\\STACK80211\\proc_phy_exp.h,24)
******/
#ifndef XOPTSORT
extern XCONST struct xSortIdStruct ySrtR_z_sysincl_exp_26_tagSYMBOL;
#define ySrtN_z_sysincl_exp_26_tagSYMBOL  (&ySrtR_z_sysincl_exp_26_tagSYMBOL)
#endif

#define yAss_z_sysincl_exp_26_tagSYMBOL(Addr,Expr,AssName) (void)GenericAssignSort(Addr,Expr,AssName,(tSDLTypeInfo *)&ySDL_z_sysincl_exp_26_tagSYMBOL)
#define yAssF_z_sysincl_exp_26_tagSYMBOL(V,E,A)  yAss_z_sysincl_exp_26_tagSYMBOL(&(V),E,A)
#define yEq_z_sysincl_exp_26_tagSYMBOL(Expr1,Expr2) GenericEqualSort((void *)Expr1,(void *)Expr2,(tSDLTypeInfo *)&ySDL_z_sysincl_exp_26_tagSYMBOL)
#define yEqF_z_sysincl_exp_26_tagSYMBOL(Expr1,Expr2)  yEq_z_sysincl_exp_26_tagSYMBOL(Expr1,Expr2)
#define yNEqF_z_sysincl_exp_26_tagSYMBOL(Expr1,Expr2)  ( ! yEq_z_sysincl_exp_26_tagSYMBOL(Expr1,Expr2) )
#ifndef ANY_z_sysincl_exp_26_tagSYMBOL
#define ANY_z_sysincl_exp_26_tagSYMBOL(R) (z_sysincl_exp_26_tagSYMBOL *)GenericAnySort(R, (tSDLTypeInfo *)&ySDL_z_sysincl_exp_26_tagSYMBOL)
#endif
#define z_sysincl_exp_263_copy(P)  P

/*****
* NEWTYPE CA_sysincl_exp_20_X_tagCMPLX  (HEADING section)
* <<PACKAGE sysincl_exp>>
* #SDTREF(TEXT,C:\\Kolevatov\\Projects\\SDL\\STACK80211\\proc_phy_exp.h,31)
******/
#ifndef XOPTSORT
extern XCONST struct xSortIdStruct ySrtR_z_sysincl_exp_27_CA_sysincl_exp_20_X_tagCMPLX;
#define ySrtN_z_sysincl_exp_27_CA_sysincl_exp_20_X_tagCMPLX  (&ySrtR_z_sysincl_exp_27_CA_sysincl_exp_20_X_tagCMPLX)
#endif

#define yAss_z_sysincl_exp_27_CA_sysincl_exp_20_X_tagCMPLX(Addr,Expr,AssName) (void)GenericAssignSort(Addr,Expr,AssName,(tSDLTypeInfo *)&ySDL_z_sysincl_exp_27_CA_sysincl_exp_20_X_tagCMPLX)
#define yAssF_z_sysincl_exp_27_CA_sysincl_exp_20_X_tagCMPLX(V,E,A)  yAss_z_sysincl_exp_27_CA_sysincl_exp_20_X_tagCMPLX(V,E,A)
#define yEq_z_sysincl_exp_27_CA_sysincl_exp_20_X_tagCMPLX(Expr1,Expr2) GenericEqualSort((void *)Expr1,(void *)Expr2,(tSDLTypeInfo *)&ySDL_z_sysincl_exp_27_CA_sysincl_exp_20_X_tagCMPLX)
#define yEqF_z_sysincl_exp_27_CA_sysincl_exp_20_X_tagCMPLX(Expr1,Expr2)  yEq_z_sysincl_exp_27_CA_sysincl_exp_20_X_tagCMPLX(Expr1,Expr2)
#define yNEqF_z_sysincl_exp_27_CA_sysincl_exp_20_X_tagCMPLX(Expr1,Expr2)  ( ! yEq_z_sysincl_exp_27_CA_sysincl_exp_20_X_tagCMPLX(Expr1,Expr2) )
#ifdef XEINDEX
extern SDL_Integer yTstI_z_sysincl_exp_27_CA_sysincl_exp_20_X_tagCMPLX (
  SDL_Integer);
#else
#define yTstI_z_sysincl_exp_27_CA_sysincl_exp_20_X_tagCMPLX(yExpr)  yExpr
#endif
#ifndef ANY_z_sysincl_exp_27_CA_sysincl_exp_20_X_tagCMPLX
#define ANY_z_sysincl_exp_27_CA_sysincl_exp_20_X_tagCMPLX
#endif
#define z_sysincl_exp_275_copy(P)  P

/*****
* NEWTYPE tagMDM_SAMPLES  (HEADING section)
* <<PACKAGE sysincl_exp>>
* #SDTREF(TEXT,C:\\Kolevatov\\Projects\\SDL\\STACK80211\\proc_phy_exp.h,31)
******/
#ifndef XOPTSORT
extern XCONST struct xSortIdStruct ySrtR_z_sysincl_exp_28_tagMDM_SAMPLES;
#define ySrtN_z_sysincl_exp_28_tagMDM_SAMPLES  (&ySrtR_z_sysincl_exp_28_tagMDM_SAMPLES)
#endif

#define yAss_z_sysincl_exp_28_tagMDM_SAMPLES(Addr,Expr,AssName) (void)GenericAssignSort(Addr,Expr,AssName,(tSDLTypeInfo *)&ySDL_z_sysincl_exp_28_tagMDM_SAMPLES)
#define yAssF_z_sysincl_exp_28_tagMDM_SAMPLES(V,E,A)  yAss_z_sysincl_exp_28_tagMDM_SAMPLES(&(V),E,A)
#define yEq_z_sysincl_exp_28_tagMDM_SAMPLES(Expr1,Expr2) GenericEqualSort((void *)Expr1,(void *)Expr2,(tSDLTypeInfo *)&ySDL_z_sysincl_exp_28_tagMDM_SAMPLES)
#define yEqF_z_sysincl_exp_28_tagMDM_SAMPLES(Expr1,Expr2)  yEq_z_sysincl_exp_28_tagMDM_SAMPLES(Expr1,Expr2)
#define yNEqF_z_sysincl_exp_28_tagMDM_SAMPLES(Expr1,Expr2)  ( ! yEq_z_sysincl_exp_28_tagMDM_SAMPLES(Expr1,Expr2) )
#ifndef ANY_z_sysincl_exp_28_tagMDM_SAMPLES
#define ANY_z_sysincl_exp_28_tagMDM_SAMPLES(R) (z_sysincl_exp_28_tagMDM_SAMPLES *)GenericAnySort(R, (tSDLTypeInfo *)&ySDL_z_sysincl_exp_28_tagMDM_SAMPLES)
#endif
#define z_sysincl_exp_283_copy(P)  P

/*****
* SYNTYPE SYMB  (HEADING section)
* <<PACKAGE sysincl_exp>>
* #SDTREF(TEXT,C:\\Kolevatov\\Projects\\SDL\\STACK80211\\proc_phy_exp.h,36)
******/
#ifndef XOPTSORT
extern XCONST struct xSortIdStruct ySrtR_z_sysincl_exp_2M_SYMB;
#define ySrtN_z_sysincl_exp_2M_SYMB  (&ySrtR_z_sysincl_exp_2M_SYMB)
#endif

#define yAssF_z_sysincl_exp_2M_SYMB(V,E,A)  yAssF_z_sysincl_exp_26_tagSYMBOL(V,E,A)
#define yEqF_z_sysincl_exp_2M_SYMB(Expr1,Expr2)  yEqF_z_sysincl_exp_26_tagSYMBOL(Expr1,Expr2)
#define yNEqF_z_sysincl_exp_2M_SYMB(Expr1,Expr2)  yNEqF_z_sysincl_exp_26_tagSYMBOL(Expr1,Expr2)
#ifndef ANY_z_sysincl_exp_2M_SYMB
#define ANY_z_sysincl_exp_2M_SYMB ANY_z_sysincl_exp_26_tagSYMBOL
#endif

/*****
* SYNTYPE SMPLS  (HEADING section)
* <<PACKAGE sysincl_exp>>
* #SDTREF(TEXT,C:\\Kolevatov\\Projects\\SDL\\STACK80211\\proc_phy_exp.h,37)
******/
#ifndef XOPTSORT
extern XCONST struct xSortIdStruct ySrtR_z_sysincl_exp_2N_SMPLS;
#define ySrtN_z_sysincl_exp_2N_SMPLS  (&ySrtR_z_sysincl_exp_2N_SMPLS)
#endif

#define yAssF_z_sysincl_exp_2N_SMPLS(V,E,A)  yAssF_z_sysincl_exp_28_tagMDM_SAMPLES(V,E,A)
#define yEqF_z_sysincl_exp_2N_SMPLS(Expr1,Expr2)  yEqF_z_sysincl_exp_28_tagMDM_SAMPLES(Expr1,Expr2)
#define yNEqF_z_sysincl_exp_2N_SMPLS(Expr1,Expr2)  yNEqF_z_sysincl_exp_28_tagMDM_SAMPLES(Expr1,Expr2)
#ifndef ANY_z_sysincl_exp_2N_SMPLS
#define ANY_z_sysincl_exp_2N_SMPLS ANY_z_sysincl_exp_28_tagMDM_SAMPLES
#endif

/*****
* NEWTYPE Ref_sysincl_exp_Integer  (HEADING section)
* <<PACKAGE sysincl_exp>>
* #SDTREF(TEXT,C:\\Kolevatov\\Projects\\SDL\\STACK80211\\export_sdl_exp.h,33)
******/
#ifndef XOPTSORT
extern XCONST struct xSortIdStruct ySrtR_z_sysincl_exp_29_Ref_sysincl_exp_Integer;
#define ySrtN_z_sysincl_exp_29_Ref_sysincl_exp_Integer  (&ySrtR_z_sysincl_exp_29_Ref_sysincl_exp_Integer)
#endif

#define yAssF_z_sysincl_exp_29_Ref_sysincl_exp_Integer(V,E,A)  V = E
#define yEqF_z_sysincl_exp_29_Ref_sysincl_exp_Integer(Expr1,Expr2)  (Expr1) == (Expr2)
#define yNEqF_z_sysincl_exp_29_Ref_sysincl_exp_Integer(Expr1,Expr2)  (Expr1) != (Expr2)
extern void * yMkAddr_z_sysincl_exp_29_Ref_sysincl_exp_Integer (z_sysincl_exp_29_Ref_sysincl_exp_Integer, z_sysincl_exp_29_Ref_sysincl_exp_Integer *);
#ifndef ANY_z_sysincl_exp_29_Ref_sysincl_exp_Integer
#define ANY_z_sysincl_exp_29_Ref_sysincl_exp_Integer 0
#endif
#define z_sysincl_exp_29F_copy(P)  P
#ifdef XVALIDATOR_LIB
#define yAll_z_sysincl_exp_29_Ref_sysincl_exp_Integer() (z_sysincl_exp_29_Ref_sysincl_exp_Integer)XALLOC_REF_VAL(sizeof(SDL_Integer), ySrtN_z_sysincl_exp_29_Ref_sysincl_exp_Integer)
#else
#define yAll_z_sysincl_exp_29_Ref_sysincl_exp_Integer() (z_sysincl_exp_29_Ref_sysincl_exp_Integer)XALLOC(sizeof(SDL_Integer), \
  (tSDLTypeInfo *)&ySDL_z_sysincl_exp_29_Ref_sysincl_exp_Integer)
#endif
#define yPlus_z_sysincl_exp_29_Ref_sysincl_exp_Integer(P1,P2) (P1+P2)
#define yMinus_z_sysincl_exp_29_Ref_sysincl_exp_Integer(P1,P2) (P1-P2)
#define z_sysincl_exp_290_Null() 0
#define z_sysincl_exp_291_Alloc() yAll_z_sysincl_exp_29_Ref_sysincl_exp_Integer()
#ifdef XVALIDATOR_LIB
#define z_sysincl_exp_296_free(P) XFREE_REF_VAL((void **)(P), sizeof(SDL_Integer))
#else
#define z_sysincl_exp_296_free(P) XFREE((void **)(P), sizeof(SDL_Integer))
#endif
#define z_sysincl_exp_299_ref2vstar(P) (z_ctypes_4_Voidstar)(P)
#define z_sysincl_exp_29A_vstar2ref(P) (z_ctypes_4_Voidstar)(P)
#define z_sysincl_exp_29B_ref2vstarstar(P) (z_ctypes_5_Voidstarstar)(P)

/*****
* NEWTYPE Ref_sysincl_exp_tagMAC_ST  (HEADING section)
* <<PACKAGE sysincl_exp>>
* #SDTREF(TEXT,C:\\Kolevatov\\Projects\\SDL\\STACK80211\\export_sdl_exp.h,38)
******/
#ifndef XOPTSORT
extern XCONST struct xSortIdStruct ySrtR_z_sysincl_exp_2A_Ref_sysincl_exp_tagMAC_ST;
#define ySrtN_z_sysincl_exp_2A_Ref_sysincl_exp_tagMAC_ST  (&ySrtR_z_sysincl_exp_2A_Ref_sysincl_exp_tagMAC_ST)
#endif

#define yAssF_z_sysincl_exp_2A_Ref_sysincl_exp_tagMAC_ST(V,E,A)  V = E
#define yEqF_z_sysincl_exp_2A_Ref_sysincl_exp_tagMAC_ST(Expr1,Expr2)  (Expr1) == (Expr2)
#define yNEqF_z_sysincl_exp_2A_Ref_sysincl_exp_tagMAC_ST(Expr1,Expr2)  (Expr1) != (Expr2)
extern void * yMkAddr_z_sysincl_exp_2A_Ref_sysincl_exp_tagMAC_ST (z_sysincl_exp_2A_Ref_sysincl_exp_tagMAC_ST, z_sysincl_exp_2A_Ref_sysincl_exp_tagMAC_ST *);
#ifndef ANY_z_sysincl_exp_2A_Ref_sysincl_exp_tagMAC_ST
#define ANY_z_sysincl_exp_2A_Ref_sysincl_exp_tagMAC_ST 0
#endif
#define z_sysincl_exp_2AF_copy(P)  P
#ifdef XVALIDATOR_LIB
#define yAll_z_sysincl_exp_2A_Ref_sysincl_exp_tagMAC_ST() (z_sysincl_exp_2A_Ref_sysincl_exp_tagMAC_ST)XALLOC_REF_VAL(sizeof(z_sysincl_exp_1Y_tagMAC_ST), ySrtN_z_sysincl_exp_2A_Ref_sysincl_exp_tagMAC_ST)
#else
#define yAll_z_sysincl_exp_2A_Ref_sysincl_exp_tagMAC_ST() (z_sysincl_exp_2A_Ref_sysincl_exp_tagMAC_ST)XALLOC(sizeof(z_sysincl_exp_1Y_tagMAC_ST), \
  (tSDLTypeInfo *)&ySDL_z_sysincl_exp_2A_Ref_sysincl_exp_tagMAC_ST)
#endif
#define yPlus_z_sysincl_exp_2A_Ref_sysincl_exp_tagMAC_ST(P1,P2) (P1+P2)
#define yMinus_z_sysincl_exp_2A_Ref_sysincl_exp_tagMAC_ST(P1,P2) (P1-P2)
#define z_sysincl_exp_2A0_Null() 0
#define z_sysincl_exp_2A1_Alloc() yAll_z_sysincl_exp_2A_Ref_sysincl_exp_tagMAC_ST()
#ifdef XVALIDATOR_LIB
#define z_sysincl_exp_2A6_free(P) XFREE_REF_VAL((void **)(P), sizeof(z_sysincl_exp_1Y_tagMAC_ST))
#else
#define z_sysincl_exp_2A6_free(P) XFREE((void **)(P), sizeof(z_sysincl_exp_1Y_tagMAC_ST))
#endif
#define z_sysincl_exp_2A9_ref2vstar(P) (z_ctypes_4_Voidstar)(P)
#define z_sysincl_exp_2AA_vstar2ref(P) (z_ctypes_4_Voidstar)(P)
#define z_sysincl_exp_2AB_ref2vstarstar(P) (z_ctypes_5_Voidstarstar)(P)

/*****
* NEWTYPE Ref_sysincl_exp_tagMACADDR  (HEADING section)
* <<PACKAGE sysincl_exp>>
* #SDTREF(TEXT,C:\\Kolevatov\\Projects\\SDL\\STACK80211\\export_sdl_exp.h,44)
******/
#ifndef XOPTSORT
extern XCONST struct xSortIdStruct ySrtR_z_sysincl_exp_2B_Ref_sysincl_exp_tagMACADDR;
#define ySrtN_z_sysincl_exp_2B_Ref_sysincl_exp_tagMACADDR  (&ySrtR_z_sysincl_exp_2B_Ref_sysincl_exp_tagMACADDR)
#endif

#define yAssF_z_sysincl_exp_2B_Ref_sysincl_exp_tagMACADDR(V,E,A)  V = E
#define yEqF_z_sysincl_exp_2B_Ref_sysincl_exp_tagMACADDR(Expr1,Expr2)  (Expr1) == (Expr2)
#define yNEqF_z_sysincl_exp_2B_Ref_sysincl_exp_tagMACADDR(Expr1,Expr2)  (Expr1) != (Expr2)
extern void * yMkAddr_z_sysincl_exp_2B_Ref_sysincl_exp_tagMACADDR (z_sysincl_exp_2B_Ref_sysincl_exp_tagMACADDR, z_sysincl_exp_2B_Ref_sysincl_exp_tagMACADDR *);
#ifndef ANY_z_sysincl_exp_2B_Ref_sysincl_exp_tagMACADDR
#define ANY_z_sysincl_exp_2B_Ref_sysincl_exp_tagMACADDR 0
#endif
#define z_sysincl_exp_2BF_copy(P)  P
#ifdef XVALIDATOR_LIB
#define yAll_z_sysincl_exp_2B_Ref_sysincl_exp_tagMACADDR() (z_sysincl_exp_2B_Ref_sysincl_exp_tagMACADDR)XALLOC_REF_VAL(sizeof(z_sysincl_exp_1R_tagMACADDR), ySrtN_z_sysincl_exp_2B_Ref_sysincl_exp_tagMACADDR)
#else
#define yAll_z_sysincl_exp_2B_Ref_sysincl_exp_tagMACADDR() (z_sysincl_exp_2B_Ref_sysincl_exp_tagMACADDR)XALLOC(sizeof(z_sysincl_exp_1R_tagMACADDR), \
  (tSDLTypeInfo *)&ySDL_z_sysincl_exp_2B_Ref_sysincl_exp_tagMACADDR)
#endif
#define yPlus_z_sysincl_exp_2B_Ref_sysincl_exp_tagMACADDR(P1,P2) (P1+P2)
#define yMinus_z_sysincl_exp_2B_Ref_sysincl_exp_tagMACADDR(P1,P2) (P1-P2)
#define z_sysincl_exp_2B0_Null() 0
#define z_sysincl_exp_2B1_Alloc() yAll_z_sysincl_exp_2B_Ref_sysincl_exp_tagMACADDR()
#ifdef XVALIDATOR_LIB
#define z_sysincl_exp_2B6_free(P) XFREE_REF_VAL((void **)(P), sizeof(z_sysincl_exp_1R_tagMACADDR))
#else
#define z_sysincl_exp_2B6_free(P) XFREE((void **)(P), sizeof(z_sysincl_exp_1R_tagMACADDR))
#endif
#define z_sysincl_exp_2B9_ref2vstar(P) (z_ctypes_4_Voidstar)(P)
#define z_sysincl_exp_2BA_vstar2ref(P) (z_ctypes_4_Voidstar)(P)
#define z_sysincl_exp_2BB_ref2vstarstar(P) (z_ctypes_5_Voidstarstar)(P)

/*****
* NEWTYPE Ref_sysincl_exp_tagFLATARRAY  (HEADING section)
* <<PACKAGE sysincl_exp>>
* #SDTREF(TEXT,C:\\Kolevatov\\Projects\\SDL\\STACK80211\\export_sdl_exp.h,44)
******/
#ifndef XOPTSORT
extern XCONST struct xSortIdStruct ySrtR_z_sysincl_exp_2C_Ref_sysincl_exp_tagFLATARRAY;
#define ySrtN_z_sysincl_exp_2C_Ref_sysincl_exp_tagFLATARRAY  (&ySrtR_z_sysincl_exp_2C_Ref_sysincl_exp_tagFLATARRAY)
#endif

#define yAssF_z_sysincl_exp_2C_Ref_sysincl_exp_tagFLATARRAY(V,E,A)  V = E
#define yEqF_z_sysincl_exp_2C_Ref_sysincl_exp_tagFLATARRAY(Expr1,Expr2)  (Expr1) == (Expr2)
#define yNEqF_z_sysincl_exp_2C_Ref_sysincl_exp_tagFLATARRAY(Expr1,Expr2)  (Expr1) != (Expr2)
extern void * yMkAddr_z_sysincl_exp_2C_Ref_sysincl_exp_tagFLATARRAY (z_sysincl_exp_2C_Ref_sysincl_exp_tagFLATARRAY, z_sysincl_exp_2C_Ref_sysincl_exp_tagFLATARRAY *);
#ifndef ANY_z_sysincl_exp_2C_Ref_sysincl_exp_tagFLATARRAY
#define ANY_z_sysincl_exp_2C_Ref_sysincl_exp_tagFLATARRAY 0
#endif
#define z_sysincl_exp_2CF_copy(P)  P
#ifdef XVALIDATOR_LIB
#define yAll_z_sysincl_exp_2C_Ref_sysincl_exp_tagFLATARRAY() (z_sysincl_exp_2C_Ref_sysincl_exp_tagFLATARRAY)XALLOC_REF_VAL(sizeof(z_sysincl_exp_1U_tagFLATARRAY), ySrtN_z_sysincl_exp_2C_Ref_sysincl_exp_tagFLATARRAY)
#else
#define yAll_z_sysincl_exp_2C_Ref_sysincl_exp_tagFLATARRAY() (z_sysincl_exp_2C_Ref_sysincl_exp_tagFLATARRAY)XALLOC(sizeof(z_sysincl_exp_1U_tagFLATARRAY), \
  (tSDLTypeInfo *)&ySDL_z_sysincl_exp_2C_Ref_sysincl_exp_tagFLATARRAY)
#endif
#define yPlus_z_sysincl_exp_2C_Ref_sysincl_exp_tagFLATARRAY(P1,P2) (P1+P2)
#define yMinus_z_sysincl_exp_2C_Ref_sysincl_exp_tagFLATARRAY(P1,P2) (P1-P2)
#define z_sysincl_exp_2C0_Null() 0
#define z_sysincl_exp_2C1_Alloc() yAll_z_sysincl_exp_2C_Ref_sysincl_exp_tagFLATARRAY()
#ifdef XVALIDATOR_LIB
#define z_sysincl_exp_2C6_free(P) XFREE_REF_VAL((void **)(P), sizeof(z_sysincl_exp_1U_tagFLATARRAY))
#else
#define z_sysincl_exp_2C6_free(P) XFREE((void **)(P), sizeof(z_sysincl_exp_1U_tagFLATARRAY))
#endif
#define z_sysincl_exp_2C9_ref2vstar(P) (z_ctypes_4_Voidstar)(P)
#define z_sysincl_exp_2CA_vstar2ref(P) (z_ctypes_4_Voidstar)(P)
#define z_sysincl_exp_2CB_ref2vstarstar(P) (z_ctypes_5_Voidstarstar)(P)

/*****
* NEWTYPE Ref_sysincl_exp_tagFLDPSDU  (HEADING section)
* <<PACKAGE sysincl_exp>>
* #SDTREF(TEXT,C:\\Kolevatov\\Projects\\SDL\\STACK80211\\export_sdl_exp.h,45)
******/
#ifndef XOPTSORT
extern XCONST struct xSortIdStruct ySrtR_z_sysincl_exp_2D_Ref_sysincl_exp_tagFLDPSDU;
#define ySrtN_z_sysincl_exp_2D_Ref_sysincl_exp_tagFLDPSDU  (&ySrtR_z_sysincl_exp_2D_Ref_sysincl_exp_tagFLDPSDU)
#endif

#define yAssF_z_sysincl_exp_2D_Ref_sysincl_exp_tagFLDPSDU(V,E,A)  V = E
#define yEqF_z_sysincl_exp_2D_Ref_sysincl_exp_tagFLDPSDU(Expr1,Expr2)  (Expr1) == (Expr2)
#define yNEqF_z_sysincl_exp_2D_Ref_sysincl_exp_tagFLDPSDU(Expr1,Expr2)  (Expr1) != (Expr2)
extern void * yMkAddr_z_sysincl_exp_2D_Ref_sysincl_exp_tagFLDPSDU (z_sysincl_exp_2D_Ref_sysincl_exp_tagFLDPSDU, z_sysincl_exp_2D_Ref_sysincl_exp_tagFLDPSDU *);
#ifndef ANY_z_sysincl_exp_2D_Ref_sysincl_exp_tagFLDPSDU
#define ANY_z_sysincl_exp_2D_Ref_sysincl_exp_tagFLDPSDU 0
#endif
#define z_sysincl_exp_2DF_copy(P)  P
#ifdef XVALIDATOR_LIB
#define yAll_z_sysincl_exp_2D_Ref_sysincl_exp_tagFLDPSDU() (z_sysincl_exp_2D_Ref_sysincl_exp_tagFLDPSDU)XALLOC_REF_VAL(sizeof(z_sysincl_exp_20_tagFLDPSDU), ySrtN_z_sysincl_exp_2D_Ref_sysincl_exp_tagFLDPSDU)
#else
#define yAll_z_sysincl_exp_2D_Ref_sysincl_exp_tagFLDPSDU() (z_sysincl_exp_2D_Ref_sysincl_exp_tagFLDPSDU)XALLOC(sizeof(z_sysincl_exp_20_tagFLDPSDU), \
  (tSDLTypeInfo *)&ySDL_z_sysincl_exp_2D_Ref_sysincl_exp_tagFLDPSDU)
#endif
#define yPlus_z_sysincl_exp_2D_Ref_sysincl_exp_tagFLDPSDU(P1,P2) (P1+P2)
#define yMinus_z_sysincl_exp_2D_Ref_sysincl_exp_tagFLDPSDU(P1,P2) (P1-P2)
#define z_sysincl_exp_2D0_Null() 0
#define z_sysincl_exp_2D1_Alloc() yAll_z_sysincl_exp_2D_Ref_sysincl_exp_tagFLDPSDU()
#ifdef XVALIDATOR_LIB
#define z_sysincl_exp_2D6_free(P) XFREE_REF_VAL((void **)(P), sizeof(z_sysincl_exp_20_tagFLDPSDU))
#else
#define z_sysincl_exp_2D6_free(P) XFREE((void **)(P), sizeof(z_sysincl_exp_20_tagFLDPSDU))
#endif
#define z_sysincl_exp_2D9_ref2vstar(P) (z_ctypes_4_Voidstar)(P)
#define z_sysincl_exp_2DA_vstar2ref(P) (z_ctypes_4_Voidstar)(P)
#define z_sysincl_exp_2DB_ref2vstarstar(P) (z_ctypes_5_Voidstarstar)(P)

/*****
* NEWTYPE Ref_sysincl_exp_tagBITSEQ  (HEADING section)
* <<PACKAGE sysincl_exp>>
* #SDTREF(TEXT,C:\\Kolevatov\\Projects\\SDL\\STACK80211\\export_sdl_exp.h,71)
******/
#ifndef XOPTSORT
extern XCONST struct xSortIdStruct ySrtR_z_sysincl_exp_2E_Ref_sysincl_exp_tagBITSEQ;
#define ySrtN_z_sysincl_exp_2E_Ref_sysincl_exp_tagBITSEQ  (&ySrtR_z_sysincl_exp_2E_Ref_sysincl_exp_tagBITSEQ)
#endif

#define yAssF_z_sysincl_exp_2E_Ref_sysincl_exp_tagBITSEQ(V,E,A)  V = E
#define yEqF_z_sysincl_exp_2E_Ref_sysincl_exp_tagBITSEQ(Expr1,Expr2)  (Expr1) == (Expr2)
#define yNEqF_z_sysincl_exp_2E_Ref_sysincl_exp_tagBITSEQ(Expr1,Expr2)  (Expr1) != (Expr2)
extern void * yMkAddr_z_sysincl_exp_2E_Ref_sysincl_exp_tagBITSEQ (z_sysincl_exp_2E_Ref_sysincl_exp_tagBITSEQ, z_sysincl_exp_2E_Ref_sysincl_exp_tagBITSEQ *);
#ifndef ANY_z_sysincl_exp_2E_Ref_sysincl_exp_tagBITSEQ
#define ANY_z_sysincl_exp_2E_Ref_sysincl_exp_tagBITSEQ 0
#endif
#define z_sysincl_exp_2EF_copy(P)  P
#ifdef XVALIDATOR_LIB
#define yAll_z_sysincl_exp_2E_Ref_sysincl_exp_tagBITSEQ() (z_sysincl_exp_2E_Ref_sysincl_exp_tagBITSEQ)XALLOC_REF_VAL(sizeof(z_sysincl_exp_23_tagBITSEQ), ySrtN_z_sysincl_exp_2E_Ref_sysincl_exp_tagBITSEQ)
#else
#define yAll_z_sysincl_exp_2E_Ref_sysincl_exp_tagBITSEQ() (z_sysincl_exp_2E_Ref_sysincl_exp_tagBITSEQ)XALLOC(sizeof(z_sysincl_exp_23_tagBITSEQ), \
  (tSDLTypeInfo *)&ySDL_z_sysincl_exp_2E_Ref_sysincl_exp_tagBITSEQ)
#endif
#define yPlus_z_sysincl_exp_2E_Ref_sysincl_exp_tagBITSEQ(P1,P2) (P1+P2)
#define yMinus_z_sysincl_exp_2E_Ref_sysincl_exp_tagBITSEQ(P1,P2) (P1-P2)
#define z_sysincl_exp_2E0_Null() 0
#define z_sysincl_exp_2E1_Alloc() yAll_z_sysincl_exp_2E_Ref_sysincl_exp_tagBITSEQ()
#ifdef XVALIDATOR_LIB
#define z_sysincl_exp_2E6_free(P) XFREE_REF_VAL((void **)(P), sizeof(z_sysincl_exp_23_tagBITSEQ))
#else
#define z_sysincl_exp_2E6_free(P) XFREE((void **)(P), sizeof(z_sysincl_exp_23_tagBITSEQ))
#endif
#define z_sysincl_exp_2E9_ref2vstar(P) (z_ctypes_4_Voidstar)(P)
#define z_sysincl_exp_2EA_vstar2ref(P) (z_ctypes_4_Voidstar)(P)
#define z_sysincl_exp_2EB_ref2vstarstar(P) (z_ctypes_5_Voidstarstar)(P)

/*****
* NEWTYPE Ref_sysincl_exp_tagSIGNAL  (HEADING section)
* <<PACKAGE sysincl_exp>>
* #SDTREF(TEXT,C:\\Kolevatov\\Projects\\SDL\\STACK80211\\export_sdl_exp.h,71)
******/
#ifndef XOPTSORT
extern XCONST struct xSortIdStruct ySrtR_z_sysincl_exp_2F_Ref_sysincl_exp_tagSIGNAL;
#define ySrtN_z_sysincl_exp_2F_Ref_sysincl_exp_tagSIGNAL  (&ySrtR_z_sysincl_exp_2F_Ref_sysincl_exp_tagSIGNAL)
#endif

#define yAssF_z_sysincl_exp_2F_Ref_sysincl_exp_tagSIGNAL(V,E,A)  V = E
#define yEqF_z_sysincl_exp_2F_Ref_sysincl_exp_tagSIGNAL(Expr1,Expr2)  (Expr1) == (Expr2)
#define yNEqF_z_sysincl_exp_2F_Ref_sysincl_exp_tagSIGNAL(Expr1,Expr2)  (Expr1) != (Expr2)
extern void * yMkAddr_z_sysincl_exp_2F_Ref_sysincl_exp_tagSIGNAL (z_sysincl_exp_2F_Ref_sysincl_exp_tagSIGNAL, z_sysincl_exp_2F_Ref_sysincl_exp_tagSIGNAL *);
#ifndef ANY_z_sysincl_exp_2F_Ref_sysincl_exp_tagSIGNAL
#define ANY_z_sysincl_exp_2F_Ref_sysincl_exp_tagSIGNAL 0
#endif
#define z_sysincl_exp_2FF_copy(P)  P
#ifdef XVALIDATOR_LIB
#define yAll_z_sysincl_exp_2F_Ref_sysincl_exp_tagSIGNAL() (z_sysincl_exp_2F_Ref_sysincl_exp_tagSIGNAL)XALLOC_REF_VAL(sizeof(z_sysincl_exp_21_tagSIGNAL), ySrtN_z_sysincl_exp_2F_Ref_sysincl_exp_tagSIGNAL)
#else
#define yAll_z_sysincl_exp_2F_Ref_sysincl_exp_tagSIGNAL() (z_sysincl_exp_2F_Ref_sysincl_exp_tagSIGNAL)XALLOC(sizeof(z_sysincl_exp_21_tagSIGNAL), \
  (tSDLTypeInfo *)&ySDL_z_sysincl_exp_2F_Ref_sysincl_exp_tagSIGNAL)
#endif
#define yPlus_z_sysincl_exp_2F_Ref_sysincl_exp_tagSIGNAL(P1,P2) (P1+P2)
#define yMinus_z_sysincl_exp_2F_Ref_sysincl_exp_tagSIGNAL(P1,P2) (P1-P2)
#define z_sysincl_exp_2F0_Null() 0
#define z_sysincl_exp_2F1_Alloc() yAll_z_sysincl_exp_2F_Ref_sysincl_exp_tagSIGNAL()
#ifdef XVALIDATOR_LIB
#define z_sysincl_exp_2F6_free(P) XFREE_REF_VAL((void **)(P), sizeof(z_sysincl_exp_21_tagSIGNAL))
#else
#define z_sysincl_exp_2F6_free(P) XFREE((void **)(P), sizeof(z_sysincl_exp_21_tagSIGNAL))
#endif
#define z_sysincl_exp_2F9_ref2vstar(P) (z_ctypes_4_Voidstar)(P)
#define z_sysincl_exp_2FA_vstar2ref(P) (z_ctypes_4_Voidstar)(P)
#define z_sysincl_exp_2FB_ref2vstarstar(P) (z_ctypes_5_Voidstarstar)(P)

/*****
* NEWTYPE Ref_sysincl_exp_tagSYMBOL  (HEADING section)
* <<PACKAGE sysincl_exp>>
* #SDTREF(TEXT,C:\\Kolevatov\\Projects\\SDL\\STACK80211\\export_sdl_exp.h,75)
******/
#ifndef XOPTSORT
extern XCONST struct xSortIdStruct ySrtR_z_sysincl_exp_2G_Ref_sysincl_exp_tagSYMBOL;
#define ySrtN_z_sysincl_exp_2G_Ref_sysincl_exp_tagSYMBOL  (&ySrtR_z_sysincl_exp_2G_Ref_sysincl_exp_tagSYMBOL)
#endif

#define yAssF_z_sysincl_exp_2G_Ref_sysincl_exp_tagSYMBOL(V,E,A)  V = E
#define yEqF_z_sysincl_exp_2G_Ref_sysincl_exp_tagSYMBOL(Expr1,Expr2)  (Expr1) == (Expr2)
#define yNEqF_z_sysincl_exp_2G_Ref_sysincl_exp_tagSYMBOL(Expr1,Expr2)  (Expr1) != (Expr2)
extern void * yMkAddr_z_sysincl_exp_2G_Ref_sysincl_exp_tagSYMBOL (z_sysincl_exp_2G_Ref_sysincl_exp_tagSYMBOL, z_sysincl_exp_2G_Ref_sysincl_exp_tagSYMBOL *);
#ifndef ANY_z_sysincl_exp_2G_Ref_sysincl_exp_tagSYMBOL
#define ANY_z_sysincl_exp_2G_Ref_sysincl_exp_tagSYMBOL 0
#endif
#define z_sysincl_exp_2GF_copy(P)  P
#ifdef XVALIDATOR_LIB
#define yAll_z_sysincl_exp_2G_Ref_sysincl_exp_tagSYMBOL() (z_sysincl_exp_2G_Ref_sysincl_exp_tagSYMBOL)XALLOC_REF_VAL(sizeof(z_sysincl_exp_26_tagSYMBOL), ySrtN_z_sysincl_exp_2G_Ref_sysincl_exp_tagSYMBOL)
#else
#define yAll_z_sysincl_exp_2G_Ref_sysincl_exp_tagSYMBOL() (z_sysincl_exp_2G_Ref_sysincl_exp_tagSYMBOL)XALLOC(sizeof(z_sysincl_exp_26_tagSYMBOL), \
  (tSDLTypeInfo *)&ySDL_z_sysincl_exp_2G_Ref_sysincl_exp_tagSYMBOL)
#endif
#define yPlus_z_sysincl_exp_2G_Ref_sysincl_exp_tagSYMBOL(P1,P2) (P1+P2)
#define yMinus_z_sysincl_exp_2G_Ref_sysincl_exp_tagSYMBOL(P1,P2) (P1-P2)
#define z_sysincl_exp_2G0_Null() 0
#define z_sysincl_exp_2G1_Alloc() yAll_z_sysincl_exp_2G_Ref_sysincl_exp_tagSYMBOL()
#ifdef XVALIDATOR_LIB
#define z_sysincl_exp_2G6_free(P) XFREE_REF_VAL((void **)(P), sizeof(z_sysincl_exp_26_tagSYMBOL))
#else
#define z_sysincl_exp_2G6_free(P) XFREE((void **)(P), sizeof(z_sysincl_exp_26_tagSYMBOL))
#endif
#define z_sysincl_exp_2G9_ref2vstar(P) (z_ctypes_4_Voidstar)(P)
#define z_sysincl_exp_2GA_vstar2ref(P) (z_ctypes_4_Voidstar)(P)
#define z_sysincl_exp_2GB_ref2vstarstar(P) (z_ctypes_5_Voidstarstar)(P)

/*****
* NEWTYPE Ref_sysincl_exp_tagMDM_SAMPLES  (HEADING section)
* <<PACKAGE sysincl_exp>>
* #SDTREF(TEXT,C:\\Kolevatov\\Projects\\SDL\\STACK80211\\export_sdl_exp.h,103)
******/
#ifndef XOPTSORT
extern XCONST struct xSortIdStruct ySrtR_z_sysincl_exp_2H_Ref_sysincl_exp_tagMDM_SAMPLES;
#define ySrtN_z_sysincl_exp_2H_Ref_sysincl_exp_tagMDM_SAMPLES  (&ySrtR_z_sysincl_exp_2H_Ref_sysincl_exp_tagMDM_SAMPLES)
#endif

#define yAssF_z_sysincl_exp_2H_Ref_sysincl_exp_tagMDM_SAMPLES(V,E,A)  V = E
#define yEqF_z_sysincl_exp_2H_Ref_sysincl_exp_tagMDM_SAMPLES(Expr1,Expr2)  (Expr1) == (Expr2)
#define yNEqF_z_sysincl_exp_2H_Ref_sysincl_exp_tagMDM_SAMPLES(Expr1,Expr2)  (Expr1) != (Expr2)
extern void * yMkAddr_z_sysincl_exp_2H_Ref_sysincl_exp_tagMDM_SAMPLES (z_sysincl_exp_2H_Ref_sysincl_exp_tagMDM_SAMPLES, z_sysincl_exp_2H_Ref_sysincl_exp_tagMDM_SAMPLES *);
#ifndef ANY_z_sysincl_exp_2H_Ref_sysincl_exp_tagMDM_SAMPLES
#define ANY_z_sysincl_exp_2H_Ref_sysincl_exp_tagMDM_SAMPLES 0
#endif
#define z_sysincl_exp_2HF_copy(P)  P
#ifdef XVALIDATOR_LIB
#define yAll_z_sysincl_exp_2H_Ref_sysincl_exp_tagMDM_SAMPLES() (z_sysincl_exp_2H_Ref_sysincl_exp_tagMDM_SAMPLES)XALLOC_REF_VAL(sizeof(z_sysincl_exp_28_tagMDM_SAMPLES), ySrtN_z_sysincl_exp_2H_Ref_sysincl_exp_tagMDM_SAMPLES)
#else
#define yAll_z_sysincl_exp_2H_Ref_sysincl_exp_tagMDM_SAMPLES() (z_sysincl_exp_2H_Ref_sysincl_exp_tagMDM_SAMPLES)XALLOC(sizeof(z_sysincl_exp_28_tagMDM_SAMPLES), \
  (tSDLTypeInfo *)&ySDL_z_sysincl_exp_2H_Ref_sysincl_exp_tagMDM_SAMPLES)
#endif
#define yPlus_z_sysincl_exp_2H_Ref_sysincl_exp_tagMDM_SAMPLES(P1,P2) (P1+P2)
#define yMinus_z_sysincl_exp_2H_Ref_sysincl_exp_tagMDM_SAMPLES(P1,P2) (P1-P2)
#define z_sysincl_exp_2H0_Null() 0
#define z_sysincl_exp_2H1_Alloc() yAll_z_sysincl_exp_2H_Ref_sysincl_exp_tagMDM_SAMPLES()
#ifdef XVALIDATOR_LIB
#define z_sysincl_exp_2H6_free(P) XFREE_REF_VAL((void **)(P), sizeof(z_sysincl_exp_28_tagMDM_SAMPLES))
#else
#define z_sysincl_exp_2H6_free(P) XFREE((void **)(P), sizeof(z_sysincl_exp_28_tagMDM_SAMPLES))
#endif
#define z_sysincl_exp_2H9_ref2vstar(P) (z_ctypes_4_Voidstar)(P)
#define z_sysincl_exp_2HA_vstar2ref(P) (z_ctypes_4_Voidstar)(P)
#define z_sysincl_exp_2HB_ref2vstarstar(P) (z_ctypes_5_Voidstarstar)(P)

/*****
* NEWTYPE Ref_sysincl_exp_Real  (HEADING section)
* <<PACKAGE sysincl_exp>>
* #SDTREF(TEXT,C:\\Kolevatov\\Projects\\SDL\\STACK80211\\export_sdl_exp.h,109)
******/
#ifndef XOPTSORT
extern XCONST struct xSortIdStruct ySrtR_z_sysincl_exp_2I_Ref_sysincl_exp_Real;
#define ySrtN_z_sysincl_exp_2I_Ref_sysincl_exp_Real  (&ySrtR_z_sysincl_exp_2I_Ref_sysincl_exp_Real)
#endif

#define yAssF_z_sysincl_exp_2I_Ref_sysincl_exp_Real(V,E,A)  V = E
#define yEqF_z_sysincl_exp_2I_Ref_sysincl_exp_Real(Expr1,Expr2)  (Expr1) == (Expr2)
#define yNEqF_z_sysincl_exp_2I_Ref_sysincl_exp_Real(Expr1,Expr2)  (Expr1) != (Expr2)
extern void * yMkAddr_z_sysincl_exp_2I_Ref_sysincl_exp_Real (z_sysincl_exp_2I_Ref_sysincl_exp_Real, z_sysincl_exp_2I_Ref_sysincl_exp_Real *);
#ifndef ANY_z_sysincl_exp_2I_Ref_sysincl_exp_Real
#define ANY_z_sysincl_exp_2I_Ref_sysincl_exp_Real 0
#endif
#define z_sysincl_exp_2IF_copy(P)  P
#ifdef XVALIDATOR_LIB
#define yAll_z_sysincl_exp_2I_Ref_sysincl_exp_Real() (z_sysincl_exp_2I_Ref_sysincl_exp_Real)XALLOC_REF_VAL(sizeof(SDL_Real), ySrtN_z_sysincl_exp_2I_Ref_sysincl_exp_Real)
#else
#define yAll_z_sysincl_exp_2I_Ref_sysincl_exp_Real() (z_sysincl_exp_2I_Ref_sysincl_exp_Real)XALLOC(sizeof(SDL_Real), \
  (tSDLTypeInfo *)&ySDL_z_sysincl_exp_2I_Ref_sysincl_exp_Real)
#endif
#define yPlus_z_sysincl_exp_2I_Ref_sysincl_exp_Real(P1,P2) (P1+P2)
#define yMinus_z_sysincl_exp_2I_Ref_sysincl_exp_Real(P1,P2) (P1-P2)
#define z_sysincl_exp_2I0_Null() 0
#define z_sysincl_exp_2I1_Alloc() yAll_z_sysincl_exp_2I_Ref_sysincl_exp_Real()
#ifdef XVALIDATOR_LIB
#define z_sysincl_exp_2I6_free(P) XFREE_REF_VAL((void **)(P), sizeof(SDL_Real))
#else
#define z_sysincl_exp_2I6_free(P) XFREE((void **)(P), sizeof(SDL_Real))
#endif
#define z_sysincl_exp_2I9_ref2vstar(P) (z_ctypes_4_Voidstar)(P)
#define z_sysincl_exp_2IA_vstar2ref(P) (z_ctypes_4_Voidstar)(P)
#define z_sysincl_exp_2IB_ref2vstarstar(P) (z_ctypes_5_Voidstarstar)(P)

/*************************************************************************
**                #CODE directives, #HEADING sections                   **
*************************************************************************/
                /* #SDTREF(TEXT,C:\\Kolevatov\\Projects\\SDL\\STACK80211\\sysincl_exp.h,16) */
#define Set_MS(i) (H2SDL_USCR(MS) = (i))
#define Get_MS() (MS)

#endif
